### ISSUE TITLE
How does Irmin handle rename conflicts?

### ISSUE THREAD

**Issue by TyOverby** [mirage/irmin#1006]
I’m looking at the `move` example in the [tutorial](https://irmin.org/tutorial/getting-started) and am wondering how Irmin handles rename conflicts, especially in a distributed world where syncing happens infrequently.

Example: 
- user 1 : rename foo.txt to bar.txt
- user 2 : set “some content” to foo.txt

My understanding of the “transaction example” is that “user 1” is really doing 
1. Read `$content` from foo.txt
2. Delete foo.txt
3. Set bar.txt to `$content`

I have to admit, I don’t know how Git resolves conflicts like this, but what is Irmin’s resolution strategy?

**Comment by CraigFe** [comment]
Good question. Your understanding of the transaction example is correct. Irmin has no meaningful notion of a "rename" operation. Indeed, Irmin doesn't track _any_ information at the operation level: merging is purely _state-based_, i.e. determined by the structure / contents of the trees being merged. 

This is true of Git too – it has no understanding of operations, only of current state – so how does it do it? Firstly, Git draws a distinction between merge _strategies_ and merge _drivers_. A merge strategy operates over commits/trees, and delegates to a merge driver to merge blobs. Certain merge strategies in `git` use similarity heuristics to try to reverse-engineer rename operations at the commit level (see `git diff-tree --find-renames`). Irmin does no such thing: contents stored at different paths will _never_ be compared.

Using Git terminology, Irmin allows the user to define something like a 'driver' but provides only a single 'strategy' with no heuristics. In your example, the resolution strategy recurses over non-equal subtrees until it hits the `foo.txt` base case, at which point the result depends on the user's driver:

```ocaml
user_supplied_merge
  ~common_ancestor:(Some "old content")
  None                                   (* [foo.txt] from user1's tree *)
  (Some "content")                       (* [foo.txt] from user2's tree *)
```

It's possible to build a store that _does_ have a notion of a rename operation by building a higher-level API that tracks operations in the store itself (something like an "_operation-based CRDT_"). At that point, the user's merge driver effectively acts as a merge _strategy_ and can be more expressive.

Operation-based encodings aside, we've discussed some proposals that would allow the user much more control over the tree-level merge logic, but not yet found anything elegant enough :slightly_smiling_face:

**Comment by TyOverby** [comment]
I see, so at the moment there’s nothing built-in that would handle renames without making a custom store?

**Comment by avsm** [comment]
It's hard to answer your question more precisely without more context of what you're trying to achieve.  Your application may be better off handling this at a higher level, as @CraigFe suggested. For example, see the 3-way merge strategy Cuekeeper uses to ensure all merged operations are 'loadable' (viewable) in the todolist: https://roscidus.com/blog/blog/2015/04/28/cuekeeper-gitting-things-done-in-the-browser/#check-before-merge

**Comment by TyOverby** [comment]
Oh wow; what a great blog post!

I've begun exploring Irmin's semantics by writing some [expect-tests](https://github.com/TyOverby/ebu/blob/master/test/irmin_tests.ml) and I think I have a much better understanding of how it works now!

Thanks for the help @CraigFe and @avsm

**Comment by avsm** [comment]
Glad to help - please do contribute back your learnings; we'd love to link to your sample app and/or integrate what you've learnt into the tutorial.
