### ISSUE TITLE
irmin-pack: ensure snapshot-isolation of read-only instances

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1040]
This is the counterpart of https://github.com/mirage/index/pull/198

We'd like `irmin-pack` read-only instances to always stay valid, whatever happens. E.g. a concurrent `clear` + `adds` should not lead to valid reads in the read-only instance. To see any new values, the read-only instance should use `sync`.

This is a bit different from the other backends, where read-only instance can see when values are removed/added without the need for an explicit sync. But this is needed to ensure that 1/ irmin-pack read-only instances do not keep reading the file headers to check if the file have been clearer; and 3/ irmin-pack read-only instances always read valid data.

**Comment by samoht** [comment]
@icristescu is this fixed?

**Comment by icristescu** [comment]
Indeed, this is covered by the tests [here](https://github.com/mirage/irmin/blob/master/test/irmin-pack/multiple_instances.ml#L134), [here](https://github.com/mirage/irmin/blob/master/test/irmin-pack/test_pack.ml#L457) and [here](https://github.com/mirage/irmin/blob/master/test/irmin-pack/test_pack.ml#L486).
