### ISSUE TITLE
Update wiki to new API

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#105]

**Comment by yansh** [comment]
+1 Badly needed. How can I help with this one?  How about I create a wiki page and start writing up on the API I use. You can correct me if I am getting it wrong. I think it would be a good start towards proper documentation.

**Comment by samoht** [comment]
That would be great if you could do that! Thanks!

**Comment by yansh** [comment]
Cool. On it. :+1:

**Comment by samoht** [comment]
I made a new pass on it, to simplify few bits. Still need some work, but that's a good start. Thanks!

**Comment by yansh** [comment]
Awesome. I will keep on it. I think we need to assume no prior knowledge of Irmin and explain the purpose of each element, maybe even provide a description of sample scenarios where different elements can be used.

**Comment by yansh** [comment]
@talex5 thanks for editing the wiki looks awesome. @samoht I think Wiki is an intermediate solution, we need to think longer term and provide proper documentation for all Irmin versions because people using previous versions of Irmin might find it confusing, especially as the API changes in the future.

**Comment by samoht** [comment]
@yansh Sure. A solution is to move the wiki pages into the repo (and build proper user manual). But I don't really plan to document how to transition for one version of the API to another (at least, not until 1.0.0 is properly released: I consider current user as "friendly" beta tester who might survive if I change the API :p)

**Comment by samoht** [comment]
I'll move the wiki pages to the repo once they are stabilised and than you think (as an early user) that they are sufficiently clear.

**Comment by yansh** [comment]
I added a section on custom merge. Honestly, I only get some of it: you define your custom structure, then you define merge for it, but the custom_merge example looks more sophisticated than just that. I will try to understand it better, but any tips/comments would go along way :)

**Comment by samoht** [comment]
Thanks, I've tried to improve the section a little bit, but I'm not happy with the result. Will continue to work on that later.

**Comment by yansh** [comment]
awesome. thanks - I find it very helpful. Let's keep working on it. I will add stuff as soon as I figure them out.

**Comment by yansh** [comment]
@talex5 @samoht  I added some pointer on Views api.  I will try to elaborate on them and provide better examples soon. Have a look and add additional API that are worth writing about.

**Comment by samoht** [comment]
As the wiki tend to become out-of-date pretty quickly, I have removed the page completely. The current examples and the online docs are currently the only source of truth. I also plan to write a small blog post to help getting started with the new API.
