### ISSUE TITLE
Mirage support

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#107]
This issue is used to track the integration with mirage. What needs to be done:
- [x] Remove the dependency to `Unix` for the logging library (https://github.com/UnixJunkie/dolog/pull/14). Might end-up using something else.
- [x] New release of `cohttp` with https://github.com/mirage/ocaml-cohttp/pull/267
- [x] New release of `mirage-http` with https://github.com/mirage/mirage-http/pull/10
- [x] New release of `conduit` with a fix for https://github.com/mirage/ocaml-conduit/pull/45
- [x] Add `Git_mirage` for Mirage IO (https://github.com/mirage/ocaml-git/pull/70)
- [x] Massage `mirage-dev` packages (https://github.com/mirage/mirage-dev/pull/56). Would be much easier if we had a pure OCaml implementation of:
  - [SHA1](https://github.com/dbuenzli/uuidm/blob/master/src/uuidm.ml#L21-#L124)
  - [zlib](https://github.com/mirage/mirage-www/wiki/Pioneer-Projects#deflate-zlib-in-pure-ocaml)
- [x] Smart HTTP Git support (https://github.com/mirage/ocaml-git/issues/26) 
- [ ] Implement `Git.FS` using raw block devices
- [x] Add `Irmin_mirage`
- [x] Add a unikernel using Irmin (see https://github.com/samoht/mirmin)
- [x] Irmin combinators for Mirage

**Comment by samoht** [comment]
I've updated the list, main blocker is the cohttp PR (I'm not totally convinced that's the right approach but I don't think of anything better).

**Comment by avsm** [comment]
Thanks, I'll be looking at this tomorrow afternoon/Friday

**Comment by yomimono** [comment]
It looks like a lot of the linked PRs have been merged (or provided as branches, in the case of dolog), but I know we're not quite ready for Irmin on unikernels.  When it's convenient, could someone knowledgeable update us on what's missing?

**Comment by samoht** [comment]
yea I wanted to do that yesterday but got caught by other emergencies :p  

I've ticked some boxed, the PR on ocaml-git is the next thing to be updated.

**Comment by talex5** [comment]
I get a bunch of link errors on Xen (e.g. `/home/tal/.opam/4.01.0-ck/build/bin_prot.111.03.00/_build/lib/read.ml:598: undefined reference to `bin_prot_blit_buf_float_array_stub'). Is there a branch somewhere I need to pin?

**Comment by rgrinberg** [comment]
There's a new, pure OCaml implementation of zlib here btw https://github.com/dinosaure/Decompress

**Comment by talex5** [comment]
I've added support for building Xen C stubs to my (now badly named) js_of_ocaml branch:

https://github.com/talex5/bin_prot/tree/js_of_ocaml

**Comment by samoht** [comment]
I've ticked more boxes, basically we have `ocaml-git` working with Xen, now need to massage Irmin (should not be very hard). The main missing piece is have something to persist the data (for instance a block device)

**Comment by samoht** [comment]
Ticking more boxes: now the in-memory Git backend seems to work fine with Mirage (although more testing is certainly needed). I'm releasing the various branches now. Having a raw block-device FS backend is the only missing bit.

**Comment by yomimono** [comment]
I get a bunch of link errors on Xen related to bin-prot, as @talex5 reported above.  Is there a fix for those I'm missing?

**Comment by samoht** [comment]
yea, I overlooked the `bin_prot` linking issues ... trying to fix those now.

**Comment by samoht** [comment]
I have some patches here: https://github.com/samoht/bin_prot/tree/xen they seem to work fine, might need some clean-up to have any chance to be integrated upstream ...

**Comment by samoht** [comment]
And I've updated https://github.com/mirage/mirage-dev/pull/56 to include all of the missing packages.

An example of use is here: https://github.com/samoht/mirage-skeleton/blob/irmin/static_website/config.ml#L53

To use it:

```
FS=irmin URI=https://github.com/mirage/mirage-www PATH=tmpl mirage configure
```

**Comment by yomimono** [comment]
I think mirage-xen-posix will need a release as well; my Irmin unikernels fail with `Unsupported function times called in Mini-OS kernel` when not pinned to dev-repo.  Looks like it's fixed by [this patch](https://github.com/talex5/mirage-platform/commit/e4de7b0f35b5b679c5eb2d9ae6cf2417b54b1bf1) from @talex5 which is merged but not in a release.

**Comment by yomimono** [comment]
[This Irmin in-memory-store-backed-ARP-using unikernel](https://github.com/yomimono/example-unikernels/tree/mirarp/irmin-arp-node) now boots and seems to work! :smile_cat:

**Comment by samoht** [comment]
yay!

**Comment by avsm** [comment]
Wow, nice!

**Comment by samoht** [comment]
I've just released a new version of `mirage-xen-ocaml` which includes the `times` patch and I've merged my branch into mirage-dev. Should be working fine by just pinning `mirage-dev` now.

**Comment by samoht** [comment]
Closing this as there is now some kind of support for a mirage backend.
