### ISSUE TITLE
Immutable Views

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#109]
In some case, you want to use immutable views (currently they are mutable). We should add them.

**Comment by talex5** [comment]
Possibly relevant: the recently-opensourced Datakit provides immutable trees for Irmin, which may cover some uses of immutable views:

https://github.com/docker/datakit/blob/master/src/ivfs/ivfs_tree.mli

**Comment by samoht** [comment]
Done in 1.0, see S.Tree.
