### ISSUE TITLE
irmin-pack: add a tool for regenerating the index from the pack file

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#1094]
Each block in the `irmin-pack` pack file is stored along with: its hash, its magic char (kind), and its length (as part of the binary encoding of types). This is enough to reconstruct an index from a pack file, by decoding a stream of objects from the pack file and adding their offsets / kinds to a fresh index.

We should add an endpoint / CLI tool to perform this reconstruction, allowing us to recover stores with corrupted indices.

CC @icristescu, @pascutto, @samoht.

**Comment by samoht** [comment]
What's the status of this? Is it fixed by #1097  ?

**Comment by icristescu** [comment]
Almost, there is a piece missing which is to add the `index_reconstruct` to the [irmin-pack cli]( https://github.com/mirage/irmin/blob/master/src/irmin-pack/checks.ml#L159).
