### ISSUE TITLE
last_modified doesnt consider the key creation as a modification

### ISSUE THREAD

**Issue by clecat** [mirage/irmin#1109]
When trying to use the function last_modified of an `fs_store`, it happened to never return any commits even when the key actually exists.

After looking a bit, it seems that the problem comes from [here](https://github.com/mirage/irmin/blob/7960e4eeb669342cb646486a2357134b1ef767ea/src/irmin/store.ml#L1031):
```ocaml
match (e, current_value) with
| Some x, Some y -> not (Type.equal Contents.t x y)
| Some _, None -> true
| _, _ -> false)
```
This match, which is supposed to consider if the key was modified, is letting the case `None, Some _` (key creation) fall in the wildcard and return false.
It might not be the only problem, but it looks like it is a good place to start investigations.

However, it might be the intended behaviour, if the function was coded in this purpose (not considering the creation of the key as a modification)

**Comment by pascutto** [comment]
I think this is not the intended behaviour and looks like a bug to me indeed. Thanks for catching that!
It looks like this pattern matching could do with a `| None, Some _ -> true` case.

**Comment by samoht** [comment]
@clecat do you mind sending a patch to fix this?

**Comment by clecat** [comment]
Done

**Comment by clecat** [comment]
Should I had it to the file `change.md` as a `fixed` or `changed` ?

**Comment by CraigFe** [comment]
I'd go with `fixed`; I'm not sure we can claim this was intentional.
