### ISSUE TITLE
using Irmin as a beginner

### ISSUE THREAD

**Issue by AntouanK** [mirage/irmin#1112]
Hi there.

Looking to use a git-like db in our product, and we are looking at irmin and dolt right now.
OCaml is very interesting, but I wanted to ask a couple of quick questions to understand the learning curve.
We basically want to switch from mongodb and go into a db that we can branch/merge and log every interaction ( so commits seem ideal for that )

Would a total beginner in OCaml be able to setup an irmin db and a graphql API relatively easily?
( I have experience in Elm and a bit of Haskell, that might help I suppose )

Are there any "real application" examples anywhere to look at?
( trying to figure out how to run the `examples/custom_graphql.ml` file right now, but it seems like a very small example anyway )

Also, is this the best place to ask questions as a beginner? Or the IRC channel? Or something else?

Thank you.

**Comment by avsm** [comment]
Welcome! Have you tried following the Irmin tutorial to begin with? https://irmin.org/tutorial/introduction

**Comment by AntouanK** [comment]
Yes, I did today.
Few questions for example :

- I run `irmin graphql --port 8080` and I get a GraphQL server. Great!
Then I try a mutation to set `foo` to be `bar` ( from what I understand it's key/value like redis is, right? )
```
mutation {
  set(key:"foo", value: "bar"){
    info
  }
}
``` 

how can I read the value now? Or check the diff with master? The queries I see in graphql don't help much.

- going forward with the tutorial, I can see ways to write code to configure everything. Like schema I guess etc.
Which is great! But as a non-ocaml user, I have no idea what file to run and how.
Do I use `~/.irmin/config.yml` to point to my directory and put some .ml file there?
So then when I run `irmin` it compiles it somehow?
I'm a bit lost there in the tutorial.

**Comment by AntouanK** [comment]
side note, when trying 
```
git clone https://github.com/mirage/irmin
cd irmin/
opam install .
```
I get : 
```
➜  test-irmin git:(master) opam install .
ppx_irmin is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-unix is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-type is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version ~dev)
irmin-test is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
The following additional pinnings are required by irmin-pack.2.2.0:
  - index.dev at git+https://github.com/mirage/index#b3b21b6ff21cd23974f8451b0c959f5b183f9d56
Continue? [Y/n] y
[index.dev] synchronised from git+https://github.com/mirage/index#b3b21b6ff21cd23974f8451b0c959f5b183f9d56
index is now pinned to git+https://github.com/mirage/index#b3b21b6ff21cd23974f8451b0c959f5b183f9d56 (version dev)
irmin-pack is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-mirage is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-mirage-graphql is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-mirage-git is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-mem is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-layers is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version ~dev)
irmin-http is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-graphql is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-git is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-fuzz is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version ~dev)
irmin-fs is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
irmin-containers is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version ~dev)
irmin-chunk is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version 2.2.0)
The following additional pinnings are required by irmin-bench.~dev:
  - bechamel.dev at git+https://github.com/dinosaure/bechamel#f1b3db0115af3854422697134a1555e3c07a19f5
Continue? [Y/n] Y
Processing: [bechamel.dev: git]
[bechamel.dev] synchronised from git+https://github.com/dinosaure/bechamel#f1b3db0115af3854422697134a1555e3c07a19f5
bechamel is now pinned to git+https://github.com/dinosaure/bechamel#f1b3db0115af3854422697134a1555e3c07a19f5 (version dev)
irmin-bench is now pinned to git+file:///run/media/antouank/evo1/_REPOS_/_futureon_/test-irmin#master (version ~dev)
The following dependencies couldn't be met:
  - irmin-bench → irmin < 0.7.0
      no matching version

No solution found, exiting
```

_I did try the unpinning as well, same output_

**Comment by AntouanK** [comment]
I tried using dune, I followed the error messages and it ended up un/re/installing some packages.
now, trying `dune build` I get : 
```
➜  test-irmin git:(master) dune build                                                            antonis-futureon.toc.systems
File "src/irmin-pack/IO.ml", line 207, characters 8-26:
207 |       { Raw.Header.version = Version.to_bin version; offset; generation }
              ^^^^^^^^^^^^^^^^^^
Error: Unbound module Raw.Header
File "src/irmin-pack/pack_index.ml", line 77, characters 46-67:
77 |   module Index = Index_unix.Make (Key) (Val) (Index.Cache.Unbounded)
                                                   ^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Index.Cache
File "src/irmin-pack/pack.ml", line 134, characters 45-47:
134 |       if index then Index.flush ~no_callback:() t.pack.index;
                                                   ^^
Error: The function applied to this argument has type
         ?with_fsync:bool -> unit
This argument cannot be applied with label ~no_callback
Done: 2810/2855 (jobs: 1)%       
```

not sure what's missing :(

**Comment by AntouanK** [comment]
with some help from the discord channel, I managed to build the project
https://discord.com/channels/436568060288172042/585511202759770135/770678121111224400

my initial questions remain though. on how to play around with the code. 
any help or example ( like which file to edit and how to test it ) would be greatly appreciated.

**Comment by AntouanK** [comment]
I figured out that you can run the graphql example by doing :
`dune build examples/custom_graphql.exe`
and 
`dune exec examples/custom_graphql.exe`

tried some queries/mutations, some times they work, some times I get `"Error: Internal Server Error"`
No clue why, there are no logs at all in the terminal.
Any help on how to log those?
