### ISSUE TITLE
all `set` commands lead to "deleted" files

### ISSUE THREAD

**Issue by AntouanK** [mirage/irmin#1123]
hi there.

trying out the graphql version if irmin, having a confusing issue where files are deleted.

I start it with 
`irmin graphql --root irmin_fs -s git --port 8080 --color always -a 0.0.0.0 -v;`
( inside a docker container and I mount the directory with rw permissions )

Let's say this is the set mutation I make
```
mutation {
  set(info: {message: "no message provided", author: "(writer service)"}, branch: "master", key: "/project/-proj-1605097427897", value: "{\"creator\":\"John Doe\",\"name\":\"Project Halloween\",\"id\":\"-proj-1605097427897\"}") {
    hash
  }
}
```

I'd expect in the `/project/-proj-1605097427897` to have a json string file with `{\"creator\":\"John Doe\",\"name\":\"Project Halloween\",\"id\":\"-proj-1605097427897\"}` inside.

But, instead I can see the commit with `git log`, but with `git status` it shows the file deleted and staged.

```
❯ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    project/-proj-1605097427897

❯ git show
commit c510e1fadf25e48ca4be44f12f20c9eeaac2e766 (HEAD -> master)
Author: (writer service) <irmin@openmirage.org>
Date:   Wed Nov 11 12:30:13 2020 +0000

    no message provided

diff --git a/project/-proj-1605097813331 b/project/-proj-1605097427897
new file mode 100644
index 0000000..3ea1b0e
--- /dev/null
+++ b/project/-proj-1605097427897
@@ -0,0 +1 @@
+{"creator":"John Doe","name":"Project Halloween","id":"-proj-1605097427897"}
\ No newline at end of file
(END)

❯ ls -la
total 0
drwxr-xr-x 1 antouank   0 Nov 11 13:30 .
drwxr-xr-x 1 antouank   0 Nov 11 13:27 ..
drwxr-xr-x 1 antouank 424 Nov 11 13:35 .git
```

so my question is, does irmin delete the file write after I make the "commit"??

**Comment by samoht** [comment]
Hi, thanks for your interest in Irmin and your patience!

It is possible that the irmin CLI doesn't checkout the master branch on the filesystem by default.

Can you try to run `git reset master --hard` and see if that helps? I need to check if there is an option to do this automatically (we used to have one in older versions of the CLI) but I don't have working setup right now.

**Comment by AntouanK** [comment]
yes, by doing `git reset master --hard` the files appear and I get them as "modified" in the status and not staged.
all good.

**but**, any new graphql `set` mutation will do the same to the new file.
what can I do to solve that from the CLI?

**Comment by samoht** [comment]
To be clear: it is not recommended to always checkout the files on the filesystem on any operations, as it is not possible to make that operation atomic (nor efficient). So the idea is really to do this only when you want to debug or inspect your data. 

I also suspect the "auto-checkout" feature has been broken since a long time because of [that line](https://github.com/mirage/irmin/blob/master/src/irmin-git/irmin_git.ml#L660) introduced 3 years ago when we switch to [ocaml-git 2.0](https://github.com/mirage/irmin/commit/95762cec04e1e623e4f7633966958fef5a84339b). @dinosaure does ocaml-git 3.0 supports writing checkout indexes to disk?

**Comment by AntouanK** [comment]
ok, to give you some context and then you can tell me what's the best option I have.

we want to be able to save json blobs in irmin, so that : 
- we can easily keep track of what changed when
- cheap branch so a user can try things and discard or merge with his previous state

the idea is to use the key as a namespace and the value is always a json string.
for example, a "project" will be in `/projects/_project_id/`
a "user" will be in `/user/_user_id`
etc.

we have a layer on top of irmin, that exposes queries to the user, we validate them, and if it looks ok, we set the key/value in irmin.
for example, a user wants to create a "project", we validate the project, that it doesn't exist, etc, and when it's all good, we set the key/value in irmin.

now we want persistence, so git and fs sounds like the right choice (?).
unfortunately I don't know ocaml enough to make the whole thing one ocaml service, so I made a node.js service that interacts with irmin via graphql.
( all via docker containers )

what would be your suggestion?

also, we want to test how it scales, that's my plan over the next few days, once I get 5-6 queries and types done.

**Comment by samoht** [comment]
Your current setup should be enough - all the data that you set via GraphQL are stored as Git blobs in the `.git` directory (even if there is a bug which doesn't allow to auto-checkout the current branch, as you found out). 

You can see the history of your queries with `git log` (or `tig`), dump the state via `git reset master --hard`, etc. Or you can use the equivalent Irmin API calls (or via the CLI, check `irmin --help`).

**Comment by dinosaure** [comment]
> I also suspect the "auto-checkout" feature has been broken since a long time because of that line introduced 3 years ago when we switch to ocaml-git 2.0. @dinosaure does ocaml-git 3.0 supports writing checkout indexes to disk?

We assumesd that the INDEX file is too UNIX-depedant and it is a part of `git-unix` since `git.2.0.0`. We still able to write an INDEX file but it comes with `unix` package and it is not MirageOS compatible

**Comment by samoht** [comment]
Ha yes, that makes sense -- need to modify irmin-git to somehow do this then. I have create #1126 to track this.
