### ISSUE TITLE
Installation error on Mac OS

### ISSUE THREAD

**Issue by yansh** [mirage/irmin#115]
I am trying to install irmin on Mac OS 10.10.1 

after running __opam install irmin__ I get these errors. Is it irmin or opam?

```
=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Copying ~/.opam/repo/default/packages/camlp4/camlp4.4.02.1+system/files/install to ~/.opam/system/build/camlp4.4.02.1+system/
Copying ~/.opam/repo/default/packages/camlp4/camlp4.4.02.1+system/files/check-camlp4.sh to ~/.opam/system/build/camlp4.4.02.1+system/
Building camlp4.4.02.1+system:
  sh ./check-camlp4.sh
[ERROR] The compilation of camlp4.4.02.1+system failed.
Removing camlp4.4.02.1+system.
  Nothing to do.
[WARNING] Directory /Users/yan/.opam/system/lib/camlp4 is not empty, not removing
Copying ~/.opam/repo/default/packages/conf-gmp/conf-gmp.1/files/test.c to ~/.opam/system/build/conf-gmp.1/
Building conf-gmp.1:
  sh -c cc -c $CFLAGS test.c
[ERROR] The compilation of conf-gmp.1 failed.
Removing conf-gmp.1.
  Nothing to do.
Building ctypes.0.3.4:
  make
  make install
[ERROR] The compilation of ctypes.0.3.4 failed.
Removing ctypes.0.3.4.
  ocamlfind remove ctypes


#=== ERROR while installing camlp4.4.02.1+system ==============================#
# opam-version 1.2.0
# os           darwin
# command      sh ./check-camlp4.sh
# path         /Users/yan/.opam/system/build/camlp4.4.02.1+system
# compiler     system (4.02.1)
# exit-code    1
# env-file     /Users/yan/.opam/system/build/camlp4.4.02.1+system/camlp4-13444-2dea01.env
# stdout-file  /Users/yan/.opam/system/build/camlp4.4.02.1+system/camlp4-13444-2dea01.out
# stderr-file  /Users/yan/.opam/system/build/camlp4.4.02.1+system/camlp4-13444-2dea01.err
### stdout ###
# ...[truncated]
# 4.02 by switching to a local installation via `opam switch 4.02.1`.
# 
# Here are some installation instructions for camlp4 if you obtained OCaml
# via the OPAM binary packages:
# 
# http://software.opensuse.org/download.html?project=home%3Aocaml&package=ocaml
# 
# * Debian/Ubuntu: sudo apt-get install camlp4-extra
# * RHEL/CentOS/Fedora: sudo yum install ocaml-camlp4
# 
### stderr ###
# Fatal error: the file '/usr/local/bin/camlp4orf' is not a bytecode executable file


#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version 1.2.0
# os           darwin
# command      sh -c cc -c $CFLAGS test.c
# path         /Users/yan/.opam/system/build/conf-gmp.1
# compiler     system (4.02.1)
# exit-code    1
# env-file     /Users/yan/.opam/system/build/conf-gmp.1/conf-gmp-13455-335865.env
# stdout-file  /Users/yan/.opam/system/build/conf-gmp.1/conf-gmp-13455-335865.out
# stderr-file  /Users/yan/.opam/system/build/conf-gmp.1/conf-gmp-13455-335865.err
### stderr ###
# test.c:1:10: fatal error: 'gmp.h' file not found
# #include <gmp.h>
#          ^
# 1 error generated.


#=== ERROR while installing ctypes.0.3.4 ======================================#
# opam-version 1.2.0
# os           darwin
# command      make
# path         /Users/yan/.opam/system/build/ctypes.0.3.4
# compiler     system (4.02.1)
# exit-code    2
# env-file     /Users/yan/.opam/system/build/ctypes.0.3.4/ctypes-13462-2c871f.env
# stdout-file  /Users/yan/.opam/system/build/ctypes.0.3.4/ctypes-13462-2c871f.out
# stderr-file  /Users/yan/.opam/system/build/ctypes.0.3.4/ctypes-13462-2c871f.err
### stdout ###
# ...[truncated]
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/libffi_abi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/libffi_abi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/weakRef.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/weakRef.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/ffi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/ffi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.ml
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/foreign_basis.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/foreign_basis.ml
# ocamlfind ocamlc -a   -cclib -lctypes-foreign-base_stubs -dllib -lctypes-foreign-base_stubs   -o _build/ctypes-foreign-base.cma _build/src/ctypes-foreign-base/closure_properties.cmo _build/src/ctypes-foreign-base/dl.cmo _build/src/ctypes-foreign-base/ffi_stubs.cmo _build/src/ctypes-foreign-base/libffi_abi.cmo _build/src/ctypes-foreign-base/weakRef.cmo _build/src/ctypes-foreign-base/ffi.cmo _build/src/ctypes-foreign-base/foreign_basis.cmo 
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /src -ccopt -I -ccopt /tests -o dl_stubs.o  /Users/yan/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/dl_stubs.c
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /src -ccopt -I -ccopt /tests -o ffi_call_stubs.o  /Users/yan/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c
### stderr ###
# /Users/yan/.opam/system/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c:21:10: fatal error: 'ffi.h' file not found
# #include <ffi.h>
#          ^
# 1 error generated.
# make: *** [_build/src/ctypes-foreign-base/ffi_call_stubs.o] Error 2


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following failed
 - install   camlp4.4.02.1+system
 - install   conf-gmp.1
 - install   ctypes.0.3.4
Due to the errors, the following have been cancelled
 - install   zarith.1.3
 - install   uri.1.7.2
 - install   mirage-tc.0.3.0
 - install   irmin.0.9.2
 - install   mstruct.1.3.2
 - install   lwt.2.4.7
 - install   nocrypto.0.3.0
 - install   cstruct.1.5.0
 - install   sexplib.112.06.00
 - install   bin_prot.112.06.00
 - install   ezjsonm.0.4.0
 - install   type_conv.112.01.00
```

**Comment by amirmc** [comment]
This output doesn't get as far as Irmin. Is it something else?

**Comment by amirmc** [comment]
Also, useful to wrap the output with three backticks  ...  ``` … (means the email notifications are readable)

**Comment by yansh** [comment]
Sorry, yes. noted.

**Comment by yansh** [comment]
> On Jan 21, 2015, at 10:31 AM, Amir Chaudhry <notifications@github.com> wrote:
> 
> This output doesn't get as far as Irmin. Is it something else?
> 
> 
Updated the output.

**Comment by dsheets** [comment]
You probably need libffi, gmp, and camlp4 from homebrew.

**Comment by samoht** [comment]
You need to install the external dependencies as well:
```
$ opam install installext
$ opam installext irmin
```

**Comment by yansh** [comment]
Thanks but…:)

opam install installext
[ERROR] No package named installext found.

**Comment by yansh** [comment]
> On Jan 21, 2015, at 11:16 AM, Thomas Gazagnaire <notifications@github.com> wrote:
> 
> You need to install the external dependencies as well:
> 
> $ opam install installext
Got it. It should be. 

opam install opam-installext

**Comment by yansh** [comment]
> On Jan 21, 2015, at 11:13 AM, David Sheets <notifications@github.com> wrote:
> 

> You probably need libffi, gmp, and camlp4 from homebrew.
> 
> 

Tried it. Installed all of it with brew. Same error :(

**Comment by dsheets** [comment]
Exactly the same error? That's odd...

Can you search for `ffi.h`, `gmp.h`, and `camlp4orf` on your system?

**Comment by samoht** [comment]
> This doesn't work :(

can you be more precise? `opam installext irmin` is supposed to work fine ...

**Comment by yansh** [comment]
> On Jan 21, 2015, at 11:39 AM, Thomas Gazagnaire <notifications@github.com> wrote:
> 
> This doesn't work :(
> 
> can you be more precise? opam installext irmin is supposed to work fine ...
> 
> 

Sorry, here is the message I get: 

opam installext irmin
opam: unknown command `installext'
Usage: opam COMMAND ...
Try `opam --help' for more information.

**Comment by samoht** [comment]
and did you install `opam-installext`?

**Comment by samoht** [comment]
Missing an "eval `opam config env`" maybe?

**Comment by yansh** [comment]
[NOTE] Package opam-installext is already installed (current version is 1.0.1).
> On Jan 21, 2015, at 11:41 AM, Thomas Gazagnaire <notifications@github.com> wrote:
> 
> and did you install opam-installext?
> 
> 

Yes:

opam install opam-installext 
[NOTE] Package opam-installext is already installed (current version is 1.0.1).

**Comment by yansh** [comment]
> On Jan 21, 2015, at 11:42 AM, Thomas Gazagnaire <notifications@github.com> wrote:
> 
> Missing an "eval opam config env" maybe?
> 
> 

Nope. I feel my setup is somehow wrong :(

**Comment by samoht** [comment]
And using `opam-installext irmin` ?

**Comment by avsm** [comment]
This error:

```
[ERROR] The compilation of conf-gmp.1 failed.
```

means that you don't have libgmp installed.  You can install it with

```
brew install gmp
```

Or opam has experimental support for automatically installing external dependencies as well, via:

```
opam install opam-installext
```

This installs the `opam-installext` plugin.  Then just always use `installext` to install libraries, via:

```
opam installext irmin
```

**Comment by yansh** [comment]
thanks. It still gives me the error for some reason even with gmp installed. Also it has some issue with ctypes installation.


#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version 1.2.0
# os           darwin
# command      sh -c cc -c $CFLAGS test.c
# path         /Users/yan/.opam/4.02.1/build/conf-gmp.1
# compiler     4.02.1
# exit-code    1
# env-file     /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-40879-ebe0e0.env
# stdout-file  /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-40879-ebe0e0.out
# stderr-file  /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-40879-ebe0e0.err
### stderr ###
# test.c:1:10: fatal error: 'gmp.h' file not found
# #include <gmp.h>
#          ^
# 1 error generated.


#=== ERROR while installing ctypes.0.3.4 ======================================#
# opam-version 1.2.0
# os           darwin
# command      make
# path         /Users/yan/.opam/4.02.1/build/ctypes.0.3.4
# compiler     4.02.1
# exit-code    2
# env-file     /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/ctypes-44466-e0ba4f.env
# stdout-file  /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/ctypes-44466-e0ba4f.out
# stderr-file  /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/ctypes-44466-e0ba4f.err
### stdout ###
# ...[truncated]
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/libffi_abi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/libffi_abi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/libffi_abi.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/weakRef.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/weakRef.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/weakRef.ml
# ocamlfind ocamlc -c -o _build/src/ctypes-foreign-base/ffi.cmi    -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.mli
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/ffi.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/ffi.ml
# ocamlfind ocamlc      -c -o _build/src/ctypes-foreign-base/foreign_basis.cmo -I _build/src/ctypes-foreign-base  -I _build/src/ctypes src/ctypes-foreign-base/foreign_basis.ml
# ocamlfind ocamlc -a   -cclib -lctypes-foreign-base_stubs -dllib -lctypes-foreign-base_stubs   -o _build/ctypes-foreign-base.cma _build/src/ctypes-foreign-base/closure_properties.cmo _build/src/ctypes-foreign-base/dl.cmo _build/src/ctypes-foreign-base/ffi_stubs.cmo _build/src/ctypes-foreign-base/libffi_abi.cmo _build/src/ctypes-foreign-base/weakRef.cmo _build/src/ctypes-foreign-base/ffi.cmo _build/src/ctypes-foreign-base/foreign_basis.cmo 
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /Users/yan/src -ccopt -I -ccopt /Users/yan/tests -o dl_stubs.o  /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/src/ctypes-foreign-base/dl_stubs.c
# cd _build/src/ctypes-foreign-base && ocamlfind ocamlc -c -ccopt -fPIC -ccopt -Wall -ccopt -O3 -ccopt -I -ccopt /Users/yan/src -ccopt -I -ccopt /Users/yan/tests -o ffi_call_stubs.o  /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c
### stderr ###
# /Users/yan/.opam/4.02.1/build/ctypes.0.3.4/src/ctypes-foreign-base/ffi_call_stubs.c:21:10: fatal error: 'ffi.h' file not found
# #include <ffi.h>
#          ^
# 1 error generated.
# make: *** [_build/src/ctypes-foreign-base/ffi_call_stubs.o] Error 2


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
These actions have been completed successfully
 - install   camlp4.4.02.1+2
 - install   uutf.0.9.3
 - install   type_conv.112.01.00
 - install   cppo.1.1.2
 - install   cmdliner.0.9.6
 - install   ocamlgraph.1.8.5
 - install   cstruct.1.5.0
 - install   mstruct.1.3.2
 - install   ocamlfind.1.5.5
 - install   ppx_tools.0.99.2
 - install   dolog.1.0
 - install   jsonm.0.9.1
 - install   ocplib-endian.0.8
 - install   ezjsonm.0.4.0
 - install   crunch.1.3.0
 - install   bin_prot.112.06.00
 - install   sexplib.112.06.00
 - install   re.1.2.2
 - install   lwt.2.4.7
 - install   hex.0.1.0
 - install   mirage-tc.0.3.0
 - install   uri.1.7.2
 - install   stringext.1.2.0
 - install   base-bytes.base
The following failed
 - install   conf-gmp.1
 - install   ctypes.0.3.4
Due to the errors, the following have been cancelled
 - install   zarith.1.3
 - install   irmin.0.9.2
 - install   nocrypto.0.3.0

The former state can be restored with opam switch import "/Users/yan/.opam/4.02.1/backup/state-20150021185652.export"
edgemac:~ yan$ brew install gmp
Warning: gmp-6.0.0a already installed

**Comment by yallop** [comment]
It looks like ctypes is failing to install because you don't have libffi installed.

**Comment by yansh** [comment]
Thanks. yes, I fixed it already thanks to this http://stackoverflow.com/questions/22875270/error-installing-bcrypt-with-pip-on-os-x-cant-find-ffi-h-libffi-is-installed

Now I still have trouble  with gmp, although I installed it. For some reason, it cannot find gmp.h

Copying ~/.opam/repo/default/packages/conf-gmp/conf-gmp.1/files/test.c to ~/.opam/4.02.1/build/conf-gmp.1/
Building conf-gmp.1:
  sh -c cc -c $CFLAGS test.c
[ERROR] The compilation of conf-gmp.1 failed.
Removing conf-gmp.1.
  Nothing to do.


#=== ERROR while installing conf-gmp.1 ========================================#
# opam-version 1.2.0
# os           darwin
# command      sh -c cc -c $CFLAGS test.c
# path         /Users/yan/.opam/4.02.1/build/conf-gmp.1
# compiler     4.02.1
# exit-code    1
# env-file     /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-25310-6d07ae.env
# stdout-file  /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-25310-6d07ae.out
# stderr-file  /Users/yan/.opam/4.02.1/build/conf-gmp.1/conf-gmp-25310-6d07ae.err
### stderr ###
# test.c:1:10: fatal error: 'gmp.h' file not found
# #include <gmp.h>
#          ^
# 1 error generated.

**Comment by yallop** [comment]
This looks like it might be related to ocaml/opam-repository#3000

**Comment by avsm** [comment]
I think upgrading xcode to the latest version fixes this -- or at least, it disappeared at some point

**Comment by yansh** [comment]
Haha…indeed, it worked!

All I did was:

LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include opam install irmin

Thanks @avsm @yallop

**Comment by yansh** [comment]
Irmin installed!

**Comment by yansh** [comment]
I thought I had an updated version.
