### ISSUE TITLE
CLI! CLI! CLI!

### ISSUE THREAD

**Issue by globalcitizen** [mirage/irmin#119]
It's not *git*-like without putting the command line interface first!

Seriously though, it will increase adoption for you and make it easier for people to perform comparative tests and benchmarks.

Right now this represents a needless barrier between potential new users and your codebase.

**Comment by globalcitizen** [comment]
Err, OK, so next I clicked wiki and there it was. Put it in `README.md` ;)

**Comment by samoht** [comment]
A "library database" is much more useful used as a library, as the user could define its own contents and merge functions. But yes, I should advertise the basic command-line facilities ...

**Comment by samoht** [comment]
I think this is now addressed in the README
