### ISSUE TITLE
Seq to improve the mem footprint of Tree.clear?

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1221]
https://github.com/mirage/irmin/pull/1171 recently expressed concern about the memory footprint of `Tree.clear`. 

Currently, `clear_info` starts by calling `StepMap.bindings` on all 3 maps, would it be worthwhile to call `StepMap.to_seq` instead and concatenate these sequences using `Seq.append`?

**Comment by CraigFe** [comment]
That seems like a good idea to me :-) all the better if we can write a benchmark / collect a `memtrace` that indicates the improvement.

**Comment by samoht** [comment]
Fixed by 4c90fa54f7a26f1a53cce55597fe044cd93be56a
