### ISSUE TITLE
irmin-pack-layers: rework freeze's API

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1238]
See https://github.com/mirage/irmin/pull/1213#discussion_r548049208 and https://github.com/mirage/irmin/pull/1213#discussion_r548050341.
Related to https://github.com/mirage/irmin/issues/1226

**Comment by Ngoguey42** [comment]
Partially solved by #1322, we still need to rework the `freeze_throttle` parameter

**Comment by maiste** [comment]
Closed as a new layered store is coming so it is depracted.
