### ISSUE TITLE
Add `seq` converters

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1257]
The paginated `Tree.list` functions would probably be better expressed as sequences. They will also be more efficient (especially for the inodes backend).

**Comment by samoht** [comment]
(from https://gitlab.com/tezos/tezos/-/merge_requests/2440?commit_id=4d9549b1ff7d41f488f7182dba506c7e5f7dfa9c#note_490753645)

**Comment by CraigFe** [comment]
This would require some sort of Lwt-ified `Seq.t`, such as the one proposed by: https://github.com/ocsigen/lwt/pull/836.

**Comment by metanivek** [comment]
@samoht it looks like you added a `seq` implementation in 1f7f310269a8f7a077921f6d13089e232c749aa7 -- would exposing it in the interface be sufficient for closing this issue?

**Comment by samoht** [comment]
I think the initial feature request was about adding `Tree.seq` (and not `Node.seq`). It's a bit trickier as the `Tree` functions are in the Lwt monad so complicates all the signature.

I suggest we defer this after we rewrite everything in direct style with eio.

**Comment by metanivek** [comment]
The message of the commit only mentions node constructors, but it does include a `seq` in `tree.ml` ([direct link that would've been more helpful](https://github.com/mirage/irmin/commit/1f7f310269a8f7a077921f6d13089e232c749aa7#diff-b69187f706f079406ffcf31edc21275bdee6ed99b12094a44381876e94eb203aR742) :sweat_smile:). It's just not exposed in the interface, which I thought might be enough to address this issue / the original request from Raphaël.

**Comment by samoht** [comment]
So maybe we should just need to expose `Tree.seq` in `tree_intf.ml` ?

**Comment by samoht** [comment]
Anyway, paginated lists are a step forward in that direction already, so it's clearly not a blocking feature :-)

**Comment by metanivek** [comment]
> So maybe we should just need to expose `Tree.seq` in `tree_intf.ml` ?

Yep, that was my thought. 😎
