### ISSUE TITLE
404 links in tutorial

### ISSUE THREAD

**Issue by Sir4ur0n** [mirage/irmin#1264]
Hi,

https://irmin.io/tutorial/contents chapter 4 links to:
* [Irmin.Type](https://mirage.github.io/irmin/irmin/Irmin/Type/index.html)
* [official documentation](https://mirage.github.io/irmin/irmin/Irmin/Type/index.html)

which do not exist (404). I thought you would want to know :sweat_smile:

**Comment by Ngoguey42** [comment]
Hi, thanks for bringing this up. 

Irmin.Type has moved, the documentation can be found here https://mirage.github.io/repr/repr/index.html. We haven't corrected the tutorial yet.

**Comment by CraigFe** [comment]
Now fixed; thanks! :slightly_smiling_face:
