### ISSUE TITLE
Irmin as a PouchDB/CouchDB replacement?

### ISSUE THREAD

**Issue by hoichi** [mirage/irmin#1281]
Hey guys!

Hope it's ok to put questions like these in an issue, I've found no other means of communication.

I work in a team using OCaml/ReScript, and we're considering Irmin as a solution for collaborative editing. We want (maybe to different degrees): collaborative editing, version history, and two-way replication between browsers and the server.

So my question is: how feasible it is to use Irmin in the browser today. Is it production-ready? And more specifically:
- Do you know if you can compile Irmin with ReScrit(formerly BuckleScript)? I've only seen mentions of JSOO.
- ~~Is there a ready-made backend for LocalStorage/IndexedDB, or do we have to write it ourselves?~~ Nevermind, found [talex5/irmin-indexeddb](https://github.com/talex5/irmin-indexeddb)
- What about two-way replication between the browser and the server? Will we have to write the replication layer too?

**Comment by avsm** [comment]
@hoichi thanks for the interest. I'd suggest short-circuiting a back and forth on this issue to have a quick video chat to discuss what you'd like to do, and then circle back and summarise the findings in this issue.  Browser support has long been on our roadmap, and we've had prototypes, but it's been awaiting a serious user before committing to it. And here you are :-)

If you could drop me a mail on anil@recoil.org, I'll connect to the right Irmin/Mirage developers.
