### ISSUE TITLE
Store.Tree.shallow breaks hash stability on `Contents nodes

### ISSUE THREAD

**Issue by smelc** [mirage/irmin#1284]
`Store.Tree.hash` is disturbed by the presence of trees built by `Store.Tree.shallow` on `Contents` nodes. In other words, `Store.Tree.hash t` differs from `Store.Tree.hash t'` when `t'` has some of its subtrees replaced with `Store.Tree.shallow` calls. Here's the minimal example I could come up with (versioned [here](https://gitlab.com/smelc/tezos/-/blob/a60d9ee4e5b800d397c28f42e5ef44532fa4d939/src/lib_proxy/test/test_light_lwt.ml#L42) on Tezos):

```ocaml
(* Store is an irmin-mem store *)

let test_shallow_contents _ () =
  let leaf = Store.Tree.of_concrete (`Contents (Bytes.of_string "0", ())) in
  let (empty, k) = (Store.Tree.empty, ["a"]) in
  Store.Tree.add_tree empty k leaf
  >>= fun tree ->
  let tree_hash = Store.Tree.hash tree in
  Irmin_mem.config () |> Store.Repo.v
  >>= fun repo ->
  let shallow_leaf = Store.Tree.shallow repo @@ Store.Tree.hash leaf in
  Store.Tree.add_tree empty k shallow_leaf
  >>= fun tree_with_shallow ->
  let tree_with_shallow_hash = Store.Tree.hash tree_with_shallow in
  let hash_eq = Irmin.Type.(unstage (equal Store.Hash.t)) in
  ( if hash_eq tree_hash tree_with_shallow_hash then ()
  else
    let hash_to_string = Irmin.Type.to_string Store.Hash.t in
    Printf.eprintf
      "Hash mismatch: %s <> %s"
      (hash_to_string tree_hash)
      (hash_to_string tree_with_shallow_hash) ;
    assert false ) ;
  Lwt.return_unit
  ```
  
  Executing this snippet fails as follows:
  
  ```
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        all          0   test_shallow_contents.                        │
└──────────────────────────────────────────────────────────────────────────────┘
[exception] "Assert_failure src/lib_proxy/test/test_light_lwt.ml:62:4"
            Raised at file "src/lib_proxy/test/test_light_lwt.ml", line 62, characters 4-16
            Called from file "src/alcotest-lwt/alcotest_lwt.ml", line 29, characters 47-57
            Called from file "src/core/lwt.ml", line 2133, characters 16-20
            Hash mismatch: CoWC8E5KRmgLx326RRsdKAXtoaFoWUyndd3qc6DfPwZMs472zbSp <> CoWRXCQXzCQRqbAQdiYyjvNmDRK574ZfNgvoQVnNEUsSmgwSqQrG
  ```
  
  I will gladly help fixing this/testing the fix.

**Comment by CraigFe** [comment]
Thanks for the report. Can you check whether the API change proposed in #1285 supports your use-case?

**Comment by CraigFe** [comment]
Oops – re-opened :-)

**Comment by smelc** [comment]
The API change is fine and this makes baking with the light mode work, thanks for your lightning fast support! :pray:

For the record, here's the change in Tezos: https://gitlab.com/smelc/tezos/-/commit/49659e6854ee52abd58eafc46dbac7f45ad16eb3#b2553a7e1d18556779d212de94fd13a1eef57d06

**Comment by CraigFe** [comment]
Excellent, thanks. We'll cut a release with this shortly & make it available in the Tezos `opam-repository`.
