### ISSUE TITLE
pre_hash collisions

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1304]
There currently is a systematic way to collide the `pre_hash` of objects with different types, resulting in undefined behaviours.

This document summarises this convoluted problem, when using irmin-pack.

---

### Definition of the problem
In irmin-pack, the blobs/nodes/commits are all stored in a single content addressable store, i.e. the pack file.

To interact with the store, each of the 3 types define those 3 functions:
```
pre_hash: v -> p // from in-memory value to hashable bytes
ser: v -> s      // from in-memory value to storable bytes
deser: s -> v    // from storable bytes to in-memory value
```

And all 3 types share a common hash function:
```
hash: p -> h     // from hashable bytes to hash
```

The workflow is straighforward:
- A value `v` is stored at `key`:`v |> pre_hash |> hash` / `value`:`v |> ser`. A `magic` byte is also stored alongside the value to tag the type of the object.
- A value can be fetched using its hash `h` and rebuilt from `s` using `deser`. The `magic` byte doesn't come into account during this operation.

`pre_hash` and `ser` are often the same function, but it sometimes is important for an object to have 2 distinct funtions. For example, the node type references hashes to blobs and other nodes. To save disk space, we substitute the ~30 byte long hashes with 8 byte long offsets within the pack file. We don't want that optimisation to be reflected into the hash, hence the use of a `pre_hash` function different than `ser`.

Problems arise when two `pre_hash` functions from two different types produce the same `p`.

#### The "small problem"
When two objects of different types have the same `p` and the same `s`, no wrong behaviour is to be expected at runtime. The only hickup is that the `magic` tag will not always reflect the type of the manipulated object.

#### The "huge problem"
When two objects of different types have the same `p` but not the same `s`, one of the `deser` function will crash (or silently produce wrong `v`s).

---

### Examples of the "huge problem"

This is the minimal program that will trigger the problem, by colliding a blob with the empty directory.
```ocaml
let conf = Irmin_pack.config ~readonly:false ~fresh:true "ici" in
let* repo = Store.Repo.v conf in
let tree =
  Store.Tree.of_concrete
    (`Tree [
         (* The [foo] blob is the pre_hash of [bar] *)
         ("bar", `Tree []);
         ("foo", `Contents ("\000", ()));
    ])
in
let* commit = Store.Commit.v repo ~info:(info ()) ~parents:[] tree in
(* "foo" was written to pack-file before "bar" *)
let tree = Store.Commit.tree commit in (* This tree is shallow *)
let* _ = Store.Tree.find tree [ "foo" ] in
let* _ = Store.Tree.find tree [ "bar"; "baz" ] in (* Crashes at deserialisation *)
```

Content of the root inode of the tree:
```json
{"hash":"66f1aaca1ac05f13d7b93a0bafe9976714e1763b","stable":true,"v":{"Values":[
   ["bar",{"node":    "5ba93c9db0cff93f52b521d7420e43f6eda2784f"}],
   ["foo",{"contents":"5ba93c9db0cff93f52b521d7420e43f6eda2784f"}]
]}}
```

This example can be generalised to any directory. This blob collides with the directory containing a `baz` file containing `toto`.
```ocaml
let tree =
  Store.Tree.of_concrete
    (`Tree [
         (* The [foo] blob is the pre_hash of [bar] *)
         ("bar", `Tree [("baz", `Contents ("toto", ()))]);
         ("foo", `Contents ("\001\001\003baz\011\156&%\220!\239\005\246\173M\223G\197\242\003\131z\163,", ()));
    ])
in
```

```json
{"hash":"1f2a6a1cb43c52673f4ebe6e930afc3a65c1d07a","stable":true,"v":{"Values":[
   ["bar",{"node":    "6b655d029a63a4f43a130e3c3940e8f33548bee3"}],
   ["foo",{"contents":"6b655d029a63a4f43a130e3c3940e8f33548bee3"}]
]}}
```

---

### Collisions using the default definitions

The above examples uses the default object definitions, i.e. `Irmin.Private.Contents.String`, `Irmin.Private.Commit.Make` and `Irmin.Private.Node.Make`.

- The `pre_hash` of a blob is the string itself.
   ```ocaml
   type t = string [@@deriving irmin]
   ```
   https://github.com/mirage/irmin/blob/master/src/irmin/contents.ml#L194

- The `pre_hash` of a commit is computed from this runtime type:
  ```ocaml
  type t = { node : hash; parents : hash list; info : Info.t } [@@deriving irmin]
  ```
  https://github.com/mirage/irmin/blob/master/src/irmin/commit.ml#L29

- The `pre_hash` of a stable inode is computed from this runtime type:
  ```
  let t = Type.map Type.(list entry_t) of_entries entries
  ```
  https://github.com/mirage/irmin/blob/master/src/irmin/node.ml#L139

- The `pre_hash` of an unstable inode is computed from this runtime type:
  ```ocaml
  let v_t =
    let open Irmin.Type in
    variant "Bin.v" (fun values tree -> function | Values l -> values l | Tree i -> tree i)
    |~ case1 "Values" (list (pair step_t value_t)) (fun t -> Values t)
    |~ case1 "Tree" tree_t (fun t -> Tree t)
    |> sealv
  ```
  https://github.com/mirage/irmin/blob/master/src/irmin-pack/inode.ml#L97

#### Collisions
- blob/stable: See example
- blob/unsable: Could be triggered as in example.
- blob/commit: Could be triggered as in example, but only for the "small problem" because `ser=pre_hash` for both types.
- commit/stable: Hard to say. (I'd say impossible)
- commit/unsable: Hard to say. (I'd say impossible)

---

### Collisions using Tezos' definitions

[Here](https://gitlab.com/tezos/tezos/-/blob/master/src/lib_storage/encoding/context.ml) are the custom object definitions in Tezos.

- The `pre_hash` of a blob is computed from this runtime type:
   ```ocaml
   let ty = Irmin.Type.(pair (bytes_of `Int64) unit)
   ```

- The `pre_hash` of a commit is computed from this runtime type:
   ```ocaml
   let t =
     let open Type in
     record "commit" (fun node parents info -> make ~info ~node ~parents)
     |+ field "node" K.t node
     |+ field "parents" (list ~len:`Int64 K.t) parents
     |+ field "info" info_t info
     |> sealr
   ```
   https://github.com/mirage/irmin/blob/master/src/irmin/commit.ml#L526

- The `pre_hash` of a stable inode is the computed from this runtime type:
   ```ocaml
   let entries_t = Irmin.Type.(list ~len:`Int64 entry_t)
   ```

- The `pre_hash` of a an unstable inode is the same as in previous section.

#### Prefixes of the pre_hashes
The first 8 bytes of each `pre_hash` bear witness of the difficutly to produce collisions:
- blob: the length of the blob
- commit: the length of the `node` hash.
    - `commit` is a `record`. The first field of `commit` is `node` of type `K.t`. `K.t` is a boxed string, i.e. a string prefixed by its length.  
- stable inode: the number of entries
- unsable inode: complicated, this is a variant

#### Collisions
- blob/commit: Can't collide prefix
- blob/stable: Can only collide with the empty dir
- blob/unsable: Hard to say. (I'd say impossible)
- commit/stable: Can't collide prefix
- commit/unsable: Hard to say. (I'd say impossible)

---

**Comment by samoht** [comment]
Thanks for the detailed analysis. As discussed offline, by default we must add a different prefix for every type of object. 

Would be also nice to convince ourself that "blob/unsable: Hard to say. (I'd say impossible)" is true. I came to same conclusion with a quick analysis but would nice to be 100% sure.

**Comment by Ngoguey42** [comment]
Let's add a unit test that tries to push blobs that match the pre_hash of previously pushed nodes and commits. Using `Store.save_tree` might be convenient.

**Comment by samoht** [comment]
@Ngoguey42 That's a good idea! Could you add this unit test on a branch?
