### ISSUE TITLE
`irmin init` fails

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#132]
tal@cam ~/tmp> mkdir test_irmin
    tal@cam ~/tmp> cd test_irmin
    tal@cam ~/t/test_irmin> irmin init -v
    Failed to open event channel interface: ENOENT
    Does this system have Xen userspace eventchannel support?
    On linux try:
      sudo modprobe xen-evtchn
    2015-02-04 14:56:33.246 unix         INFO : Writing /home/tal/tmp/test_irmin/.git/HEAD (/tmp/HEAD53cf5cwrite)
    Unix.Unix_error(Unix.EXDEV, "rename", "/tmp/HEAD53cf5cwrite")

Looks like it's trying to rename across filesystems (`/tmp` vs `/home`) for some reason.

**Comment by samoht** [comment]
Which version of `ocaml-git` are you using? You could set `OGITTMPDIR` to change that on the latest version of  `ocaml-git`. Not sure what's the best way to expose this to the user ...

**Comment by samoht** [comment]
See https://github.com/mirage/ocaml-git/pull/51 for a similar bug.

Maybe the solution is to use the repository root dir as temporary folder.

**Comment by talex5** [comment]
ocaml-git is the Git version. Shouldn't it create the temporary file in the same directory as the target?

**Comment by samoht** [comment]
creating in the same directory is not ideal when you are watching the filesystem you changes (Irmin watches are looking into `.git/refs` to check when references are  mutated)

**Comment by samoht** [comment]
Does changing `TMPDIR` help?

**Comment by talex5** [comment]
Maybe `.git/tmp` or something then? I'm testing from `/tmp` now, which is enough to get it running.
