### ISSUE TITLE
Store.set_exn will freeze or stackoverflow on large trees

### ISSUE THREAD

**Issue by kluvin** [mirage/irmin#1329]
Not sure if I have found an edge-case here (doubt) or I am doing something wrong, but I haven't been able to figure this out.

When setting ~30K trees, `Store.set` will stackoverflow with:

```
1 Raised by primitive operation at Stdlib__bytes.make in file "bytes.ml", line 42, characters 10-18
2 Called from Stdlib__string.make in file "string.ml" (inlined), line 41, characters 2-12
3 Called from Encore__Lavoisier.write_char in file "lib/lavoisier.ml", line 42, characters 28-47
4 Called from Encore__Lavoisier.map.(fun) in file "lib/lavoisier.ml", line 257, characters 28-43
```

Line 4 repeats and makes up the remainder of my stack trace.

-------------

Provided 20K inputs, we don't get any exception but are rather stuck in `Store.set`. Although it seems Irmin has successfully written to disk, none of the contents is actually reachable, neither before nor after terminating.

Originally I tried to do this without using transactions, though that ran into issues as well. For reference, I am running OCaml 4.11.1 with ocaml-git 3.3.1 and irmin 2.5.1 using WSL2 on Windows.

Provided is an offending program:

```ocaml
open Lwt.Infix
open Core

let ( let* ) x f = Lwt.bind x f
let ( let+ ) x f = Lwt.map f x

module Store = Irmin_unix.Git.FS.KV(Irmin.Contents.String)
module Tree = Store.Tree
let info = Irmin_unix.info

let tree_of_records records =
  Lwt_list.fold_left_s
    (fun acc (k , c) ->
      let acc = Tree.add acc k c in
      print_endline ("Set " ^ (String.concat ~sep:"/" k)); acc)
    (Tree.empty) (records) >>= Lwt.return

let main () =
  let config = Irmin_git.config ~bare:true "./" in
  let* repo = Store.Repo.v config in
  let* t = Store.master repo in

  let records =
    List.init 30000 ~f:succ
    |> List.map ~f:string_of_int
    |> List.map ~f:(fun x -> [ x ] , x) in
    let* tree = tree_of_records records in
    
    print_endline "Completing";
    Store.set_tree_exn t ~info:(info "...") [ "a" ] tree
    let () = Lwt_main.run (main ()); print_endline "Completed"
```

**Comment by CraigFe** [comment]
Looks like you've been hit by [this Encore bug](https://github.com/mirage/encore/issues/30), which looks to have been fixed by https://github.com/mirage/encore/pull/31 and released in `encore.0.8`. I suspect you'll also want the fix in https://github.com/mirage/ocaml-git/pull/485, which is currently unreleased. (CC: @dinosaure)

Can you try using `encore.0.8` and pinning to `ocaml-git` master to see if that fixes your issues?

**Comment by dinosaure** [comment]
I release of `ocaml-git` was just made here: https://github.com/ocaml/opam-repository/pull/18372. @zshipko did a test on his side about such corner case.

**Comment by kluvin** [comment]
Great! Works on my end as well 🥇
