### ISSUE TITLE
irmin: unknown option `-m'

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#134]
The tutorial starts:

    irmin init -d -m -v # Start a server (-d) in-memory (-m) and display some events (-v)

But:

    $ irmin init -d -m -v 
    irmin: unknown option `-m'.

According to `git-log`, the `-m` option was removed in f4fd2fd82f6.

**Comment by talex5** [comment]
Other tutorial issues:
* `export IRMIN=r:http://127.0.0.1:8080` didn't do anything. The tutorial appeared to work, but it was really writing directly to a different directory.
* The `-g` option doesn't exist (seems to use Git by default).
* `irmin dump` didn't work (no such command), though `irmin dot` did.

**Comment by samoht** [comment]
Thanks, the tutorial is indeed outdated: see https://github.com/mirage/irmin/issues/105

Contributions are very welcome!

**Comment by samoht** [comment]
I'll make a quick pass on it.

**Comment by samoht** [comment]
Thanks for the feedback, I've updated the page (with two new FIXME unfortunately).
