### ISSUE TITLE
Fatal error: exception Sync.Make(IO)(Store).Error

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#138]
I'm trying the first example from https://mirage.github.io/irmin/Irmin.html#examples but I get:

    $ ./test.native https://github.com/mirage/irmin.git
    2015-02-05 15:49:05.533 sync         ERROR: 0x��E is not a valid integer
    Fatal error: exception Sync.Make(IO)(Store).Error

The example at https://github.com/mirage/irmin/wiki/Using-the-Irmin-API has the same problem.

Using http instead of https gives:

    $  ./test.native http://github.com/mirage/irmin.git
    Fatal error: exception End_of_file

**Comment by samoht** [comment]
Hum indeed, the smart HTTP protocol is broken. I'll fix that.

You can still use the usual Git protocol, though:
```
ogit clone git://github.com:/mirage/irmin.git
```

**Comment by samoht** [comment]
Thanks for the report, seems that the interaction between HTTP chunk encoding + Git sideband protocols needed some care. I've also added support for redirection for `http://github.com` to work correctly.
