### ISSUE TITLE
re-enable flaky test: layer 8 Test commits and graphs.

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1383]
No log.
```
> [FAIL]        LAYERED_PACK             8   Test commits and graphs.
```

https://ci.ocamllabs.io/github/mirage/irmin/commit/692a92a409e732340f929352f2ed6dc9cf1e7042/variant/ubuntu-20.04-4.12
https://ci.ocamllabs.io/github/mirage/irmin/commit/893cd332feb359e651374c585155cd2dc1114109/variant/debian-10-4.12+flambda

**Comment by samoht** [comment]
Seen again on https://ci.ocamllabs.io/github/mirage/irmin/commit/124aa3204a8ef6799f5970ce531fde79aed131fe/variant/debian-10-4.12 (still without logs)

**Comment by icristescu** [comment]
Closing this, as it did not reappeared in a while.

**Comment by samoht** [comment]
Seen again when releasing irmin 2.9: https://github.com/ocaml/opam-repository/pull/20033#issuecomment-969440397
