### ISSUE TITLE
ocamlfind: Package `irmin.backend' not found

### ISSUE THREAD

**Issue by carlos-molina** [mirage/irmin#139]
Till last Tue I had been happily compiling irmin related code using ocamlbuilt as shown below.  

(*****************************shell begin************************)
#!/bin/bash

eval `opam config env`

ocamlbuild -r -use-ocamlfind -use-menhir -classic-display -package core,async,cohttp.async,lwt,yojson,atdgen,irmin.unix,irmin.backend,irmin.server,git.unix,irmin.unix,sexplib.syntax,comparelib.syntax,bin_prot.syntax -tag thread ser.byte cli.byte
(*****************************shell end*********************************)

But now  my shell produces error messages like:
ocamlfind: Package `irmin.unix' not found

ocamlfind: Package `irmin.backend' not found

Platform: 
a) I use a Mac Book air.
b) I used to have irmin.0.8.3. 
c) After some unexpected upgrade, I can see that now % irmin --version produces 0.9.3

QUESTIONS:
Q1: Are those packages now deprecated?
Q2: Shall I find then (where?) and install them (how: brew or opam?)?
Q3: Will they conflict with irmin 0.9.3?
Q4:  Shall I just migrate my broken Ocaml code to irmin 0.9.3?

Any advice will be appreciated. Thanks.

Carlos

**Comment by yansh** [comment]
@carlos-molina  you probably updated irmin. It is indeed 0.9.3 and it has slightly different API which me and @samoht are gradually documenting on the Wiki [1] 

As to 
```
ocamlfind: Package `irmin.backend' not found
```
I encounter this error myself, try install git package that should solve it.

Having said that, I think your code won't work with the new Irmin version, so you have two options

1. downgrade to irmin.0.8.3
2. or refactor your code to support the new API

If the part of the code that interacts with Irmin is from MoanaML, then I have updated the code to support the new API.

Hope it helps. 

[1] https://github.com/mirage/irmin/wiki/Using-the-Irmin-API

**Comment by carlos-molina** [comment]
Yansh

I have git installed: Package git is already installed (current version is 1.4.10). 

The error comes,I think, from the use of the new version of irmin. I was expecting this prob to hit me.

It's time to upgrade my code and use the version of Moana that works with the new version of irmin. 

Carlos

**Comment by samoht** [comment]
Indeed `irmin.backend` does not exits anymore in Irmin 0.9.3. Closing this now, feel free to ask if you have more specific questions about porting your app to the new API.
