### ISSUE TITLE
Add support for `last_modified` field in irmin-graphql

### ISSUE THREAD

**Issue by kluvin** [mirage/irmin#1393]
I need a way to determine if a key in a branch is ahead of the same key in a different branch, I would also like to know the distance between them. So far I have been querying irmin-graphql from a node.js server, and so I am limited to the operations exposed by graphql.

This does not seem like an immediately large task, and I should probably be able to implement this myself with some direction here. I am also wondering if it is a goal to expose more of Irmin's operation in the Graphql interface?

**Comment by samoht** [comment]
Hey! Thanks for your interest.

We are definitely interested in making the GraphQL interface more useful. Ideally, this should support the same functions as the OCaml API. And of course we'll be happy to guide you if you'd like to contribute with a patch! I am not super familiar with that part of the codebase (which was written by @andreas) but I suspect a good place to start is to add a new entry in the [branch schema](https://github.com/mirage/irmin/blob/master/src/irmin-graphql/server.ml#L341) to call `last_modified`.

**Comment by kluvin** [comment]
Thank you for building this!

I actually got that far, and in-between writing this reply I was able to guess my way there, and I am now able to compile. Although I'm not sure if I'm running the right binary because I can't use the new field or see the GraphQL docs for it. I am calling `irmin graphql` from bash after `dune build` with:

```bash
 $ which irmin
 > `/home/kluvin/.opam/irmin/bin/irmin`.
```

I should be able to figure this one out in a bit. Any next steps I should have in mind after that?

**Comment by CraigFe** [comment]
@kluvin: Dune puts development binaries into `./_build/install/default/bin/`, or you can do `dune exec irmin` (which will recompile if necessary).

I would expect that adding to the schema is all that's necessary to get this running. It would be good to have a test case for it, which could probably go in [this file](https://github.com/CraigFe/irmin/blob/keys-are-not-necessarily-hashes/test/irmin-graphql/test.ml) somewhere.

**Comment by kluvin** [comment]
What I gather from the test suite is that we build the internal representation by hand, write that, and then query it before the final comparison. I am not certain here what tree I should build and precisely what aspect to test.

There is lower-level tests for the `last_modified`, so I suppose the simplest sanity check---whatever that is---suffices?

**Comment by CraigFe** [comment]
@kluvin: Indeed, if your implementation is mostly just plumbing, the test only really needs to trigger that path once and get some sensible response back on the GraphQL side. (As you say, the correctness of `last_modified` is established elsewhere.)
