### ISSUE TITLE
 irmin: [WARNING] Got an error when we tried to load the packed-refs: "(Sys_error \"./.git/packed-refs: No such file or directory\")".

### ISSUE THREAD

**Issue by TheKnarf** [mirage/irmin#1398]
```
brew install ocaml opam
opam init
eval $(opam env)
opam install irmin-unix # Installs about 304 packages....
mkdir irmin-example
cd irmin-example
git init
echo "root: ." > irmin.yml
irmin init
```

And then I get:

```
irmin: [WARNING] Got an error when we tried to load the packed-refs: "(Sys_error \"./.git/packed-refs: No such file or directory\")".
```

There's no packed-refs since this is a new git repo, so a bit weird that it needs to spit out a warning about it?

**Comment by samoht** [comment]
Hey, thanks for your report! Which version of `git` in opam do you have installed? You can see it with `opam info git -f version`. Versions prior to 3.4.0 used to have this warning but that aims to be fixed now.

**Comment by TheKnarf** [comment]
```
$ opam info git -f version
3.3.3
```

I guess that explains it.
