### ISSUE TITLE
Website does not work.

### ISSUE THREAD

**Issue by splitcells** [mirage/irmin#1408]
Opening https://irmin.org/ results in an redirection error.

**Comment by samoht** [comment]
That's odd, it seems up right now. What error did you get?

**Comment by splitcells** [comment]
mhhh, now it works.

It was on Firefox and Windows.
It did not show an error code.
Firefox just told, that there was some kind of redirect error.

I suspect it was not caused by my local, because it was the only site with such an error.
On the other hand there is nothing that can be done.
