### ISSUE TITLE
Index out of bounds from various parts of the system

### ISSUE THREAD

**Issue by kluvin** [mirage/irmin#1419]
I have been running 2.5.1 with some specific pins that resolved my issues, I was hoping them released now resolved some everything, though something new has popped up:

**Initializing my store with `set_tree_exn`**
```
Uncaught exception:
  
  (Invalid_argument "index out of bounds")

Raised at Lwt.Miscellaneous.poll in file "src/core/lwt.ml", line 3072, characters 20-29
Called from Lwt_main.run.run_loop in file "src/unix/lwt_main.ml", line 31, characters 10-20
Called from Lwt_main.run in file "src/unix/lwt_main.ml", line 118, characters 8-13
Re-raised at Lwt_main.run in file "src/unix/lwt_main.ml", line 124, characters 4-13
Called from Dune__exe__Populate_irmin in file "populate_irmin.ml", line 44, characters 9-31
```

**Getting a value from the store**
```
(encoding (Fixed 165))): (Invalid_argument "index out of bounds")
```

This is not urgent to me, as I have a fix, but I'll mention it in case it is useful to you guys. I can provide more information if needed. Besides that, this is on a fresh 4.11.1 switch with:

* Irmin 2.6
* git 3.4
* encore 0.8
* decompress 1.4
* encore

**Comment by icristescu** [comment]
Can you check if you can reproduce this with the latest releases of irmin and git? And if so, can you please add more context, so that we can reproduce it on our side? Thanks!

**Comment by CraigFe** [comment]
Closing as we'd need a reproduction to investigate this further. Feel free to open if you get time to post one. Thanks!
