### ISSUE TITLE
Abstracting over IO

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1425]
It would be nice if we could use Irmin with other IO monads (and in direct style).

Here a tentative to do this: https://github.com/mirage/irmin/pull/1325 and https://github.com/samoht/irmin/tree/abstract-over-io

**Comment by icristescu** [comment]
We needed this for adding an in-memory backend that uses the inodes. Instead of doing this, we added a irmin-pack.mem package (https://github.com/mirage/irmin/pull/1436).
