### ISSUE TITLE
Are the modules under irmin-containers usable by 3rd party code?

### ISSUE THREAD

**Issue by anentropic** [mirage/irmin#1435]
I found https://mirage.github.io/irmin/irmin-containers/Irmin_containers/index.html and `Linked_log` seems like it would fit well what I want to do with Irmin.  Ideally I want to use it with the Git backend.

The docs page says:

> `Irmin_containers` is a collection of simple, ready-to-use mergeable data structures. Each data structure works with an arbitrary Irmin backend and is customisable in a variety of ways.

I have been struggling to find the right types to satisfy the interface. At first I assumed it's just because I'm new to OCaml and don't understand everything....

But the problem I keep running into is that, to my code, `Irmin.Content_addressable` appears as a functor rather than a module, so I cannot access the `Make` functor inside. Which I think I need in order to define a module which satisfies `Irmin.CONTENT_ADDRESSABLE_STORE_MAKER` type... which I need as one of the args to `Linked_log.Make`

It seems that `Irmin.Content_addressable.Make` is only available as an internal interface.

Now I have noticed that the [tutorial here](https://irmin.org/tutorial/contents) ignores the `Counter` and `LWW_Register` implementations in `irmin-containers` and instead builds them from scratch.

So I'm wondering if I'm trying to do something impossible with code that's not meant to be used?

Apologies if this is a stupid question, if you can give me any pointers it'd be much appreciated.

(my project is set up with dune, I have irmin 2.6.0 installed via opam)

**Comment by anentropic** [comment]
From [advice on stackoverflow](https://stackoverflow.com/questions/67550571/irmin-linked-log-possible-with-git-fs-backend?noredirect=1#comment119474435_67550571) I updated to the git head version, which brought a lot of changes (I guess next release will be 2.7...)

`Irmin.Content_addressable.Make` is visible to my code now

As an aside, it's no longer clear how to create a commit `Info` ...

the examples fail like:
```ocaml
utop # let transaction_example =
Mem_store.Repo.v config >>= Mem_store.master >>= fun t ->
let info = Irmin_unix.info "example transaction" in
Mem_store.with_tree_exn t [] ~info ~strategy:`Set (fun tree ->
    let tree = match tree with Some t -> t | None -> Mem_store.Tree.empty in
    Mem_store.Tree.remove tree ["foo"; "bar"] >>= fun tree ->
    Mem_store.Tree.add tree ["a"; "b"; "c"] "123" >>= fun tree ->
    Mem_store.Tree.add tree ["d"; "e"; "f"] "456" >>= Lwt.return_some);;
Line 4, characters 30-34:
Error: This expression has type unit -> Irmin_unix.FS.info
       but an expression was expected of type
         Mem_store.Info.f = unit -> Mem_store.info
       Type Irmin_unix.FS.info is not compatible with type Mem_store.info
```
this recipe seems to work, at least for the commit message:
```ocaml
utop # let info message = fun () ->
  Mem_store.Info.v ?author:(Some "Author") ?message:(Some message) (Int64.of_float (Unix.gettimeofday ()));;

utop # let transaction_example =
Mem_store.Repo.v config >>= Mem_store.master >>= fun t ->
Mem_store.with_tree_exn t [] ~info:(info "example transaction") ~strategy:`Set (fun tree ->
    let tree = match tree with Some t -> t | None -> Mem_store.Tree.empty in
    Mem_store.Tree.remove tree ["foo"; "bar"] >>= fun tree ->
    Mem_store.Tree.add tree ["a"; "b"; "c"] "123" >>= fun tree ->
    Mem_store.Tree.add tree ["d"; "e"; "f"] "456" >>= Lwt.return_some);;
Line 6, characters 44-49:
Error: This expression has type string but an expression was expected of type
         Mem_store.contents = (string * Irmin.Contents.json) list
```

Back to my original problem, I can now copy the example from the linked logs tests:
```ocaml
module CAS = struct
  include Irmin.Content_addressable.Make (Irmin_mem.Append_only)

  let config = Irmin_mem.config ()
end
```

But modifying it to use FS instead of mem:
```ocaml
module CAS = struct
  include Irmin.Content_addressable.Make (Irmin_fs.Append_only)

  let config = Irmin_fs.config "/tmp/irmin"
end;;
Line 2, characters 42-62:
Error: Signature mismatch:
       Modules do not match:
         functor (IO : Irmin_fs.IO) ->
           sig
             module Make :
               functor (K : Irmin__.Type.S) (V : Irmin__.Type.S) ->
                 sig
                   type 'a t = 'a Irmin_fs.Append_only(IO).Make(K)(V).t
                   type key = K.t
                   type value = V.t
                   val mem : [> Irmin.Perms.read ] t -> key -> bool Lwt.t
                   val find :
                     [> Irmin.Perms.read ] t -> key -> value option Lwt.t
                   val add :
                     [> Irmin.Perms.write ] t -> key -> value -> unit Lwt.t
                   val clear : 'a t -> unit Lwt.t
                   val close : 'a t -> unit Lwt.t
                   val batch :
                     Irmin.Perms.read t ->
                     ([ `Read | `Write ] t -> 'a Lwt.t) -> 'a Lwt.t
                   val v : Irmin.config -> Irmin.Perms.read t Lwt.t
                 end
           end
       is not included in
         Irmin__.Append_only.Maker
```

**Comment by zshipko** [comment]
This should work for setting up the content addressable store:

```ocaml
module CA = Irmin.Content_adressable.Make(Irmin_unix.FS.Append_only)
```

The issue is that `Irmin_fs.Append_only` expects an additional `IO` parameter, which is made available in `irmin-unix`

**Comment by anentropic** [comment]
@zshipko  Thanks so much!

I am confused about the significance of having a module called `irmin-unix`. Most of the useful mem/fs/git stuff seems to exist in some form under there, though there are also `irmin-git` `irmin-mem` and `irmin-fs` modules.  Is `irmin-unix` intended to be the main entry point for using this stuff?

I am also confused about the different elements of a "Backend" and what constitutes a "Backend" 🤯 

https://irmin.org/tutorial/getting-started shows examples of a `Irmin_mem.KV` store and an `Irmin_unix.Git.FS.KV`. I can see there is also a `Irmin_unix.Git.Mem.KV` store.

I was trying to use Git-specialised types everywhere I saw "FS' or "Mem", for instantiating my `Linked_log` type. But they either don't match up or e.g. `Irmin_unix.Git.FS.Append_only` doesn't exist.

Would it be correct to say that the `FS` and `Mem` instantiations already provided here https://mirage.github.io/irmin/irmin-containers/Irmin_containers/Linked_log/index.html are all that is required?

So the Git-specialisation only happens at the very outer level... i.e. I can instantiate a FS or Mem Linked_log and then use that as the `Content` type of my `Git.FS.KV` or `Git.Mem.KV` store?

**Comment by zshipko** [comment]
A backend like `irmin-mem`,  `irmin-fs`, `irmin-git` determines the layout of the store, however they typically don't provide I/O operations. `irmin-unix` provides those missing I/O functions on Unix-like platforms and `irmin-mirage` does the same for MirageOS.

In `irmin-containers` the `Backend` functor argument is a module that implements `Irmin.KV_maker`:
```ocaml
module type KV =
  S with type key = string list and type step = string and type branch = string

module type KV_maker = sig
  type metadata
  type endpoint
  type info

  module Make (C : Contents.S) :
    KV
      with type contents = C.t
       and type metadata = metadata
       and type Private.Remote.endpoint = endpoint
       and type info = info
end
```
(defined [here](https://github.com/mirage/irmin/blob/2f0c1b3d4e7a8ba7c29c8fd33636eba6c399100b/src/irmin/store_intf.ml#L917))

The irmin storage backends aren't uniform, so to create an `irmin-git` content addressable store it would look like this:

```ocaml
module Maker = Irmin_git.Content_addressable(Git_unix.Store)
module CA = Maker.Make(Irmin.Contents.String)
```

I'm not familiar with `irmin-containers`, but I don't think you can use `Linked_log.FS` with `irmin-git`, it looks like you would have to use `Linked_log.Make` and provide the `Backend` yourself.

**Comment by anentropic** [comment]
Thanks again for your help!

I feel like I'm quite close now...

I have:
```ocaml
open Lwt.Infix
open Lwt.Syntax

module Make (Store: (Irmin.KV with type contents = string)) = struct
  let info message = fun () ->
    let timestamp = Int64.of_float (Unix.gettimeofday ()) in
    Store.Info.v ?author:(Some "BYOSchema") ?message:(Some message) timestamp

  let push_schema (repo: Store.repo) (subject: string) (body: string) =
    let schema_id = Schema.get_id body in
    Store.master repo >>= fun t ->
      Store.with_tree_exn t [] ~info:(info "push new version of schema") ~strategy:`Set (
        fun tree ->
          let tree = match tree with Some t -> t | None -> Store.Tree.empty in
          Store.Tree.add tree ["schemas"; subject; Printf.sprintf "%s.json" schema_id] body
          >>= Lwt.return_some
      ) >>= fun () -> Lwt.return schema_id

  let get_schema (repo: Store.repo) (subject: string) (schema_id: string) = 
    Store.master repo >>= fun t ->
      Store.get t ["schemas"; subject; Printf.sprintf "%s.json" schema_id]
      >>= fun contents -> Lwt.return contents
end

let demo_push repo_path subject schema_body =
  let module CAS = struct
    include Irmin.Content_addressable.Make (Irmin_unix.FS.Append_only)
    let config = Irmin_git.config ~bare:true repo_path
  end in
  let module Log = Irmin_containers.Linked_log.FS (CAS) (Irmin.Contents.String) () in
  let module GitFSRegistry = Make (Log.Store) in
  let* repo = Log.Store.Repo.v (CAS.config) in
  GitFSRegistry.push_schema repo subject schema_body
```

which seems to type check apart from:
```
File "lib/byo/registry.ml", line 63, characters 35-44:
63 |   let module GitFSRegistry = Make (Log.Store) in
                                        ^^^^^^^^^
Error: Signature mismatch:
       ...
       Type declarations do not match:
         type contents = Contents.t
       is not included in
         type contents = step
       File "lib/byo/registry.ml", line 11, characters 35-57:
         Expected declaration
       File "src/irmin/store_intf.ml", line 51, characters 2-34:
         Actual declaration
```

I am puzzled because AFAICT `module Log = Irmin_containers.Linked_log.FS (CAS) (Irmin.Contents.String) ()` should mean that `Log.Store.contents` ends up as `string`

because in store_intf.ml there is:
```ocaml
module type KV_maker = sig
  type metadata
  type endpoint
  type info

  module Make (C : Contents.S) :
    KV
      with type contents = C.t
       and type metadata = metadata
       and type Private.Remote.endpoint = endpoint
       and type info = info
end
```

but if I check in utop it's still abstract (?):
```
utop # Log.Store.contents_t;;
- : Log.Store.contents Repr.ty = <abstr>
```

which I guess is the problem, but I don't understand why

**Comment by zshipko** [comment]
In your example `Log.Store.contents` is not actually `string`, it is the structure defined by `Linked_log`: [Store_item.t](https://github.com/mirage/irmin/blob/master/src/irmin-containers/linked_log.ml#L24)

It seems like the simplest solution in this situation would be to use a different store for the schema info and the log data.

**Comment by anentropic** [comment]
> In your example `Log.Store.contents` is not actually `string`, it is the structure defined by `Linked_log`: [Store_item.t](https://github.com/mirage/irmin/blob/master/src/irmin-containers/linked_log.ml#L24)

But doesn't that end up as `Irmin.Contents.String`? ... it looks like the `V` should get passed all the way through ?

I'm a bit suspicious that the compiler error says
```
       is not included in
         type contents = step
```

I don't think there's anywhere that explicitly declares `contents = step`

but `step` is also supposed to have type `string`

I feel like maybe the type inference is getting its wires crossed somewhere

**Comment by anentropic** [comment]
if I remove the `with type` from my own `Make` functor:
```ocaml
open Lwt.Infix
open Lwt.Syntax

module Make (Store: (Irmin.KV)) = struct
```
then the `Make (Log.Store)` type error goes away, instead I have:
```ocaml
26 |           Store.Tree.add tree ["schemas"; subject; Printf.sprintf "%s.json" schema_id] body
                                                                                            ^^^^
Error: This expression has type string but an expression was expected of type
         Store.contents
```

well, this just lets the under-specified type propagate a bit further through the code

Let's put it back and try something else...

another attempt, probably stupid:
```ocaml
let demo_push repo_path subject schema_body =
  let module CAS = struct
    include Irmin.Content_addressable.Make (Irmin_unix.FS.Append_only)
    let config = Irmin_git.config ~bare:true repo_path
  end in
  let module Log_ = Irmin_containers.Linked_log.FS (CAS) (Irmin.Contents.String) () in
  let module Log = struct
    include Log_
    module Store = struct
      include Log_.Store
      type contents = string
    end
  end in
  let module GitFSRegistry = Make (Log.Store) in
  let* repo = Log.Store.Repo.v (CAS.config) in
  GitFSRegistry.push_schema repo subject schema_body
```
gives:
```ocaml
81 |   let module GitFSRegistry = Make (Log.Store) in
                                        ^^^^^^^^^
Error: Signature mismatch:
       ...
       Values do not match:
         val contents_t : Contents.t Repr__Type.t
       is not included in
         val contents_t : step Repr__Type.t
       File "src/irmin/store_intf.ml", line 51, characters 2-34:
         Expected declaration
       File "src/irmin/store_intf.ml", line 51, characters 2-34:
         Actual declaration
```

agains the compiler seems to substitute `step` for `string`

specifying `contents_t` as well doesn't help:
```ocaml
  let module Log_ = Irmin_containers.Linked_log.FS (CAS) (Irmin.Contents.String) () in
  let module Log = struct
    include Log_
    module Store = struct
      include Log_.Store
      type contents = string
      type contents_t = string Repr.ty
    end
  end in
  let module GitFSRegistry = Make (Log.Store) in
```
(the same error again)

`File "src/irmin/store_intf.ml", line 51, characters 2-34:` [is](https://github.com/mirage/irmin/blob/2f0c1b3d4e7a8ba7c29c8fd33636eba6c399100b/src/irmin/store_intf.ml#L51):
```ocaml
type contents [@@deriving irmin]
```

**Comment by zshipko** [comment]
What you're trying to do in this case is not possible. Here you can see that the internal CA store is instantiated with `Store_item` as the `contents`: https://github.com/mirage/irmin/blob/master/src/irmin-containers/linked_log.ml#L42 and here is where `Linked_log` is passed to the backend: https://github.com/mirage/irmin/blob/master/src/irmin-containers/linked_log.ml#L104

When using `string` contents with `Linked_log`, the underlying content type is no longer `string` it's `Store_item.t` - the string contents are embedded in `Log_item.t`: https://github.com/mirage/irmin/blob/master/src/irmin-containers/linked_log.ml#L21

**Comment by anentropic** [comment]
Thanks so much for your continued attention, I'm very grateful!

so we have 
```
module Store = Backend.Make (L)
```

and `Backend` is `Irmin_unix.FS.KV` which is `Irmin_fs.KV (IO)` which has `module Make (C : Irmin.Contents.S)`

ok I see now the the content type of the `Log.Store` is the result of `Linked_log` functor which doesn't have a name I think

this is what I have been missing, maybe I can get something to work now 😅

**Comment by anentropic** [comment]
with some further effort I got as far as this https://gist.github.com/anentropic/508a8468f3ff73180850a7cefb936e41

which felt close to working but was it getting a bit hacky and I did not know how to progress past the problem

subsequently I gave up on irmin-containers and just started building my own Irmin content type and it has been a lot more productive (have been able to push/pull from remote git repo)
