### ISSUE TITLE
Exception "Not_found" when running the custom_merge example

### ISSUE THREAD

**Issue by yansh** [mirage/irmin#147]
When running the example, I get the following output.
```
I've just read:
-----------
0003: This is my third 
0002: This is my second 
0001: This is my first 
0008: Yes. On t!
0007: I can add stuff on t also
0003: This is my third 
0002: This is my second 
0001: This is my first 
-----------
Fatal error: exception Not_found
```

**Comment by samoht** [comment]
Cannot reproduce. Which version of Irmin are you running?

**Comment by yansh** [comment]
0.9.3 - should I update?

**Comment by samoht** [comment]
I've reverted to 0.9.3 and still cannot reproduce. Can you:
- try to remove `/tmp/irmin/test` and run the example again
- which version of `ocaml-git` do you have? If no 1.4.10 can you upgrade and try again?
- if still unsuccessful, you can try to export `DEBUG=1`, run the example again and report the error trace.

Thanks!

**Comment by yansh** [comment]
yes, removing /tmp/irmin/test fixed it. Thanks.
