### ISSUE TITLE
Tree.find and Tree.mem should distinguish between dangling hash and non-existing keys

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1475]
This kind of code is problematic:

```ocaml
let* x = Tree.find t k in
match x with
| None -> (* here we don't know if [k] is not present in the store or is any of the hashes are shallow *)
| Some x -> ...
```

We should return a proper error instead to allow consumer of the API to return a better error message to their user.

**Comment by CraigFe** [comment]
Fixed by https://github.com/mirage/irmin/pull/1477.
