### ISSUE TITLE
flaky tests in irmin-http

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1520]
Several tests in test/irmin-http/test.exe fail randomly with the `Server closed connection prematurely.` error message or with a timeout on `HTTP.GIT 27 Watch.Basic operations.`

This bug appreared during #1508

A timed out run: https://ci.ocamllabs.io/github/mirage/irmin/commit/71855450ca5a22c4c2e8ec558277f86e2f233546/variant/debian-10-4.12

**Comment by icristescu** [comment]
Can you create a branch to reproduce the bug? If this bug reappears in the CI, its not sure we can easily reproduce it locally.

**Comment by Ngoguey42** [comment]
Good idea.

On https://github.com/Ngoguey42/irmin/tree/flaky-http (42fbada0af26487298ef522c1e28c097a4f5174a):
- `dune exec -- ./test/irmin-http/test.exe test '' '18..20' --bail` always fails on my setup
- `dune exec -- ./test/irmin-http/test.exe test '' '0..26' --bail` will most likely always get you a fail
- `dune exec -- ./test/irmin-http/test.exe test 'HTTP.GIT' '27'` will timeout

**Comment by Ngoguey42** [comment]
This occurred again but with a proper error message this time
[HTTP.GIT.027.output.txt](https://github.com/mirage/irmin/files/7144955/HTTP.GIT.027.output.txt)

**Comment by Ngoguey42** [comment]
[log.txt](https://github.com/mirage/irmin/files/7176563/log.txt)

**Comment by metanivek** [comment]
`irmin-http` has been removed https://github.com/mirage/irmin/pull/1902
