### ISSUE TITLE
opam install -b -t irmin fails

### ISSUE THREAD

**Issue by dsheets** [mirage/irmin#153]
Tests fail with something like `Unix.Unix_error(Unix.EXDEV, "rename", "/tmp/79d6dacd3274be21586252282c63d1ecd52785832f57write")` about 18 times.

**Comment by dbuenzli** [comment]
@samoht This is the same error as https://github.com/samoht/assemblage/issues/154#issuecomment-72750976. It seems that you should never use `/tmp` for atomic writes.

**Comment by samoht** [comment]
Upgrading ocaml-git should help

**Comment by dsheets** [comment]
This was with 1.4.10.

**Comment by samoht** [comment]
damn ... I though I fixed that.

**Comment by samoht** [comment]
Actually it was fixed in the Git backend, not in the custom binary format on filesystem one. Should be better now.
