### ISSUE TITLE
Experimental expose statistics with Prometheus

### ISSUE THREAD

**Issue by maiste** [mirage/irmin#1574]
Currently, the benchmark exposes results to the `continuous benchmark`. It could be nice to make them available with `Prometheus`. Thanks to that, users could display results in `Grafana` or any other data visualizer.

**Comment by nicolasochem** [comment]
There is an ongoing effort for the [tezos daemon to expose native prometheus metrics[(https://gitlab.com/tezos/tezos/-/merge_requests/4052). Can you use this instead of tezos-metrics? Native metrics support is better than exposing them via RPC then translating them.

**Comment by maiste** [comment]
Hi,
Sure! We wait for [this MR](https://gitlab.com/tezos/tezos/-/merge_requests/4042) to be approved and merged in Tezos to move the development work to the native Prometheus metrics.

**Comment by maiste** [comment]
It has been done in tarides/tezos#21. Feel free to reopen.
