### ISSUE TITLE
irmin-pack: clear the branch store as well as the data file

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#1586]
Our implementations of `clear` in `irmin-pack` and `irmin-pack.layered` appear to not clear the branch store:

- https://github.com/mirage/irmin/blob/53861f98c7c6300d8956d79464f97d3505e765a7/src/irmin-pack/ext.ml#L189
- https://github.com/mirage/irmin/blob/53861f98c7c6300d8956d79464f97d3505e765a7/src/irmin-pack/layered/ext_layered.ml#L392

This looks like a bug to me.

**Comment by maiste** [comment]
As `content_t` is defined as:
```ocaml
let contents_t t : 'a Contents.t = t.contents
```
Isn't it the same?

**Comment by CraigFe** [comment]
The two definitions above are equivalent indeed, but I think they both contain the same bug: the contents, node and commit stores all share the same underlying instance due to memoisation, so it's enough to clear only one of them (as the comment in the code says), but this _isn't_ true of the branch store, which has a separate implementation / file on disk. I think both `ext.ml:clear` and `ext_layered.ml:clear` should probably be wiping the branch store too.

**Comment by CraigFe** [comment]
Closing as `clear` is currently unsupported by `irmin-pack`.
