### ISSUE TITLE
Make the index function part to the inode parameter

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1599]
Not sure exactly how to do this, but it would be helpful to play with other `index` functions. Having something like this would be nice:

```ocaml
type key
val key: step -> key
val index: key -> max:int -> depth:int -> int
```

**Comment by CraigFe** [comment]
Implemented in https://github.com/mirage/irmin/pull/1677/files, but not yet forward-ported to `main` (so leaving this open).
