### ISSUE TITLE
irmin-unix: resolver ignores the user-specified hash function

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#1636]
Backend CLIs constructed with [`Resolver.Store.create`](https://github.com/mirage/irmin/blob/34a58da868ec88c6eccaaee818d620d6452ea37e/src/irmin-unix/resolver.ml#L288-L293) (including `irmin-mem` and `irmin-fs`) ignore the user-specified hash function, when they should obviously include it in the schema used to build the store. (I'm surprised that the unused `(module H)` doesn't trigger a compiler warning.)

This should also be tested as part of our cram tests for the `irmin-unix` CLI.

**Comment by zshipko** [comment]
Nice catch! I can make a PR to fix this at some point today
