### ISSUE TITLE
Benchmarking structured keys, tracking what needs to be done

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1650]
This issue is to track various things we should do for the benchmarking of the recent structured keys work. Feel free to edit/add more items.

- [ ] Snapshot import/export add to benchmarking targets
- [ ] Some idea of the structure of the tezos context, so that we know eg how many content objects have a size greater than 128 bytes, and what paths they are under

**Comment by samoht** [comment]
It would be nice to add snapshot import/export to our benchmarking targets! (I'm not sure how to reproduce this without depending on `tezos-context`)

**Comment by icristescu** [comment]
Now tracked by https://github.com/tarides/tezos-storage-bench/issues/11
