### ISSUE TITLE
Add Node.length

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1666]
It's useful to have this exposed as the node implementations can do this more efficiently than folding over all the keys. Inodes store this directly in the object binary format, so it's a cheap.

The use-case for this is to store a list as an (index -> entry) reverse dictionary. With that scheme, to insert a new entry you need to get the size of the existing list efficiently first.

**Comment by CraigFe** [comment]
Don't we already expose a [`Backend.Node.length`](https://github.com/mirage/irmin/blob/5d8c68fdb32bdda9ee617601ef077d01c1b5e9a6/src/irmin/node_intf.ml#L82-L83)? I'm not sure what there is to do here.

**Comment by samoht** [comment]
Yea for some reasons I didn't find it when I was looking for it a couple of weeks ago :p
