### ISSUE TITLE
Flaky test: `debian-11-4.11 (failed: Disconnected: Switch turned off)`

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1696]
This occurred here https://github.com/mirage/irmin/pull/1689 without more details in the logs

**Comment by Ngoguey42** [comment]
Also occurred here: https://github.com/ocaml/opam-repository/pull/20494

![image](https://user-images.githubusercontent.com/9285880/150496293-7fb85e9d-5a2c-4b46-876c-41a0a8815bdb.png)

**Comment by mseri** [comment]
Thanks for the reporting, however those are internal infrastructural issues in the ocaml-ci (it happens when the CI is overloaded unfortunately) you can safely ignore them

**Comment by Ngoguey42** [comment]
Thanks @mseri
