### ISSUE TITLE
After I run update_path, I get Uncommitted changes

### ISSUE THREAD

**Issue by yansh** [mirage/irmin#170]
I need some help to figure this out. I've been struggling with it for a while now. I feel I am missing some fundamental understanding. Could you have a look at the code?:

https://github.com/yansh/MoanaML/blob/master/rete_storage.ml

I have an issue, when I use recursion for updating the views (At least this is my suspicion)

For some reason after running the code, some of the value appear as modified.
```
Yan: /tmp/irmin/test/rete git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   Rete/Node0/AM/tuples/0
	modified:   Rete/Node1/AM/tuples/0
	modified:   Rete/Node1/AM/tuples/1
	modified:   Rete/Node1/AM/tuples/2
	modified:   Rete/Node1/AM/vars/?y/c
	modified:   Rete/Node1/AM/vars/?y/c1
	modified:   Rete/Node2/AM/tuples/0
	modified:   Rete/Node2/AM/tuples/1
	modified:   Rete/Node2/AM/tuples/2
	modified:   Rete/Node2/AM/tuples/3
	modified:   Rete/Node2/AM/vars/?x/a
	modified:   Rete/Node2/AM/vars/?x/b
	modified:   Rete/Node2/AM/vars/?x/d
	modified:   Rete/Node2/AM/vars/?y/Red
	modified:   Rete/Node2/AM/vars/?y/c
	modified:   Rete/Node3/AM/tuples/0


```

Essentially it commits everything I want it to but then modifies some entries. I presume my use of Lwt.iter_s, plus the use recursion is causing this. 

Not sure what I can do about it...

**Comment by samoht** [comment]
How do you get the list of changes to be committed? Do the change appear correctly in `git show` and `git log`? If yes, you have hit https://github.com/mirage/ocaml-git/issues/68 which is annoying but not very critical (basically, I need to understand what `git status` is looking at exactly): it doesn't affect the data you are storing at all.

**Comment by yansh** [comment]
Thanks for looking at it.

The above is snippet is from running ```git status```

Yes, I think, it commits everything I want it to commit

```
Yan: /tmp/irmin/test/rete git log
commit 96f6659ba4fdc115735873ffe0bee1d1ee64e4ed
Author: Irmin yslaptop.ee.Princeton.EDU.[7458] <irmin@openmirage.org>
Date:   Mon Mar 23 15:33:57 2015 +0000

Rete init
```

But then some entries are modified according to ```git status```

**Comment by samoht** [comment]
The modified entries are exactly what is in the last commit, `git diff` will show you an empty diffs. It's just a "cosmetic" bug, your data are normally safely saved.

**Comment by yansh** [comment]
Git diff shows nothing :)

```
Yan: /tmp/irmin/test/rete git diff
Yan: /tmp/irmin/test/rete
```

I guess, I will work with the assumption that data is saved :)

**Comment by yansh** [comment]
Actually, I will reopen it, until the bug is resolved. I think it's best this way :)

**Comment by samoht** [comment]
The bug is already tracked in the right place ( mirage/ocaml-git#68) so closing :-)
