### ISSUE TITLE
Release 2.10

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#1703]
Dear irmin developers,

is there any chance to get a 2.10 release soon? The reason I'm asking is that (complicated dependency chain) I need a new version of git (3.7.0+), and currently released irmin versions do not support that new version (though support was merged in #1637. This is needed for mirage 3.10.8 and mirage 4 to be able to build MirageOS unikernels that use git and irmin (e.g. https://github.com/roburio/dns-primary-git/).

Thanks for your work and effort,

Hannes

**Comment by CraigFe** [comment]
Hi @hannesm.

Our plan is to release 2.10 very shortly, ideally before the end of the week. We're currently fixing a high-priority issue (https://github.com/mirage/irmin/pull/1694), but as soon as that is resolved we can cut a backport 2.10 release to unblock Mirage. Hope this helps!

**Comment by hannesm** [comment]
Thanks for your quick response.

**Comment by hannesm** [comment]
and thanks for the release in #1708
