### ISSUE TITLE
Type error with decode_bin

### ISSUE THREAD

**Issue by romildo** [mirage/irmin#1717]
When building `irmin` on NixOS I am getting some type errors:

```console
File "src/irmin/commit.ml", line 493, characters 19-37:
493 |         let n, v = decode_bin buf off in
                         ^^^^^^^^^^^^^^^^^^
Error: This expression has type string but an expression was expected of type
         'a * 'b
```
I have tried the 3 latest versions of irmin.

I have also tried with ocaml 4.8, 4.9, 4.10, 4.11, 4.12 and 4.13.

Any clues?

**Comment by Ngoguey42** [comment]
It seems your version of `repr` is incompatible, it should be `<0.6.0` to work with these versions of irmin.

**Comment by romildo** [comment]
> It seems your version of `repr` is incompatible, it should be `<0.6.0` to work with these versions of irmin.

I am updating some packages in NixOS... I will check this.
