### ISSUE TITLE
A way to query for nested View key

### ISSUE THREAD

**Issue by yansh** [mirage/irmin#173]
My data structure

```
 ----  KEY---         -Value-
Node2/AM/tuples/1 ---> tuple
Node2/AM/tuples/2 ---> tuple
Node2/AM/tuples/3 --> tuple

````
This is my code to print out the keys. 
```Ocaml
     View.list v ["Node2"; "AM"; "tuples"] >>=
            fun key_list ->
                List.iter (function |
                    [t_idx] -> 
                         print_string ("==["Node2" ^ "-AM-"^ "-tuples-"^t_idx^"]==---\n")
                  )key_list;
```

It gives me  ```Pattern matching failed```

Is it possible to use View.list this way? If not, what would be the right way to get tuples?

**Comment by samoht** [comment]
`View.list` returns the list of sub-paths, in your case:
```
[ "Node2"; "AM/tuples"; "1" ];
[ "Node2"; "AM/tuples"; "2" ];
[ "Node2"; "AM/tuples"; "3" ];
```

So I guess you want to get the last element of the list instead of assuming these contains only one element. To do that you can use `snd (Irmin.Path.String_list.decons k)`.

Also, this is related to https://github.com/mirage/irmin/issues/141 as the API types are very intuitive.

**Comment by yansh** [comment]
Hmm..I am hit all the right ~~notes~~ bugs today :) Thanks for the help.

I just want to retrieve tuples :) The printout is just to test that I can reach it.

I presume that is the reason my following code doesn't work:

```ocaml
Lwt_list.fold_left_s
                  ( fun acc [idx] ->
                        View.read_exn v [key; "AM"; "tuples"; idx]
                        >>= fun tuple ->
```

I will try   refactor the code to use ``Irmin.Path.String_list.decons k```

**Comment by samoht** [comment]
Closing as the API issue is tracked by #141 and the pattern-matching exception is correct in this case (as you don't pattern match on all the possible cases of the list).

**Comment by yansh** [comment]
@samoht thanks for the help. These are useful to add to documentation. I put some words on it.
