### ISSUE TITLE
lcas calculation very slow

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#174]
I'm still finding the lcas calculation very slow in some cases. Here's a test where I create a simple linear history and then merge the first commit with the last:

    open Lwt

    module S = Irmin.Basic(Irmin_mem.Make)(Irmin.Contents.String)

    let task s = Irmin.Task.create ~date:0L ~owner:"User" s
    let config = Irmin_mem.config ()

    let chain s n =
      let s = s "chain" in
      let rec aux = function
        | 0 -> return ()
        | n ->
            S.update s ["count"] (string_of_int n) >>= fun () ->
            aux (n - 1) in
      aux n

    let main =
      Gc.(set {(get ()) with stack_limit = 1024});
      let test n =
        Printf.printf "Test for %d\n%!" n;
        S.create config task >>= fun master ->
        S.update (master "init") ["version"] "1" >>= fun () ->
        S.head_exn (master "head") >>= fun first ->
        chain master n >>= fun () ->
        S.merge_head (master "merge") first >>= function
        | `Conflict x -> failwith x
        | `Ok () ->
        return () in
      [1; 10; 20; 30; 40; 50; 60; 70] |> List.iter (fun n -> Lwt_main.run (test n))

Here are the results, showing the time for the current lcas algorithm, and an imperative version I hacked up for comparison:

![lcas_time](https://cloud.githubusercontent.com/assets/554131/6828783/72ef201c-d307-11e4-8257-d03e897b51d0.png)

https://github.com/talex5/irmin/commits/lcas_fast

I ran all the Irmin unit tests using both versions and they mostly agreed, except in `Concurrent merges`. Looking at the repository with gitk, I think my version may be correct, but I'd like a second opinion.

**Comment by talex5** [comment]
Update: the disagreement is when `n=1` is used to limit the number of results, and they just happen to find different ones first.

**Comment by samoht** [comment]
Thank you very much for the report and for your code. I've taken some of you ideas and cleaned up the bfs search in the graph. My new patches are a bit more precise regarding `max_depth` and have similar performance to yours (a bit better in some cases, but that's very marginal). I'm waiting for Travis and I'll merge it!

**Comment by samoht** [comment]
I also removed the `n=1` in the tests, I'm not sure why it was here. And I've added more checks to be sure the right depth is used by the lca computation...

**Comment by talex5** [comment]
Cool - looks good! I'm currently testing it.

With the speed problem fixed, it might be worth changing the default `max_depth=256` to `max_depth=max_int`. Usually, you want to keep searching until you find the common ancestor. The only place I can see this being bad is when merging an entirely separate branch... but if you're not sure then it's probably best to check the entire history by default.

**Comment by samoht** [comment]
> With the speed problem fixed, it might be worth changing the default max_depth=256 to max_depth=max_int

That's indeed make sense to modify the default (although Git still limits it to 256). Done in https://github.com/samoht/irmin/commit/2d27ad734edc6d1391650306b31db23c65f514bb
