### ISSUE TITLE
irmin-trace: drop usage of Stdlib.Stream

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#1752]
This package is deprecated in OCaml 4.14 and due to be removed in OCaml 5.0, so we should avoid using it here. This is currently causing our 4.14 CI to fail:

```
File "bench/irmin-pack/tree.ml", line 82, characters 14-25:
82 |         match Stream.next json with
                   ^^^^^^^^^^^
Error (alert deprecated): module Stdlib.Stream
Use the camlp-streams library instead.
File "bench/irmin-pack/tree.ml", line 83, characters 20-34:
83 |         | exception Stream.Failure ->
                         ^^^^^^^^^^^^^^
Error (alert deprecated): module Stdlib.Stream
Use the camlp-streams library instead.
        test alias test/irmin-containers/runtest
```

**Comment by Ngoguey42** [comment]
I don't see any use of `Stream` in that file 🤔 

https://github.com/mirage/irmin/blob/main/bench/irmin-pack/tree.ml#L82

**Comment by CraigFe** [comment]
I was probably looking at a PR into 2.10 without realising it: https://github.com/mirage/irmin/blob/2.10/bench/irmin-pack/tree.ml#L82.

Closing; sorry for the noise.
