### ISSUE TITLE
Problematic dependencies to target jsoo

### ISSUE THREAD

**Issue by hhugo** [mirage/irmin#1772]
Trying to compile part of the tezos codebase to JS, I'm facing the following problematic dependencies:
-  tezos-protocol-environment -> tezos-context.memory -> irmin_pack.mem -> irmin_pack -> unix / lwt_unix
-  tezos-protocol-environment -> tezos-context.memory -> tezos-context.{helpers, encoding}  -> irmin_pack -> unix / lwt_unix

I wonder what can be done to remove theses problematic dependencies ?

**Comment by tomjridge** [comment]
Hi. Others are probably more knowledgeable but... irmin-pack currently uses the filesystem quite extensively. So I guess you can either try to support the filesystem in JS, or alternatively substitute some other implementations which don't use the filesystem. What are you trying to achieve? Do you want the JS to run in browser, or via node.js or similar?

**Comment by samoht** [comment]
@tomjridge irmin-pack.mem doesn't use the filesystem at all :-) 

We could probably easily extract the unix-specific bits from `irmin-pack` into `irmin-pack.unix`.

**Comment by CraigFe** [comment]
Indeed, it should be relatively simple to pull out an `Irmin_pack_unix` / `irmin-pack.unix` component; we just haven't had a reason to do so until now.

I would probably start by pulling out the `Unix` IO implementation in [`IO.ml`](https://github.com/mirage/irmin/blob/1d83f084815d11140f9b77fcb4732851bb6dec18/src/irmin-pack/IO.ml#L24), along with anything that's depending on it: `pack_dict.ml`, `pack_index.ml` and the bits of `pack_store.ml` that reference "persistent" stores will probably all need moved into a `unix/` subcomponent, along with the top-level functors in `ext.ml` and `irmin_pack.ml` that depend on them. The result should be roughly analogous to what we have now with `irmin-pack.mem`, but with more subcomponents involved in the functor instantiation.

@hhugo: we'd happily accept a PR to do this, and I can provide any guidance you need.
