### ISSUE TITLE
Include example js_of_ocaml usage in wiki

### ISSUE THREAD

**Issue by sgrove** [mirage/irmin#179]
My primary use requires using the same data in the browser and cli (both using Irmin), so it'd be great to have an example up-and-running project & documentation.

**Comment by sgrove** [comment]
Sorry to give a bump, but I'm coming back to this now, and hoping to be able to sync between a js_of_ocaml Irmin client running in the browser, and an Irmin instance running server-side. I know Cuekeeper is an example, but hoping for a fairly simple, minimal set of examples.

**Comment by avsm** [comment]
I was talking to @yomimono about this yesterday -- she is also looking into extracting some of the CueKeeper logic into a simpler set of examples.

**Comment by samoht** [comment]
Closing as the README now points to https://github.com/talex5/irmin-js
