### ISSUE TITLE
Remove clear from backends 

### ISSUE THREAD

**Issue by icristescu** [mirage/irmin#1793]
The `clear` functions (https://github.com/mirage/irmin/blob/main/src/irmin/store_properties_intf.ml#L46 ) were added for the layered store but the new implementation does not need it, so we can remove it.

**Comment by metanivek** [comment]
Is the related to (or possibly fixed by) #1794? It's not... well... clear to me. :see_no_evil:

**Comment by icristescu** [comment]
indeed, thanks
