### ISSUE TITLE
layers/GC: index retains entries for commits that have been GC'ed; this can lead to "read from gap" exceptions when querying via RPC

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1823]
The current layers/GC implementation focuses on the `store.pack` file; the index is not changed. The index typically stores entries `commit_id -> (offset,length,_)`, mapping a commit id to an `(offset,length)` in the `store.pack` file. After a GC (say, for the most recent commit), then any older commits will have been garbage collected. However, the index still maintains entries for each of these older commits.

Then you can trigger an error by asking the node to access one of these older commits:

```
tezos-client rpc get /chains/main/blocks/42/context/contracts/KT1VqarPDicMFn1ejmQqqshUkUXTCTXwmkCN/storage 
```
(Aside: the "savepoint" -- which I believe is now also the point at which the last layers-GC occurred -- can be found using `tezos-client rpc get /chains/main/levels/savepoint` .)

A possible solution is to link the index to the layers implementation, so that `find`ing in the index always returns `None` instead of `Some(offset,length,_)` if the relevant commit has an offset that is before the most recent GC position.

**Comment by Ngoguey42** [comment]
This will be solved by treating keys pointing to gap as non-member of the store
