### ISSUE TITLE
snapshot import: "Persisting an empty node is forbidden by the configuration of the irmin-pack store"

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1830]
Victor hit the following error when attempting to import a snapshot:
```
tezos-node: Error:
              Persisting an empty node is forbidden by the configuration of the irmin-pack store
```
This was using the current layers branch: https://github.com/tomjridge/irmin/tree/2022-04-22_layers_rebased_on_3.2.0

Also with Victor's integration into Tezos: https://gitlab.com/nomadic-labs/tezos/-/tree/vicall@tomjridge@layered_store

(This issue labelled with "feature/layered-store", but not clear that this is a problem with layers...)

**Comment by Ngoguey42** [comment]
Tezos neve exports the empty directory. That's very unexpected

**Comment by tomjridge** [comment]
Another data point: I downloaded just now `mainnet-2335199.rolling` from https://mainnet.xtz-shots.io/

I then ran: ` $ ./tezos-node  snapshot import ~/Downloads/mainnet-2335199.rolling `

The output was: 
```
May  4 11:04:33.040 - node.snapshots: importing snasphot in on-disk mode. Mind using the --in-memory flag to allow
May  4 11:04:33.040 - node.snapshots:   a faster import which uses a higher quantity of ram
May  4 11:04:33.040 - node.snapshots: importing data from snapshot
May  4 11:04:33.040 - node.snapshots:   /home/tom/Downloads/mainnet-2335199.rolling: chain TEZOS_MAINNET, block hash BKp1kQVFLjARJ8f4diHf2zhgtPDWNahYrrHdBxo3G7jyXLRFwpy at level 2335199, timestamp 2022-05-04T04:09:59-00:00 in rolling (snapshot version 3)
May  4 11:04:33.040 - node.snapshots: you may consider using the --block <block_hash> argument to ensure that the
May  4 11:04:33.040 - node.snapshots:   block imported is the one you expected
May  4 11:04:33.040 - node.snapshots: retrieving and validating data. This can take a while, please bear with us
Writing context: 0K/20331K (0%) elements, 976KiB readMay  4 11:04:33.061 - node.main: cleaning up directory "/home/tom/.tezos-node" after failure.
tezos-node: Error:
              Persisting an empty node is forbidden by the configuration of the irmin-pack store            
```

This was using the current layers branch https://github.com/tomjridge/irmin/tree/2022-04-22_layers_rebased_on_3.2.0 (at 58e34e675d), with Victor's  https://gitlab.com/nomadic-labs/tezos/-/tree/vicall@tomjridge@layered_store (4c3ca3c7d2 "[skip ci]").

**Comment by tomjridge** [comment]
Using tezos gitlab master (at 25d0584d06) and irmin (almost master, at d5e2353b62) snapshot import appears to work fine.

**Comment by tomjridge** [comment]
For layers, `pack_store.ml` has the following piece of code (or similar)

```
    let v ?fresh ?readonly ?lru_size ~index ~indexing_strategy path =
   (* FIXME force minimal indexing for layers testing *)      
      let indexing_strategy = 
        ignore(indexing_strategy);
        Irmin_pack.Indexing_strategy.minimal
      in
```

This is accompanied by an assert when appending in the pack_store:

```
          if should_index then (
            (* for layers testing, we are using minimal indexing, so only indexing commit_v2 *)
            assert(kind = Pack_value.Kind.Commit_v2);
            Index.add ~overcommit t.pack.index hash (off, len, kind))
```

If we disable both, then snapshot import proceeds as it does on main.

So, we can assume that snapshot import needs a non-minimal index.

(There are surely other problems: for example, I would expect the snapshot import code to detect when an object that should be indexed isn't, and to fail in that case; but that isn't what is happening here it seems)

**Comment by tomjridge** [comment]
**How to successfully import a snapshot and continue bootstrapping with layers/GC**

(This is mostly a note for NL people who may be interested in testing layers...)

In order to facilitate layers testing, it is possible to circumvent the current snapshot/layers problems in the following way:

1. Obtain a v4 snapshot: the snapshots on the web are v3; import and export on a tezos-node v.13.0 will produce a v4 snapshot
2. Use the v4 snapshot to obtain a data-dir with minimal index: Using a tezos-node v.13.0, import the v4 snapshot using an "--in-memory" index, into an empty data-dir
3. Convert this data-dir to layers format: Using this data-dir, convert the store.pack using convert_store_dot_pack.exe bin-layers utiility; you should end up with the original large store.pack replaced with a small store.pack and a layers.0 subdirectory

Once this is completed, you have a layers data-dir, based on a snapshot, which you can then use with a tezos-node built using the tezos/layers combination. On my machine, with a recent mainnet snapshot, the tezos-node proceeds from the last block in the snapshot, to bootstrap the rest of mainnet.

**Comment by tomjridge** [comment]
The fix for this issue is to allow non-minimal indexing (so that snapshot import can execute properly), but to ensure that snapshot import uses a temporary index rather than the main Tezos context index (which should remain using minimal indexing).

**Comment by samoht** [comment]
This should be fixed by the new snapshot implementation.
