### ISSUE TITLE
layers/GC: "read from gap" / "Kind.of_magic: unexpected magic char '\000'"

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1831]
Victor reports the following: 

```
+7550103145us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: check_worker_status called (Some case)
+7550103250us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: check_worker_status: worker terminated
+7550103267us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: checking existence of next sparse+suffix
+7550308372us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: copy additional data from current suffix to next
+7550308657us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: switching to next sparse+suffix
+7550382299us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: switched to new sparse+suffix
+7550382426us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: removing old files
+7554134620us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/layers/pre_io.ml: RO instance for /home/vicall/.tezos-node_layered/context\
/store.pack reloading for generation 1235
+7554819822us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/layers/pre_io.ml: RO instance for /home/vicall/.tezos-node_layered/context\
/store.pack reloaded; updating ro_fields
+7554819912us index [INFO] [context] sync
May  3 11:19:24.971 - validator.block: block BKucWhjSBRrvsHCd5qVJ5ntXeXz1CjErvnj5fcCrjQk8FSodAdq successfully validated
May  3 11:19:24.971 - validator.block: Request pushed on 2022-05-03T09:19:09.709-00:00, treated in 28.883us, completed in 15.262s
May  3 11:19:25.083 - validator.chain: Update current head to BKucWhjSBRrvsHCd5qVJ5ntXeXz1CjErvnj5fcCrjQk8FSodAdq (level 2302735, timestamp \
2022-04-22T14:26:29-00:00, fitness 02::0023230f::::ffffffff::00000000), same branch
May  3 11:19:25.083 - validator.chain: Request pushed on 2022-05-03T09:19:24.971-00:00, treated in 642us, completed in 111ms
+7554066625us irmin.layers.io [ERROR] vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap
vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap, voff=3146378311, len=42
Error:
  Kind.of_magic: unexpected magic char '\000'
```

This was whilst bootstrapping from mainnet, with a gap_tolerance of 1000. The bootstrap started from a snapshot "2243806" (reported by Victor; presumably this is the block level?). The "read from gap" error means that the node is attempting to read from part of the file that has been GC'ed. 

These sorts of errors are quite difficult to track down. The obvious candidates are:

1. Somehow the "reachable/live data in the file" was not calculated correctly - a bit of the file that was live was missed.
2. The "reachable data in the file" was calculated correctly, but the node wrongly tried to access a part of the file it shouldn't (e.g. it retained some reference to a part of the file in a cache, and later tried to use this reference).
3. Some other error, e.g. the processing of the "reachable" data to produce the "extent" data was buggy.

**Comment by Ngoguey42** [comment]
`+7554066625us irmin.layers.io [ERROR] vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap
vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap, voff=3146378311, len=42` 

and 

`Error: Kind.of_magic: unexpected magic char '\000'` look like 2 distinct errors. Do you know why both show up?

**Comment by tomjridge** [comment]
At the moment, the "read from gap" is logged as an error, but the code fills the buffer with '0' characters. So the exception actually gets thrown when the code attempts to interpret the '0' characters as a Pack_value.Kind t. Probably better just to make the "read from gap" case throw an exception instead.

**Comment by tomjridge** [comment]
Just altered this in the current branch; "read from gap" now results in a thrown exception.

**Comment by tomjridge** [comment]
Something I didn't notice when first reading the error: the log reports the error as:

```+7554066625us irmin.layers.io [ERROR] vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap```

Note the time stamp of "+7554066625us". Note that the previous log line was 

```
+7554819912us index [INFO] [context] sync
```

So these lines are out of order, if we believe the timestamps. If we believe the timestamps, the error occurs between the following two events:

```
+7550382426us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/unix/pack_store_IO.ml: removing old files
+7554134620us irmin.layers.io [INFO] vendors/irmin/src/irmin-pack/layers/pre_io.ml: RO instance for /home/vicall/.tezos-node_layered/context/store.pack reloading for generation 1235
```

Since the RO instance always reloads (if it can) before serving a call, the error must originate from the RW instance, immediately after switching to the next sparse+suffix (again, all this relies on the correctness of the timestamps).

**Comment by tomjridge** [comment]
I was able to reproduce this error in the following way:

- importing a snapshot seems currently not possible because of https://github.com/mirage/irmin/issues/1830
- instead, we can download a mainnet rolling tarball from https://mainnet.xtz-shots.io/
- then we need to convert the files to layers format (needs documentation - ask me if you need to do this)
- then we can run a rolling node
- soon after the first GC, we get a similar "read from gap" error

**Comment by tomjridge** [comment]
After further investigations:
- the "read from gap" error is at some position/offset 98765 (say); this position is indeed GC'ed by layers
- this position corresponds to a non-commit object; there is an entry for this object (with the position 98765) in the index
- at some point after the GC, index.find is called with the hash of this non-commit object; it finds the hash in the index, with the corresponding position 98765, returns that; the next step is an attempt to read from that offset, resulting in the error

So, it looks like the problem is that the index contains entries for non-commit objects, and these cause problems.

If we patch the index to only return results for commit objects, and to return "None" for everything else, we have a different problem:
- When GC is called, during Repo.iter, we get `Fatal error: exception Irmin_pack_unix__Pack_store.Corrupted_store("Unexpected object CoW1MP7bzPiEUZp1J7vng94pvFYmTUwdtmXKLPJMGz1M3esUqPkt missing from index")`
- This object is a non-commit object that was expected to be in the index
- After examining the code, we see that Irmin is working with a key of the form `Indexed hash`; such keys MUST be present in the index for irmin to work; in this case, our patch invalidates this invariant, and we have an exception raised

So, at this point we have: 
- Working from a snapshot, or imported tarball, seems to give rise to keys of the form `Indexed hash` for objects that are not commits
- After GC runs, these objects can be invalid because GC has removed the file regions they point to

For the imported tarball:
- It is sort-of expected that a tarball produced from a "non-minimal" indexing strategy, will not be compatible with the minimal indexing strategy that we need for layers
- It is not obvious how to fixup the imported tarball so that it can be used with layers

For the snapshot:
- Importing a snapshot in minimal-indexing mode should presumably mean that the index ONLY contains entries for commit objects. Thus, it is unclear why Victor hit this error when importing a snapshot. The suspicion is that snapshot import somehow introduces entries into index for non-commit objects. 

To progress this issue:
- We need to fixup snapshot import
- Then we need to see if we can reproduce this "read from gap" error after GC
- Then we need to confirm that the index contains entries for non-commit objects

After this, we somehow need to reconcile the way that snapshot import is working, with the requirement that index only contain entries for commit objects.

**Comment by tomjridge** [comment]
Using a mainnet v4 in-mem snapshot import into a clean data-dir, and then bootstrapping, with GC every 100 commits, this error was no longer observed (whereas previously it happened every time, almost immediately after GC switched to the new sparse and suffix).

**Comment by samoht** [comment]
Let's close this - the snapshot import code should be ok. We can re-open a new issue in case there are more issues with snapshots.
