### ISSUE TITLE
snapshot+layers/GC: Slow snapshot v4 import with "--in-memory" flag

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1840]
Using Tezos branch nomadic-labs/vicall@tomjridge@layered_store with 2022-04-22_layers_rebased_on_3.2.0 we can attempt to import a v4 snapshot into an empty data-dir:

```
$ ./tezos-node snapshot import ../mainnet-2335199.rolling.with_version_4_maybe --in-memory --data-dir ./dd3
```

This runs very slowly (too slow to be usable). 

Some figures: on the tezos main branch, this operation takes about 5 to 10s per percent imported; overall time < 10min; as above, each percent takes multiple minutes.

This seems different to the other snapshot issues: whilst snapshot import usually needs an index (by default, snapshot import uses the tezos context index, which then causes problems with layers), by using "--in-memory" we should preserve that the tezos context index is minimal, and we should avoid the problem that layers wants all indexes to be minimal. But still, there seems to be some bad interaction with the layers code.

**Comment by tomjridge** [comment]
Fixed by https://github.com/tomjridge/irmin/commit/f92b3830567af074f59343fce7f600d02f3bee82

Keeping issue open as a reminder to clarify the semantics of flush.

**Comment by Ngoguey42** [comment]
@tomjridge This is fixed right?

**Comment by tomjridge** [comment]
Yes. As I understand it, the semantics of flush is "just flush, don't fsync", so the removal of the fsync is the right fix.
