### ISSUE TITLE
layers/GC: consider using buffered writes to the suffix file (eg ocaml out_channel, or our own version)

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1841]
Currently the layers code handles `append` by issuing a pwrite. It may well be that using a buffered output (eg ocaml's out_channel, or our own version) would be much faster, at least in certain circumstances.

This issue arose because layers/GC snapshot import is still a bit slower than main branch snapshot import, and the likely cause is that layers issues direct syscalls whereas it could instead use buffered output.

**Comment by Ngoguey42** [comment]
Buffer writes are included in the gc branch, from the apprend only module
