### ISSUE TITLE
layers/GC: possible problem after mainnet bootstrap

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1844]
This issue is for a problem Victor reported earlier today. He has been bootstrapping a node from a mainnet snapshot over the last 24h period. Although apparently successful, there was a message in the logs that was worrying:

```
May 13 00:08:43.705 - validator.chain: Update current head to BKjRWH2H9jKvVacKbz3dc7Pf1e4Ms4HGF6nGaTmjPaxmmKKx46M (level 2359798, timestamp 2022-05-12T23:00:14-00:00, fitness 02::002401f6::::ffffffff::00000000), same branch
May 13 00:08:43.705 - validator.chain: Request pushed on 2022-05-13T00:08:43.698-00:00, treated in 3.840ms, completed in 2.319ms
Fatal error: exception (Failure
  "vendors/irmin/src/irmin-pack/layers/sparse_file.ml: attempt to read from gap; voff=6747967471, len=42")
May 13 00:08:44.650 - validator.block: block BLErkJV73sX5oWgxvS4RDTmQ9NW8bHDn17p5jXaJtWCcXmu9dZ2 successfully validated
May 13 00:08:44.650 - validator.block: Request pushed on 2022-05-13T00:08:43.706-00:00, treated in 4.910us, completed in 943ms
May 13 00:08:44.656 - validator.chain: Update current head to BLErkJV73sX5oWgxvS4RDTmQ9NW8bHDn17p5jXaJtWCcXmu9dZ2 (level 2359799, timestamp 2022-05-12T23:00:44-00:00, fitness 02::002401f7::::ffffffff::00000000), same branch
May 13 00:08:44.656 - validator.chain: Request pushed on 2022-05-13T00:08:44.649-00:00, treated in 110us, completed in 6.574ms
Error:
  "Assert_failure vendors/irmin/src/irmin-pack/unix/ext.ml:437:24"

May 13 00:08:44.750 - validator.block: validation of block BMdLR5QcDzdmBmEgxtrsSakUega71ukEFGdpGxUtNZV1vLFAEum failed
May 13 00:08:44.750 - validator.block: Request pushed on 2022-05-13T00:08:44.651-00:00, treated in 413us, completed in 97.816ms ,
May 13 00:08:44.750 - validator.block: "Assert_failure vendors/irmin/src/irmin-pack/unix/ext.ml:437:24"
May 13 00:08:44.752 - node.validator.bootstrap_pipeline: unexpected error while fetching headers:
May 13 00:08:44.752 - node.validator.bootstrap_pipeline:   "Assert_failure vendors/irmin/src/irmin-pack/unix/ext.ml:437:24"
May 13 00:08:44.752 - validator.peer: New branch BMdLR5QcDzdmBmEgxtrsSakUega71ukEFGdpGxUtNZV1vLFAEum, locator length 2494603
May 13 00:08:44.752 - validator.peer:  Request pushed on 2022-05-12T23:01:22.946-00:00, treated in 463us, completed in 1h7min ,
May 13 00:08:44.752 - validator.peer: "Assert_failure vendors/irmin/src/irmin-pack/unix/ext.ml:437:24"
May 13 00:08:44.752 - validator.peer: Worker crashed [node_peer_validator]:
May 13 00:08:44.752 - validator.peer: "Assert_failure vendors/irmin/src/irmin-pack/unix/ext.ml:437:24"
Error:
  Worker terminated unsuccessfully with 1  

May 13 00:08:45.533 - validator.block: validation of block BMdLR5QcDzdmBmEgxtrsSakUega71ukEFGdpGxUtNZV1vLFAEum failed
May 13 00:08:45.533 - validator.block: Request pushed on 2022-05-13T00:08:44.657-00:00, treated in 92.757ms, completed in 783ms ,
```

The first error is the notorious "read from gap" error. The subsequent assert failures are because the worker terminated unsuccessfully.

Although not 100% clear from these messages, I believe the "read from gap" error is actually occurring in the worker, which then terminates unsuccessfully (which is why the assert failures occur). The error would then be due to the GC using Repo.iter for a recent commit, which then touched old data that was not detected as live for the previous GC commit. This breaks one of the layers/GC invariants of course. To my knowledge, this can only happen if there is an entry in the index that points to the GC'ed offset, but this shouldn't be the case in minimal indexing mode.

The node apparently completed bootstrapping at 1:10 in the morning, so this failure occurs while the node is in "normal" mode (ie not bootstrapping, but listening for new blocks). The error occurs in the worker, but seems confined to the worker: the rest of the node continues working fine.

I'm attaching an image of the grafana/prometheus output. Note that the GC around 1:10am reduces the storage significantly compared to the previous GCs. I don't know if this is relevant or not. It seems strange because it coincides with the end of bootstrapping for the node.

![2022-05-13_Tezos-branch-master-Grafana](https://user-images.githubusercontent.com/1354071/168272226-5d0445eb-f6ef-4124-8f14-e3ff5d1e3050.png)

**Comment by tomjridge** [comment]
Some more data points:

- The index for the node above contained only commits. Therefore: it is not the case that there was an entry in the index that pointed to the gap.

- I ran a bootstrap from a snapshot import at level 2335199, with GC every 100 commits (which I hoped would be more likely to exhibit the issue). Everything seemed to work fine and the node synced with mainnet (after some time).

**Comment by samoht** [comment]
Could that be that someone is using the RPC mechanism to access old data?

**Comment by tomjridge** [comment]
Yeah, that was one possibility. But Victor was running with restricted RPC address. So I don't think it can be that. Also, the error seems to originate while a GC is performing Repo.iter: the Repo.iter touches old data that was GC'ed previously. Before, this was always because the index kept a reference to the position, but that is not the case here. 

Initially I thought it was due to storage running out and mmap failing in a strange way (ie not raising an exception, but allowing GC to continue with an incorrect idea of what regions were live). But this doesn't seem to be the case (there was at least 30GB free at all times). 

So here are my main two lines of enquiry:

- somehow the calculation of the reachable regions is buggy (but in a way that has never been detected before, and doesn't show when GC'ing every 100 commits)
- somehow a cache carries over a reference to a position that has been GC'ed, and this position gets reused 

I am leaning more towards the second possibility. But at the moment I haven't even reproduced the error.

**Comment by tomjridge** [comment]
I asked Victor to try the following patch to the Tezos codebase:

```
modified   src/lib_context/context.ml
@@ -325,6 +325,7 @@ module Make (Encoding : module type of Tezos_context_encoding.Context) = struct
     let* () = unshallow context in
     let+ c = Store.Commit.v context.index.repo ~info ~parents context.tree in
     Store.Tree.clear context.tree ;
+    Irmin_pack_unix.Pack_store.clear_all_caches() ;
     c
```

This is in the `raw_commit` function. The patch ensures that after each commit we clear all the Irmin caches. This is similar to what we do when performing GC with trace replay: we need to ensure that no commits after a GC commit can use cached data to access regions of the file before the GC point.

Victor re-ran the boostrap of mainnet, and he reports that the error above does not appear, and the node successfully bootstrapped. I have asked him to try the bootstrap again, just to give more confidence, and I should try this on my side as well.

What kind of sharing is happening here? This is sharing between a commit C and data from a previous commit, where the parent P of C does not share that data. This breaks one of the layers/GC invariants: all sharing from a commit to a previous commit has to occur via the parent. 

Theoretically, we do not mind if commits share data in this way with previous commits, providing all the commits are within the same "epoch" (i.e., no intermediate GC points between the commits). So, for example, if we know all the commits that will be used as GC points, then we only have to flush the caches after each of these. However, this is likely very fragile, so the current approach resorts to flushing on each commit. Of course, reducing the caching in this way likely leads to increases elsewhere, eg the store.pack file likely becomes larger because there is less reuse of objects between commits (because less caching).

At any rate, the problem appears resolved.

**Comment by Ngoguey42** [comment]
> At any rate, the problem appears resolved.

Do you mean it is resolved by discarding the caches at every commit? If yes, this is a bit unsatisfying

**Comment by tomjridge** [comment]
The problem is that we don't want any sharing-by-cache over the GC commit. Since we don't know ahead of time which commit will be used for the GC, the safe option is to discard the caches after every commit. Something more nuanced could be done for Tezos, but it would require them calling a "flush the caches" after the commit that will be used (5 or 6 cycles later) for GC. I imagine this will be error prone. On the flip side, I'm not sure clearing the caches after every commit impacts performance significantly. So although it appears brutal, I still favour the "flush caches after every commit" approach.

**Comment by Ngoguey42** [comment]
I doubt that the LRU enables sharing across commits. 

This LRU allows 2 speedups:
- Avoiding reading the disk when doing the `key -> value` operation (i.e. find) https://github.com/mirage/irmin/blob/0fd10afdfd937909822ace220c81ce8de5352b8c/src/irmin-pack/unix/pack_store.ml?ts=4#L306
- Avoiding reading the disk when doing the `key -> bool` operation (i.e. mem) https://github.com/mirage/irmin/blob/0fd10afdfd937909822ace220c81ce8de5352b8c/src/irmin-pack/unix/pack_store.ml?ts=4#L202

It is not used as a hash consing technique to deduplicate entries on disk (as index does).

**Comment by tomjridge** [comment]
The evidence from testing was that the lru did allow sharing between commits, and flushing the lru after a GC commit was required. Indeed, it fixed the bugs I saw (at various points - during trace replay and later when Victor was testing bootstrapping etc). To argue the contrary I think we need: 1) to be absolutely sure that the lru cannot allow sharing between commits; and 2) an explanation of why flushing the lru fixed the bugs; and 3) an alternative fix for the bugs we saw. 

From what I see: the lru indexes objects by **hash**; the lru is not flushed after a commit (so, objects are carried over in the lru from one commit to the next); later commits may attempt to look up an object by hash in the lru... if the object is found, then it is used, and this introduces the sharing between commits. If this is what happens (please say if I am wrong!) then it seems the lru does enable sharing?
