### ISSUE TITLE
`Irmin.clone_force` behaves inconsistently across Irmin_mem and Irmin_git.FS when tag name has a space

### ISSUE THREAD

**Issue by yomimono** [mirage/irmin#186]
With a store created via `Irmin.basic (module Irmin_mem.Make)`, calls like this work fine:

```
Irmin.clone_force Irmin_unix.task (t "merge_pairwise: clone map") "update cache"
```

but with stores created via `Irmin.basic (module Irmin_unix.Irmin_git.FS)`, such an operation hangs indefinitely.  Replacing `update cache` with `update_cache` results in the expected behaviour.

(I'm not necessarily expecting tag names with spaces to work properly on a Unix filesystem, but an error would be nice.)

**Comment by samoht** [comment]
> (I'm not necessarily expecting tag names with spaces to work properly on a Unix filesystem, but an error would be nice.)

I agree but I'm not sure what to check exactly.

**Comment by yomimono** [comment]
Thank you!

**Comment by samoht** [comment]
So I have decided to be ultra conservative and only allow a small number of ASCII characters in tag names. This can be changed by providing a different `Tag.is_valid` function.
