### ISSUE TITLE
Git reports Irmin repository is "not properly sorted"

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#190]
I have a repository with two (simple, non-merge) commits (generated by Irmin). In the second, Git seems to think that a single file (`contact/1`) was both added and removed:

    $ git whatchanged ours
    commit d38c7e0e15e65615f69f717e290ddabc4308ddb2
    Author: User <irmin@openmirage.org>
    Date:   Thu Jan 1 00:00:00 1970 +0000

	ours

    :000000 100644 0000000... 68af613... A  contact/1
    :100644 000000 a0a1e55... 0000000... D  contact/2
    :100644 000000 b7ad159... 0000000... D  contact/1
    :100644 000000 fb1e2c7... 0000000... D  context/0
    :100644 100644 d584f62... f996070... M  db/4
    :100644 000000 b65d940... 0000000... D  db/2
    :100644 000000 fe50010... 0000000... D  db/0
    :100644 000000 24f467b... 0000000... D  db/1
    :000000 100644 0000000... b3f2917... A  db/3
    :000000 100644 0000000... 2c5ee57... A  db/1

    commit 8bb2d05f0e42a77aab6099147d07f7fbdded4b11
    Author: User <irmin@openmirage.org>
    Date:   Thu Jan 1 00:00:00 1970 +0000

	base

    :000000 100644 0000000... a0a1e55... A  contact/2
    :000000 100644 0000000... b7ad159... A  contact/1
    :000000 100644 0000000... fb1e2c7... A  context/0
    :000000 100644 0000000... d584f62... A  db/4
    :000000 100644 0000000... b65d940... A  db/2
    :000000 100644 0000000... fe50010... A  db/0
    :000000 100644 0000000... 24f467b... A  db/1

`git fsck` reports:

    $ git fsck ours
    notice: HEAD points to an unborn branch (master)
    Checking object directories: 100% (256/256), done.
    error in tree 540b3918b87dba8341bc6c29175b90d7b09d740a: not properly sorted
    error in tree 9b08c0a6b9bf7372b02973be0a9f8acccdedcb11: not properly sorted
    error in tree 9f11705308fc218a6686b13de927ce891dbf4e53: not properly sorted
    error in tree e5ec0596848ebbed5b35d2e3593f667ce7a66798: not properly sorted
    dangling commit faee2ba7d3d3c6932d9a30ac7d8cb4ae8c53c2af

    $ git ls-tree ours
    040000 tree 736390337be9c3ee4142cdc1bb3f4bb3e107a839    contact
    040000 tree e5ec0596848ebbed5b35d2e3593f667ce7a66798    db

    $ git ls-tree 736390337be9c3ee4142cdc1bb3f4bb3e107a839
    100644 blob 68af613326b90ed34821de7527744285e7322dfd    1

    $ git ls-tree e5ec0596848ebbed5b35d2e3593f667ce7a66798
    100644 blob f9960701c6239c13cc4ab2f76500b8c21b3e72ac    4
    100644 blob b3f29170fe678a0f09e6a8d7d91d3aa244bf7971    3
    100644 blob 2c5ee57f8938412d1862bd09e4b3d6301ab79cdc    1

    $ git ls-tree ours~1
    040000 tree 9b08c0a6b9bf7372b02973be0a9f8acccdedcb11    contact
    040000 tree e1a4aeeb23173f6326608dfe59467c2be502acba    context
    040000 tree 9f11705308fc218a6686b13de927ce891dbf4e53    db

    $ git ls-tree 9b08c0a6b9bf7372b02973be0a9f8acccdedcb11
    100644 blob a0a1e5554d22787ae29da6de744c83ba3ead3738    2
    100644 blob b7ad159b9d18022a12df60bb07ecedfc170d2992    1

Any ideas how this could happen?

**Comment by talex5** [comment]
To reproduce:

    $ irmin init -d -v

[ new terminal, same directory] 

    $ irmin write 1 x
    $ irmin write 0 x

    $ git fsck
    Checking object directories: 100% (256/256), done.
    error in tree b635325f329e7c0807f7022a6b2cbc1413982911: not properly sorted

    $ git ls-tree HEAD
    100644 blob c1b0730e0133447badcfd47fd144e254807b06e1    1
    100644 blob c1b0730e0133447badcfd47fd144e254807b06e1    0

**Comment by talex5** [comment]
Also, it sometimes creates empty directories:

    $ git ls-tree result
    040000 tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904    contact
    040000 tree a1e6e305a029a8f1ce5d139a52e3d852cb7e98c2    db
    040000 tree 397cebe17a56e361ac5667a10916e6bd475a8c81    context
    $ git ls-tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904

That can make trees look different even when they're really the same.

**Comment by samoht** [comment]
Some of this might be related to https://github.com/mirage/ocaml-git/issues/68. But the main thing is that I choose to not sort the directories names when serialising (because my early experiment showed that it was confusing Git in some occasions). I guess I'll have to look into that again :-)

**Comment by yansh** [comment]
and by extension to #170 :+1: 

thank you both!

**Comment by samoht** [comment]
I've fixed the ordering, but I'm not sure to see where the empty dirs issue comes from. I'll have an other look but if you manage to have a repro it would be helpful.

**Comment by talex5** [comment]
Here's a CueKeeper branch showing the bug: https://github.com/talex5/cuekeeper/tree/empty_dir_bug

Running `make test` should fail with e.g.:

    [ random seed = 132754482 ]
    Failure: cue-keeper:3:merging
    ours+base
    expected: context,db but got: contact,context,db

(the tests are random, but it tries 100 times and usually fails immediately)

The Git directory is `/tmp/test_db`, with branches `base`, `ours`, `theirs` and `result`. `result` will be the one with the empty directory.

If you uncomment this line (which ignores empty directories), the tests will pass:

https://github.com/talex5/cuekeeper/blob/32138905dc6652df4c8ff9781ad2ba9be53c76a3/test.ml#L92

**Comment by samoht** [comment]
I've found a bug in `View.remove` and fixed it. I'll merge shortly the fix and see if the bug is still there in your branch.

**Comment by samoht** [comment]
Right, my fix has indeed fixed your issue. Thanks for providing the test cases. Closing.

**Comment by samoht** [comment]
This is not properly fixed, which causes all sort of madness (ie. duplicated entries). I'm fixing this now.

**Comment by samoht** [comment]
Fixed by 5045aa4. The fix is in 0.9.7
