### ISSUE TITLE
irmin opam file seems to have wrong {test} deps

### ISSUE THREAD

**Issue by avsm** [mirage/irmin#195]
In the `opam` files we have:

```
depends: [ ...
  "git" {test}
  "cohttp" {test}
  "alcotest" {test}
]
```

but these are all depends that affect core features (eg. the availability of `irmin.unix`). Why are they are marked as `{test}` only depends then?  I think this is breaking imaplet for exampe: https://travis-ci.org/ocaml/opam-repository/jobs/59724112

**Comment by samoht** [comment]
There are also depopts

**Comment by samoht** [comment]
In the run you copy/pasted, `git 1.4.3` was installed which is too old. The smart HTTP protocol was added in `1.4.4`. That's a problem in the constraints of `irmin 0.9.3`.

**Comment by samoht** [comment]
Also the test starts by installing `irmin 0.8.4` so there is a problem of irmin constraints in `imaplet-lwt` as well.

**Comment by samoht** [comment]
@avsm see https://github.com/ocaml/opam-repository/pull/4001 for fixing the depopts. `imaplet-lwt` constraints towards Irmin should also be fixed.

**Comment by avsm** [comment]
Aha! Thanks
