### ISSUE TITLE
irmin-pack: document the GC feature

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1960]
The new GC feature needs to be documented in the CHANGELOG - and maybe with extra specs/documents added to the repo. There are various tradeoffs that need to be highlighted.  For instance:
- it only works for minimally indexed stores
- after https://github.com/mirage/irmin/pull/1925, potential hash-consing optimisations are disabled to ensure GC consistency
- maybe other?

Also, it would be nice to give a few examples of how to use/configure it.

**Comment by samoht** [comment]
Kevin is writing examples of how to use the GC - and documenting the API in the process.

**Comment by tomjridge** [comment]
Just to say that the following might be useful sources of documentation: 

1. The very old prototype https://github.com/tomjridge/sparse-file had quite a lot of code documentation; there was also some more in the old version of the code. 
2. There is quite a lot of accumulated documentation (not code comments): https://docs.google.com/document/d/1UjKMNEKgB4Iee8drlhMJLONiom5XTOkM1g4DJv0UZ0I/edit#

**Comment by metanivek** [comment]
In the above PR, the example file documents

1. A simple example of how to configure irmin-pack and use the gc feature
2. That a minimal indexing strategy is needed to use gc

We can address more extensive design and/or long-form documentation in follow up PR(s).

**Comment by metanivek** [comment]
I think this can be considered completed with the existing [example](https://github.com/mirage/irmin/blob/main/examples/irmin-pack/gc.ml) and #2228.
