### ISSUE TITLE
irmin-pack: reduced LRU cache hits, much increased disk reads (irmin main vs 3.3.1)

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1974]
On 2022-07-07, Zach reported reduced LRU cache hits and much increased disk reads, when comparing irmin main branch and 3.3.1.

Attached are the original stats.txt, and an annotated version highlighting the major differences. 

[stats.txt](https://github.com/mirage/irmin/files/9070797/stats.txt)
[stats-annotated.txt](https://github.com/mirage/irmin/files/9070799/stats-annotated.txt)

**Comment by tomjridge** [comment]
These stats are significantly different from those reported in #1959.

**Comment by zshipko** [comment]
It looks like increasing the size of the lru ([here](https://github.com/mirage/irmin/blob/d69da1bfa4d6f599ee736381de738c21fb595c17/src/irmin-pack/unix/pack_store.ml#L97)) to `10_000_000` gets us much closer to 3.3.1 in terms of reads, `pack.finds.cache_miss` and `pack.finds.from_pack_direct`. It also increases memory used to around 2x.

This seems to mean that the issue is a lot more values are being created than before and new values are pushing other values out of the cache too early.

Here are the stats with this change: [stats.txt](https://github.com/mirage/irmin/files/9097632/stats.txt)

**Comment by zshipko** [comment]
Running the tree benchmark without the GC doesn't exhibit the same caching issues. I also did a run without the calls the `purge_lru` at the end of the GC and it also was nearly as performant as 3.3.1. It seems like the issue isn't really the LRU size or the change from hashes to offsets but that clearing the cache every time the GC runs has more impact than expected. 

Here are the stats comparing 3.3.1, main, main (without calls to `purge_lru`) and main (gc disabled): [stat.txt](https://github.com/mirage/irmin/files/9136252/stat.txt)

**Comment by samoht** [comment]
We should probably just purge the `commit` cache? What was the rationale for purging the node and contents stores caches too? They are expected to keep the same offsets/encoding right?

**Comment by icristescu** [comment]
@zshipko ah yes, good find! 
We need to clear the lru after the gc ended to removed the _gced objects_ from the lru - the objects kept indeed have the same offsets, so those are fine to stay in the lru.

**Comment by tomjridge** [comment]
I think it should be OK to just keep the LRU as it is (even with the GCed objects!); since the GCed objects are indexed by offset, they should no longer be touched and presumably eventually drop out of the LRU.

**Comment by icristescu** [comment]
The issue is that doing mem/find on a gced object it should return false/not found. The assumption that users never need to lookup a gced object, I'm not sure that it holds, I remember not being the case in the previous layered store.

**Comment by tomjridge** [comment]
I think in the Tezos codebase they may do something to handle the case of (for example) RPCs attempting to access commits that have been GC'ed. So effectively with Tezos, after a GC you can no longer access the commits removed by the GC. So it may be that you then can't access any of the other objects that have been GCed. 

(This is mostly guesswork! I'm suggesting it may be safe to leave GCed objects in the LRU, but I don't know for sure! Perhaps worth trying with a bootstrap or some other test)

**Comment by metanivek** [comment]
I believe this has been addressed. See https://github.com/mirage/irmin/issues/1959#issuecomment-1219810473 for current disk stats.
