### ISSUE TITLE
irmin-pack: possible increased disk usage for GC

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1979]
It was reported that:

_It seems that the disk footprint of the GC is around 40Gb for a recent context, while the context (~6 cycles) is ~37Gb (a total of ~80Gb while GCing)
IIUC, as we need to "duplicate" the state of the context at some point, we need a bit more that twice the size of a context to perform a merge._

40GB GC overhead for a 37GB context seems high compared to the previous version of the code, but could just as well be "normal".

How the GC operates: The main GC step which requires lots of disk space is when creating the new suffix. The old suffix is copied, from the GC commit point up to the end, into a new file. In the Tezos use case, the GC commit is 5 cycles in the past. So we need to copy roughly 5 cycles worth of data into the new suffix. Since GC takes some time, we also need to copy whatever data has been added to the suffix _during the GC run itself_. In normal operation, this is fairly small, but when bootstrapping this might be large (e.g. if GC takes 20 or 30 minutes to run).

**Comment by tomjridge** [comment]
One possible cause might be: temporary files (of the order of 5GB or so) are kept around longer than they are needed. Temporary files should be deleted if not needed, *before* the creation of the new suffix.

**Comment by tomjridge** [comment]
The previous version of the code had a space overhead of 25 to 30GB. So the current version seems to have an extra 10GB of overhead. However, blocks may be larger now than a month or so ago, leading to increased size of each cycle, and increased size of copied suffix. Needs further investigation.

**Comment by tomjridge** [comment]
A suggestion (from samoht): 

It may be that the LRU change interacts badly with snapshot import (or even export): e.g. the snapshot code may rely on the dedup provided by the LRU, and if this dedup no longer happens we may get increased size of context after snapshot import.

One way to investigate this would be: compare snapshot import context size (between the current irmin main and irmin main before the LRU change); are they the same or does the recent code result in increased context size after import? 

(@samoht - please edit this if I have it wrong!)

**Comment by samoht** [comment]
Something interesting to test:
- start from a snapshot and run six cycles on irmin 3.2.x (without GC)
- start from a snapshot and run six cycles on irmin `main` (with GC)
And check the size on the disk.

It would be nice to run this from the tree benchmarks too (but we need to fix the stats reporting for file sizes).

**Comment by metanivek** [comment]
This was addressed with [Irmin 3.5](https://github.com/mirage/irmin/releases/tag/3.5.0)'s chunked suffix.
