### ISSUE TITLE
layered-store: index loading seems slow (maybe too many entries)

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1982]
Victor reports: The context's loading seems pretty slow. Here is the trace of two consecutive Context.init (the first in the external validator (RW), the second for the node (RO)). Does it looks normal? (this is not a priority issue, we can discuss briefly about it during today's meeting)

```
+274603us index [INFO] [context] v fresh=false readonly=false log_size=2500000
+274636us index [DEBUG] [context] not found in cache, creating a new instance
+274647us index_unix [DEBUG] Locking ./lol/context/index/lock
+274698us index [DEBUG] [context] log file detected. Loading 22785538 entries

+25472889us index_unix [DEBUG] get_generation: 0
+25472964us index [DEBUG] [context] no index file detected.
+26354032us index [INFO] [context] v fresh=false readonly=true log_size=2500000
+26354094us index [DEBUG] [context] not found in cache, creating a new instance
+26354158us index [DEBUG] [context] checking for changes on disk (generation=0)
+52298987us index [DEBUG] [context] loaded 45571076 entries from log
+52299080us index_unix [DEBUG] [./lol/context/index/log] get_headers: { offset = 1025349210; generation = 0 }
+52299106us index [DEBUG] [context] no changes detected
```

**Comment by tomjridge** [comment]
What I wrote in reply: I would say that this doesn't look normal. Since the "structured keys" work, the index is not used very much. In "minimal indexing" mode (what is required for GC) the index is hardly used at all: It stores a map from commit to "offset in store.pack". Thus, there should be relatively few entries in the index. Here, it seems the RW finds 23M entries in the index log; the RO finds 46M entries in the index log. The index log is supposed to be limited to 2.5M entries. So these numbers seem 1) very high if we are using minimal indexing; and 2) much higher than the 2.5M max entries we would expect to find in the log.

**Comment by icristescu** [comment]
The issue is due to importing snapshot in a legacy format, that requires indexing always https://gitlab.com/tezos/tezos/-/blob/master/src/lib_store/unix/snapshots.ml#L3665. 
In order to use legacy snapshot with the Gc feature, the workflow is:
- import an “old” snapshot;
- export it as a new snapshot;
- then import it again - as the snapshot is in the new format it will use indexing `minimal`

With this workflow the context loading is not slow anymore.
