### ISSUE TITLE
Q: Has anyone tried to apply the functors to an API like WebHDFS?

### ISSUE THREAD

**Issue by smondet** [mirage/irmin#201]
Implementing something like `Irmin.S_MAKER` with Cohttp calls?

http://archive.cloudera.com/cdh4/cdh/4/hadoop/hadoop-hdfs-httpfs/index.html
http://archive.cloudera.com/cdh4/cdh/4/hadoop/hadoop-project-dist/hadoop-hdfs/WebHDFS.html

**Comment by samoht** [comment]
I don't think so (at least not me). Would be quite easy to use webHDFS as an append-only store (ie. just to have a hash/objects global mapping) so you can distribute the block store over multiple nodes.
