### ISSUE TITLE
irmin-pack: GC: main process may have problems switching to new prefix/suffix after child process completes

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#2026]
Victor Allombert reported on slack:

---

I have two machines running the GC.
The first, a powerful one, succeeded it's last GC (in a few minutes). However, the second one, a standard VPS, is still in a weird state, since ~15h. The storage contains the new suffix and the old suffix (disk footprint is high, see http://platypus.testnets.tzalpha.net:3000/d/j2yqcTenk/tezos-full-dashboard-branch-master?orgId=1&from=now-24h&to=now). My first though was that the GC was particularly long, but only the store.0.suffix was updated recently (diff in terms of size). See
```
ls -al ~/.tezos-node/context/
total 51790968
drwxr-xr-x 3 debian debian        4096 Jul 19 15:44 .
drwxrwxrwx 4 debian debian        4096 Jul 12 07:46 ..
drwxr-xr-x 2 debian debian        4096 Jul 12 07:27 index
-rw-r--r-- 1 debian debian 29790617684 Jul 20 07:03 store.0.suffix
-rw-r--r-- 1 debian debian    19433344 Jul 19 15:40 store.1.mapping
-rw-r--r-- 1 debian debian          18 Jul 19 15:44 store.1.out
-rw-r--r-- 1 debian debian  3917129952 Jul 19 15:41 store.1.prefix
-rw-r--r-- 1 debian debian 19300127540 Jul 19 15:44 store.1.suffix
-rw-r--r-- 1 debian debian          67 Jul 12 07:27 store.branches
-rw-r--r-- 1 debian debian          25 Jul 20 07:03 store.control
-rw-r--r-- 1 debian debian     6579773 Jul 12 07:27 store.dict
```
Looking at the log, it seems that the GC started :
```Jul 19 15:31:34.370 - node.store: running context garbage collection up to level 2506753
Trigger GC for commit CoVdgbhT7GCXmjUiacm3UYA9CPNUjpJa2ajTpNcWmJh4429sSqJ9
+632705392657us irmin-pack.unix [INFO] GC: Starting on {"Direct":["CoVdgbhT7GCXmjUiacm3UYA9CPNUjpJa2ajTpNcWmJh4429sSqJ9",9575682939,128]}
```

But I've failed to find the "Gc ended" event.

---

Later he observed a similar thing on a small VPS.

**Comment by metanivek** [comment]
Confirmed with Victor that he has not seen this again with the latest code.
