### ISSUE TITLE
Slices.{read/write} is broken

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#204]
From @talex5 

```ocaml
open Lwt

module Store = Irmin.Basic(Irmin_mem.Make)(Irmin.Contents.String)

let config = Irmin_mem.config ()
let task s = Irmin.Task.create ~date:0L ~owner:"User" s

let main =
 Store.create config task >>= fun t ->
 let t = t "test" in
 Store.update t ["key"] "value" >>= fun () ->
 Store.head t >>= function
 | None -> assert false
 | Some head ->
 Store.export t ~min:[] ~max:[head] >>= fun slice ->
 let buf = Cstruct.create (Store.Private.Slice.size_of slice) in
 let rest = Store.Private.Slice.write slice buf in
 assert (Cstruct.len rest = 0);
 let _slice2 = Store.Private.Slice.read (Mstruct.of_cstruct buf) in
 return ()

let () =
 Lwt_main.run main
```

I was expecting _slice2 to be the same as slice, but instead I get an
error during the read (even in native code):

````
Fatal error: exception Ir_hash.Invalid("lueB+��1d|E���O��<��key")
````

**Comment by talex5** [comment]
[ copying from mailling list ]

This is due to `Irmin.Contents.String` overriding the default serialisation:

https://github.com/mirage/irmin/blob/ae42dab34d8451395910eb4cd534ee887a6871a5/lib/ir_contents.ml#L143

> The goal is to have the file contents (once expanded on the filesystem) serialised as the raw string, not at the string with a prefix.

> While I agree that this breaks composability, I'm not sure how to fix it properly. I'd probably wrap the contents in Ir_slice.t into something that make bin-prot happy.
