### ISSUE TITLE
Add binary RPC client/server backends

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#205]
We currently have a REST/JSON client/server over HTTP (`Irmin_http` and `Irmin_http_server`). It would be nice to have the same kind of RPC service but using the binary protocol instead of JSON -- it would be more efficient and exercice some code paths not very well tested yet (see #204)).

**Comment by talex5** [comment]
I've got binary sync working* now in CueKeeper, which may be useful as an example: https://github.com/talex5/cuekeeper/blob/server/server/unikernel.ml

* no security or persistence yet though

**Comment by samoht** [comment]
Awesome!

**Comment by pascutto** [comment]
See https://github.com/mirage/irmin-rpc/
