### ISSUE TITLE
Migration: Irmin.Contents.String_v2 implications for git

### ISSUE THREAD

**Issue by reynir** [mirage/irmin#2053]
Hello,

I'm porting some code from irmin >= 2.10.o & < 3.0.0 to irmin >= 3.0.0. The code fetches a remote git repository. In #1715 a change was made that among other things added `Irmin.Contents.String_v2`. I am curious what consequences there are (not) having compatibility with older irmin versions with regard to git.
```OCaml
  module String : S with type t = string
  (** Contents of type [string], with the {{!Irmin.Merge.default} default} 3-way
      merge strategy: assume that update operations are idempotent and conflict
      iff values are modified concurrently. *)

  module String_v2 : S with type t = string
  (** Similar to [String] above, but the hash computation is compatible with
      versions older than irmin.3.0 *)
```

Thank you.

**Comment by reynir** [comment]
For some more context the code in question is in https://github.com/roburio/unipi/pull/9.

**Comment by samoht** [comment]
For the Git backend, that shouldn't make a difference - the backend is overwriting the `pre_hash` function to look like Git, so both `String` and `String_v2` object will have the same hash.
