### ISSUE TITLE
irmin-pack: Pack_store assumes that index entries are valid

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#2067]
The GC routine doesn't clean up index for simplicity. In exchange, we should be really careful in `pack_store.ml` to never assume that if a key exists in index it then exists in the pack files (i.e. suffix and prefix). 

The GC is not the only source of such problems. The user could be holding corrupted keys. We already have mechanisms and policies in place in `pack_store.ml` to deal with such corrupted keys, but these mechanisms should be revised now that the GC exists.

---

@vect0r-vicall found a problem when re-commiting a commit that was previously GCed. 

IIUC, the `unsafe_append` function in `pack_store.ml` skips the saving of this commit because it sees this hash in index.

**Comment by metanivek** [comment]
Fixed with https://github.com/mirage/irmin/pull/2070
