### ISSUE TITLE
Irmin 0.9.5 fails to install from opam repo (missing OUnit)

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#214]
# File "lib_test/test_store.ml", line 611, characters 8-25:
    # Error: Unbound module OUnit

Looks like the OUnit dependency is missing from the Git opam file too.

This is breaking the Travis build for CueKeeper:

https://travis-ci.org/talex5/cuekeeper/builds/69100229

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4346

I'll fix up the `opam` file in master.

**Comment by samoht** [comment]
I'll cut a 0.9.6 very soon, which will be compatible with alcotest 0.4
