### ISSUE TITLE
LICENSE file discrepency

### ISSUE THREAD

**Issue by raphael-proust** [mirage/irmin#2164]
The `LICENSE.md` file is ISC. But some packages mention `MIT` license. This probably needs to be explicitly listed somewhere. Maybe via dual licensing or maybe with a `LICENSE.md` file within the differently-licensed directories.

**Comment by samoht** [comment]
Should be fixed by #2165 and https://github.com/ocaml/opam-repository/pull/22894

**Comment by raphael-proust** [comment]
Thanks!
