### ISSUE TITLE
`clone` seems subject to races on non-memory backends

### ISSUE THREAD

**Issue by yomimono** [mirage/irmin#221]
I have a test for irmin-arp which causes multiple Lwt threads to attempt to clone, make an update, and merge to the same node on the same store simultaneously (or close enough to it).  Each thread attempts to get a unique tag for its branch by matching on the result of `clone` and disambiguating further if the result is `Duplicate_tag`.  However, the observed behavior is that multiple threads will commit to the same branch, indicating that more than one thread is getting an `Ok` result for the same tag.

This doesn't occur on the in-memory store.  It looks like `clone` checks for duplicate tags, then calls `clone_force`, which might have to yield if the lock for the repository is already held by another thread.

**Comment by samoht** [comment]
Wooops, this code path is indeed not protected from races. Thanks for spotting this!
