### ISSUE TITLE
Size queries

### ISSUE THREAD

**Issue by dsheets** [mirage/irmin#231]
It would be great to have a way to extract the size of a value without reading it into memory. Along with #84 (move) and #142 (branch vs leaf), this is a very useful capability for file systems.

**Comment by samoht** [comment]
I have spent a little bit of time on this (a branch is even visible [there](https://github.com/samoht/irmin/tree/sizes)) but it is not totally clear to me which `size` we want to expose: is it the size after serialisation of the values? The size of the serialisation on disk?  The in-memory size?

It is thus probably best to expose `size` in `Irmin.Type` and/or to ask the user to provide something. As the design is not totally clear to me, I am moving that issue out of the 1.0.0 Milestone.

**Comment by maiste** [comment]
We have size estimations in `Irmin.Type` (`Repr`).
