### ISSUE TITLE
Irmin.pull seems to always fail between remote URIs and in-memory stores

### ISSUE THREAD

**Issue by yomimono** [mirage/irmin#235]
It seems that attempting to run Irmin.pull on an Irmin store made with `Irmin.basic (Irmin_mem.Make)` and a remote made with `Irmin.remote_uri` always returns `Ok Error`.  Is this intended, and if so is it possible to express this incompatibility in the type system somehow?  I was surprised to discover a wider array of possible exceptions when running tests on repositories made with `Irmin_unix.Irmin_git.FS` vs `Irmin_mem.Make`.

I can work around this for my application, but I think I might not be the only person surprised by this behavior.

**Comment by samoht** [comment]
err, this should work. Do you use the last version of `ocaml-git` (1.6.0)?

All backend should behave in the same way. Please report errors if you see them :-)

**Comment by samoht** [comment]
Regarding `Irmin_mem` you might need to `open Irmin_unix` first or use `Irmin_unix.Irmin_mem`. You need to tell Irmin how you do `IO` if you want to sync. This should probably be specified in the doc, pull requests are welcome!

**Comment by yomimono** [comment]
Apparently I have 1.5.2, so I'll retry with 1.6.0 and see whether this still occurs.

**Comment by samoht** [comment]
Also, the Git's smart HTTP protocol had some issues that are fixed by https://github.com/mirage/ocaml-git/pull/102. I'll try to make a new release soon.

**Comment by samoht** [comment]
ocaml-git 1.6.1 has just landed in opam, with few fixes in the smart HTTP protocol (`https://<path.git>`).

**Comment by yomimono** [comment]
Sorry for the long reply on this; I destroyed my ability to reproduce the problem and test with the updated packages, but having looked into it more I think that's probably not necessary.  

I think this result is because `Irmin_mem.Make` uses `Irmin.Make`  which calls `Ir_bc.Make` directly, which sets `module Sync = Ir_sync.None`, which in turn will always return `Ok Error`.  On looking more deeply into Irmin it's not surprising that stores made with the Irmin_mem backend don't know how to sync with a remote URI, since information on how to (for example) resolve URIs hasn't been provided to it.

I don't see how this could be resolved in the current architecture in any way other than by making a new in-memory backend that also demands module arguments which know how to resolve and contact remote hosts, as Irmin_git.Make_ext does.  Am I correct in this understanding?

**Comment by samoht** [comment]
> Am I correct in this understanding?

Almost. It's actually possible to have a memory backend which use the right synchronisation primitive and it is already been done for the [Git in-memory backend](https://github.com/mirage/irmin/blob/master/lib/unix/irmin_unix.mli#L131). `Irmin_unix` should be able to redefine this.

I'll add this in the next release.
