### ISSUE TITLE
"bare" is actually "no-checkout"

### ISSUE THREAD

**Issue by Chris00** [mirage/irmin#243]
`Irmin_unix.Irmin_git.config` and the like have a `~bare` option.  However this is misleading if understood in Git speak: `--bare` does not create a `.git` subdirectory while in Irmin this does not do a checkout.  I suggest to rename it `no_checkout`.

In one or two version, one can set `bare: [`Use_no_checkout]` to help people to migrate.

**Comment by samoht** [comment]
I think this is more an issues in `ocaml-git` which will be fixed at one point (when I have time). Not sure it is worth distinguishing between `bare` and `no-checkout` in `Irmin`. I guess exposing the two options should be possible.

**Comment by Chris00** [comment]
Not a big deal but I wanted to let you know the discrepancy as it may be surprising.

**Comment by Chris00** [comment]
I think supporting `bare` is enough (not sure `no_checkout` is useful).

**Comment by samoht** [comment]
Fixed by #363
