### ISSUE TITLE
ERROR while installing irmin.0.9.8

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#248]
Another Travis failure:

https://travis-ci.org/talex5/cuekeeper/builds/74127652

    #=== ERROR while installing irmin.0.9.8 =======================================#
    # opam-version 1.2.2
    # os           linux
    # command      make test
    # path         /home/travis/.opam/system/build/irmin.0.9.8
    # compiler     system (4.02.1)
    # exit-code    2
    # env-file     /home/travis/.opam/system/build/irmin.0.9.8/irmin-35639-ce0575.env
    # stdout-file  /home/travis/.opam/system/build/irmin.0.9.8/irmin-35639-ce0575.out
    # stderr-file  /home/travis/.opam/system/build/irmin.0.9.8/irmin-35639-ce0575.err
    ### stdout ###
    # [...]
    # -- HTTP.MEM.012 Failed --
    # High-level store merges.
    # ./_tests/HTTP.MEM.012.output:
    # Server started on port 8080.
    #         DEBUG: post /update/a/b/a {"task":{"date":"1438720089","uid":"20401","owner":"Irmin testing-worker-linux-d..
    # 2015-08-04 20:28:09.316 MEM          DEBUG: iter
    # 
    # [exception] Unix.Unix_error(Unix.ECONNREFUSED, "connect", "")
    # 
    # 1 error! in 27.190s. 120 tests run.
    ### stderr ###

**Comment by samoht** [comment]
That's due a segfault in Lwt, fixed in 2.5.0: https://github.com/ocsigen/lwt/issues/136

Need a new release of cohttp to have the fix in ... But yea, should disable the tests in the release. I'll push a fix to opam-repository, thanks for the report.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4598

Would be very nice to have https://github.com/ocaml/opam/issues/2190 though...

**Comment by talex5** [comment]
Thanks - CueKeeper tests are passing again now :-)
