### ISSUE TITLE
Add an `irmin.cli` library

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#253]
Could be useful to have a set of standard command-line arguments.

We already the beginning of that here: https://github.com/mirage/irmin/blob/master/bin/ir_cli.mli

**Comment by dbuenzli** [comment]
I'm also planning to have that in some of my libraries should we agree to call that `$PKG.cli` in general.

**Comment by zshipko** [comment]
It seems like this can be closed since I've added `Irmin_unix.Cli`
