### ISSUE TITLE
Simplify result from iter REST call

### ISSUE THREAD

**Issue by MagnusS** [mirage/irmin#266]
The REST iter reply format looks similar to this now:

[ stream_token | version of string | result of string list ] list

It would be simpler to parse if the format was { version string; result
string list list}, which would also be more similar to the other API calls.

**Comment by samoht** [comment]
One issue with this is for watches, where you really need a stream of JSON objects. I don't know how well JSON clients deal with these, and if streaming only the value of a field makes sense at all.

**Comment by samoht** [comment]
No more `iter` call in the low-level CRUD API, so closing.
