### ISSUE TITLE
Document the `.irminconfig` file

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#280]
Instead of passing `-s <kind>` and config options on the command-line, Irmin supports reading configuration variables in the current directory:

So:

```
$ cat .irminconfig
store=http
uri=foo
$ irmin tree
```

is equivalent to

```
irmin tree --store=http --uri=foo
```

**Comment by samoht** [comment]
Also the fields in that file should not be case-sensitive.

**Comment by dudelson** [comment]
I am working on this!

**Comment by dudelson** [comment]
A couple of questions about this:

- How should this be documented? It seems like the most natural thing to do would be to add an `irminconfig` man page, but were you thinking of putting the documentation somewhere else?
- Besides removing case-sensitivity in the config file, there appear to be a number of other TODOs in the cli and resolver code, e.g.:
  - Moving to a toml config format
  - Interfacing the config file properly with Cmdliner
  - Adding the remote configuration to the config file
  - Inferring the remote kind from the config file

I'm not sure how much effort each of these would be, but would they be valuable contributions to the project?

**Comment by samoht** [comment]
Hi @dudelson, thanks for looking at that task.

- man pages is indeed probably the best page. There is already a `irmin help` command, which could be extended to work with `irmin help irminconfig`.
- for the TODO points, for me the main point is using a proper config format (`toml` or `yaml` or something similar to the Git config format). 

The other points are pretty minor but you are welcome to help if you wish. However, currently the command-line tool is more a debug tool to test the API that something really usable. Making it more usable/useful would probably need to think of the design first and what we want to achieve. But having a proper config with proper documentation is the first step no matter what :-)

**Comment by dudelson** [comment]
I understand how to extend the `irmin help` command, but from reading the Cmdliner docs I don't believe it's possible to create a man page for something that isn't a command. That is, from my current understanding, the only way to add `irmin help irminconfig` and have it display a man page is to create an `irminconfig` subcommand that does nothing. Other options would be having `irmin help irminconfig` dump a message to stdout, or adding the config file documentation to `help irmin`. I think all of these options are a little bit ugly, guidance would be appreciated.

**Comment by dudelson** [comment]
Also, where is the [`pure`](https://github.com/mirage/irmin/blob/master/bin/ir_cli.ml#L547) function defined? I cannot find it in the Cmdliner docs.

**Comment by dbuenzli** [comment]
@dudelson `pure` is there but deprecated use `const`. Regarding creating a help system it's a pattern I plan once to integrate in `Cmdliner` itself but meanwhile you can have a look at [this issue](https://github.com/dbuenzli/cmdliner/issues/70) which as references in how it was done in various other tools without being too ugly.

**Comment by dudelson** [comment]
Glad to know a pattern is in the works. Thank you for the link, I think I see how this is best accomplished now.

**Comment by dbuenzli** [comment]
In fact the sample `darcs` sample code also has the pattern see http://erratique.ch/software/cmdliner/doc/Cmdliner#exdarcs

**Comment by dudelson** [comment]
Is it possible to make a bulleted list in a manpage with Cmdliner? I want something that looks the same as the list in the `gitignore` manpage, for example (`git help ignore`).
