### ISSUE TITLE
More consistent types for params and results in the REST API

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#283]
Currently, `{ "params": ... }` and `{ "resuts":...}` have some restrictions in what they contain as we are using the latest released version [jsonm](https://github.com/dbuenzli/jsonm) which requires JSON serializer to produces arrays or objects. The master version of `jsonm` removes that restriction which will helps us being a bit more consistent there.

**Comment by MagnusS** [comment]
For example a successful `read` returns an array that always has a single item:

```
{"result":["value"],"version":"0.9.9"}
```

**Comment by samoht** [comment]
In 1.0, the high-level REST API has been removed. Only the low-level API to export and access the AO and RW stores is now available and these have been rewritten using `webmachine` so they are much more robust / consistent.
