### ISSUE TITLE
rest api: /view/create returns "-" separated string in json output

### ISSUE THREAD

**Issue by MagnusS** [mirage/irmin#295]
`/view/create` returns a head/node hash pair encoded in a string:

```
{"result":"3334cf1e47ddc6eea109bc64b27b0d7ceba6fa17-ebbe9892d45849d9fa37f94530b745cf9f88320e","version":"0.9.9"}
```

The reply would be easier to parse if the hashes were in a json array or  { "head" : .., "node" : ...}.

**Comment by samoht** [comment]
In 1.0, the high-level REST API has been removed. Only the low-level API to export and access the AO and RW stores is now available and these have been rewritten using `webmachine` so they are much more robust / consistent.
