### ISSUE TITLE
rest api: /view/merge-path returns "ok": null on success

### ISSUE THREAD

**Issue by MagnusS** [mirage/irmin#296]
The new `view/merge-path` call returns `{ result: { "ok" : null } .. }` on success. To match the other calls it should return `{ result: "ok" .. }` or a hash.

**Comment by samoht** [comment]
In 1.0, the high-level REST API has been removed. Only the low-level API to export and access the AO and RW stores is now available and these have been rewritten using `webmachine` so they are much more robust / consistent.
