### ISSUE TITLE
Use Jsont

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#300]
`Tc.S0` should expose:

```
val json: t Jsont.t
```

instead of the `to_json` and `of_json` functions.

**Comment by dbuenzli** [comment]
I guess you meant `jsont`, there's no such polymorphic type in `jsonm`.

**Comment by samoht** [comment]
indeed

**Comment by samoht** [comment]
Irmin.Type has now its own non-blocking codecs for JSON, so closing.
