### ISSUE TITLE
Must `BC` require `HRW`?

### ISSUE THREAD

**Issue by yomimono** [mirage/irmin#312]
I have a couple of use cases where it seems reasonable to want a branch-consistent store where there is no hierarchy of keys -- in other words, we want to store stuff but have only one level of naming associated with it.  (For example, if I'm implementing a store that maps  `uint32`s to `uint64`s, I get no value out of storing or referring to the keys as a `uint32 list` -- a maximum of one item in that list can be useful to me.)

Might it be possible to get branches without a name hierarchy?

**Comment by samoht** [comment]
In 1.0, `BC` has been renamed to `S` and`HRW` has been removed and folded directly into `S`.
