### ISSUE TITLE
Setting compression level to 0 in Irmin_git doesn't disable compression.

### ISSUE THREAD

**Issue by gregtatcam** [mirage/irmin#314]
A blob created by Irmin (git backend, with Irmin_git.config ~level:0) is still compressed.

**Comment by samoht** [comment]
Err sorry, just saw that you've created the issue. I guess it will be in 0.10.1 then... not sure why this doesn't work, do you have time to investigate it a bit more?

**Comment by gregtatcam** [comment]
Sure, no problem. I might some spare time in a few days.

**Comment by samoht** [comment]
This should be fixed with ocaml-git 2.0
