### ISSUE TITLE
http: internal error, uncaught exception if too many connections

### ISSUE THREAD

**Issue by MagnusS** [mirage/irmin#328]
After about 500 connections to the HTTP server Irmin exits with the following exception:

```
irmin: internal error, uncaught exception:
       Unix.Unix_error(Unix.EINVAL, "select", "")
```

Tested with release 0.10.0 and master.

To reproduce:

```
while : ; do curl http://localhost:8080/head -O /dev/null; done;
```

**Comment by samoht** [comment]
This needs some conduit tweak on the server-side, using something like

```
    Conduit_lwt_unix.set_max_active 100;
```
