### ISSUE TITLE
http: error format

### ISSUE THREAD

**Issue by MagnusS** [mirage/irmin#331]
The current error format for REST errors is not very consistent. It seems to be either a string or the name of the error type that occurred (or exception name) and a message:

`error_msg | {"failure" : error_msg} | {"invalid-argument" : error_msg} ...`

The different error types that can occur do not seem to be document anywhere?

It would be nice with a format that either always was a string with an error message or had fields for the error type and message, e.g. `{ type: "invalid-argument", message: "..." }`.

**Comment by samoht** [comment]
In 1.0, the high-level REST API has been removed. Only the low-level API to export and access the AO and RW stores is now available and these have been rewritten using `webmachine` so they are much more robust / consistent.
