### ISSUE TITLE
Dependency problem with sexplib?

### ISSUE THREAD

**Issue by wiredsister** [mirage/irmin#337]
From a fresh switch, I `opam upgrade` and then `opam install irmin` and this happens:

```
opam install irmin
The following dependencies couldn't be met:
  - ezjsonm -> sexplib < 113.01.00
Your request can't be satisfied:
  - No package matches sexplib<113.01.00.
```

**Comment by yomimono** [comment]
It looks like `ezjsonm` builds fine with sexplib 113.24.00 (the current version).  I filed an issue: https://github.com/mirage/ezjsonm/issues/22

**Comment by samoht** [comment]
1.0 doesn't use ezjsonm anymore so closing.
