### ISSUE TITLE
View.update is really expensive

### ISSUE THREAD

**Issue by talex5** [mirage/irmin#344]
I was using `View.update` to update a file's contents as data is streamed over the network, but I kept running out of memory. Looking at the code, I see:

```
let update_contents t k v =
  t.ops := `Write (k, v) :: !(t.ops);
  update_contents_aux t k v

let update t k v =
  Lwt_mutex.with_lock t.lock (fun () -> update_contents t k (Some v))
```

I think this means that the view is keeping a copy of every version of the file, right? We should probably provide some light-weight alternative for people who don't need this...

**Comment by samoht** [comment]
In 1.0, views are replaced by `tree` values, which provides snapshot isolation (instead of serialisability).  To guarantee snapshot isolation, we don't need the list of operations anymore (which was anyway an expensive way of ensuring that read/write conflict were caught).
