### ISSUE TITLE
Irmin on xen - current state

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#348]
it doesn't compile anymore... `bin_prot` (used by `mirage-tc`) needs to be patched (as you did here for a 112.35 version https://github.com/samoht/bin_prot/tree/112.35.00+xen), mirage-tc has an upper bound on `bin_prot  < 113.01.00`, but `pa_sexp_conv` requires (via `type_conv`) a `bin_prot >= 113.00.00`.

any plan to remove or upgrade the `bin_prot` dependency from `mirage-tc` (or remove the `mirage-tc` dependency from `irmin`)?

**Comment by hannesm** [comment]
the above relationship between `bin_prot` and `type_conv` is wrong.  an old `type_conv` requires an old `bin_prot`, and `pa_sexp_conv` is not happy with that `type_conv`

**Comment by hannesm** [comment]
(mirage-tc should be fine with newer `bin_prot` https://github.com/ocaml/opam-repository/pull/6205)

**Comment by hannesm** [comment]
and for bin_prot I started to add a xen sublibrary at https://github.com/hannesm/bin_prot/tree/113.33.00+xen but somehow I do not manage to convince the build system thereof to compile and install it...

**Comment by hannesm** [comment]
solved: https://github.com/hannesm/bin_prot/tree/113.33.00+xen now works (compiles, installs the xen sublibrary as wel); and using the result I can link a Canopy unikernel! :)

**Comment by hannesm** [comment]
would nevertheless be nice to get an opinion from @samoht about `bin_prot`...

**Comment by samoht** [comment]
I'm in favour of making that dependency optional.
