### ISSUE TITLE
Documentation for `bare` repository unclear.

### ISSUE THREAD

**Issue by kayceesrk** [mirage/irmin#362]
The documentation for a `bare` repository [0], says that 

> If bare is set (default is unset), then the local Git repository's contents will be expanded into the filesystem on each update. This might cause some performance issues.

Isn't the behaviour exact opposite? i.e., If bare is set, then the contents will **not** be expanded. 

[0] https://mirage.github.io/irmin/Irmin_unix.Irmin_git.html#VALconfig

**Comment by samoht** [comment]
yes that documentation is wrong. Would be great if you can make a PR to fix it, thanks!

**Comment by kayceesrk** [comment]
Done. See PR https://github.com/mirage/irmin/pull/363.

**Comment by samoht** [comment]
Thanks! It will be in the next release (0.12.0)
