### ISSUE TITLE
Merge function for option is broken?

### ISSUE THREAD

**Issue by kayceesrk** [mirage/irmin#421]
The merge function for the option type is broken. Here is the exhaustive list of cases for the option type merge, their merge result and why I think it should be the result. `old` is an optional value, with `None` indicating the absence LCA. 

| case | old | l | r | result | reason |
|------|----|--|--|-------|--------|
| 1 | None | None | None | None | change to the same value |
| 2 | None | Some x | Some y | merge ~old:None x y | recursive merge |
| 3 | None | None | Some x | conflict | no LCA, divergence | 
| 4 | None | Some x | None | conflict | no LCA. divergence |
| 5 | Some None | None | None | Some None | No change |
| 6 | Some None | Some x | Some y | conflict? | We have an LCA, but cannot apply recursive merge |
| 7 | Some None | Some x | None | Some x | change only in 1 branch |
| 8 | Some None | None | Some x | Some x | change only in 1 branch |
| 9 | Some (Some o) | None | None | None | change to the same value |
| 10 | Some (Some o) | Some x | Some y |  merge ~old:(Some o) x y | recursive merge |
| 11 | Some (Some o) | None | Some o | None | change only in 1 branch |
| 12 | Some (Some o) | Some o | None | None | change only in 1 branch |
| 13 | Some (Some o) | Some x | None | conflict | divergence |
| 14 | Some (Some o) | None | Some y | conflict | divergence |

My intuition behind the results is that the default merge function should not be smart; any doubtful merge should be marked as conflict.

The current implementation seems to make interesting (intelligent :-)) choices for some cases. For cases, 3 and 4, it returns `Some x` [0], even though there is a conflicting update in the other branch. For cases 11 and 12, the current implementation returns `Some o` [1] (not really since the initial call to the default function returns `None` for these cases [2]; the handling here is redundant but incorrect). Case 6 is handled as `merge ~old:None x y` i.e) even though there is an LCA, the recursive merge is invoked as if there isn't an LCA. I believe this is incorrect as we seem to be ascribing meaning to the `None` value here. The other cases seem to be right. 

[0] https://github.com/mirage/irmin/blob/master/src/ir_merge.ml#L131
[1] https://github.com/mirage/irmin/blob/master/src/ir_merge.ml#L135
[2] https://github.com/mirage/irmin/blob/master/src/ir_merge.ml#L111

**Comment by kayceesrk** [comment]
On further thought, if we consider setting the value to `None` as delete and `Some _` as add, then we can consider case 6 as concurrent additions at some key which was last deleted. So the right thing to do would be to call recursive merge for the value as `merge ~old:None x y` i.e) treat as if there was no common ancestor and let the recursive merge function deal with it.

**Comment by samoht** [comment]
This is fixed in 1.0.1.  but caused a regression for concurrent but idempotent updates. See also #429 which explained why the default option merge was defined like that initially.
