### ISSUE TITLE
Can't install irmin-unix on OS X Yosemite 

### ISSUE THREAD

**Issue by Danl2620** [mirage/irmin#424]
I have ocaml 4.03 and OPAM 1.2.2 installed. When I try to install the irmin-unix package I get this message:

```
Dans-MacBook-Pro:ml danl$ opam install irmin-unix
The following dependencies couldn't be met:
  - git-unix -> cmdliner < 1.0.0
Your request can't be satisfied:
  - No package matches cmdliner<1.0.0.

No solution found, exiting
```

Do I have the wrong version of something?

Thanks,
Dan

**Comment by samoht** [comment]
Try to pin `cmdliner` to a lower version (0.9.8). I'll release a fix later today.

**Comment by Danl2620** [comment]
Ok, it seems your fix worked -- I got further. I deleted my ~/.opam and tried again... now it has trouble compiling `src-unix/irmin_unix.ml`.

This is my error:

```
File "src-unix/irmin_unix.ml", line 82, characters 42-60:
Error: This expression has type
         Irmin_watcher_core.t =
           int -> string -> (string -> unit Lwt.t) -> (unit -> unit) Lwt.t
       but an expression was expected of type
         Irmin.Private.Watch.hook =
           int ->
           string -> (string -> unit Lwt.t) -> (unit -> unit Lwt.t) Lwt.t
       Type unit is not compatible with type unit Lwt.t 
Command exited with code 2.

```

**Comment by samoht** [comment]
Can you try to install `irmin-unix.1.0.1` that has been released a few days ago (don't forget to remove the pins). Normally it should work fine with the latest cmdliner.

**Comment by Danl2620** [comment]
Yeah, my opam pins are removed, and cmdliner isn't the problem any more. Installing irmin-unix.1.0.1 yields the same error as my 2nd post... with mismatched type of `Irmin_watcher.hook`.

**Comment by samoht** [comment]
What does `opam list` give you?

**Comment by bbc2** [comment]
Maybe this can help.  The error seems to show up with `irmin-watcher.0.1.4` but not `irmin-watcher.0.2.0`. The interface of `hook` changed between those versions: https://github.com/samoht/irmin-watcher/compare/0.1.4...0.2.0#diff-8ff6e9fd0382333475707185e6fa1336R72.

**Comment by samoht** [comment]
Yes, that's indeed the cause of the error: there is a missing version constraint in irmin-unix, I'll add it.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/8760 and https://github.com/mirage/irmin/pull/428

**Comment by Danl2620** [comment]
That fixed it.
