### ISSUE TITLE
Build error: Unbound module Git.Mem

### ISSUE THREAD

**Issue by tiensonqin** [mirage/irmin#448]
OS: Debian GNU/Linux 8.7 (jessie)
Ocaml: 4.04.0
 
➜  irmin git:(master) make                   
jbuilder build --dev
      ocamlc src/irmin-git/irmin_git.{cmo,cmt} (exit 2)
(cd _build/default && /home/tienson/.opam/4.04.0/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I /home/tienson/.opam/4.04.0/lib/astring -I /home/tienson/.opam/4.04.0/lib/bytes -I /home/tienson/.opam/4.04.0/lib/cstruct -I /home/tienson/.opam/4.04.0/lib/fmt -I /home/tienson/.opam/4.04.0/lib/git -I /home/tienson/.opam/4.04.0/lib/hex -I /home/tienson/.opam/4.04.0/lib/jsonm -I /home/tienson/.opam/4.04.0/lib/logs -I /home/tienson/.opam/4.04.0/lib/lwt -I /home/tienson/.opam/4.04.0/lib/mstruct -I /home/tienson/.opam/4.04.0/lib/ocaml -I /home/tienson/.opam/4.04.0/lib/ocamlgraph -I /home/tienson/.opam/4.04.0/lib/ocplib-endian -I /home/tienson/.opam/4.04.0/lib/re -I /home/tienson/.opam/4.04.0/lib/result -I /home/tienson/.opam/4.04.0/lib/sexplib -I /home/tienson/.opam/4.04.0/lib/sexplib/0 -I /home/tienson/.opam/4.04.0/lib/stringext -I /home/tienson/.opam/4.04.0/lib/uchar -I /home/tienson/.opam/4.04.0/lib/uri -I /home/tienson/.opam/4.04.0/lib/uutf -I src/irmin -no-alias-deps -I src/irmin-git -o src/irmin-git/irmin_git.cmo -c -impl src/irmin-git/irmin_git.ml)
File "src/irmin-git/irmin_git.ml", line 891, characters 21-33:
Error: Unbound module Git.Mem
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by samoht** [comment]
You need the latest version of ocaml-git (1.11.0, released at the end of last week) to make Irmin's master compile. I am closing the issue, but feel free to re-open if you have an other problem.
