### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by dudelson** [mirage/irmin#451]
While Irmin has a fair bit of documentation (already better than the majority of open-source projects), it seems a little bit scattered and patchy. As a newcomer to the project, I've found that understanding how Irmin works and how to use it requires a lot of jumping back and forth between docs, the wiki, blog posts, academic papers, etc. Therefore, this issue exists to discuss improvements that can be made to the documentation, by consolidating the documentation that already exists, improving that documentation where it needs work, and adding new documentation where it is needed. Here are some things that I think could be improved:

  - There aren't any introductions to Irmin for "general audiences" as far as I can find. That is, all of the existing soft documentation assumes that you're either an academic interested in mergeable data structures and CRDTs or a Mirage OS developer. 
  - The auto-generated API documentation could be a little more verbose. As a newcomer, it seems like the API docs assume the reader already has an overview of how Irmin works and how to fit individual pieces together to get a working store. However, aside from the examples, this context is not explicitly given anywhere. I think the examples would be easier to understand if they had more commentary on what some of the more important lines did and why they were being used.
  - There is no information on how to contribute to the project. This includes information on how to build the project and its documentation, good starting tasks for new contributors, and relevant project guidelines for contributors.
  - The wiki has not been updated since before the 1.0 release, and the "getting started" example appears to be both incomplete and out of date.

I hope to address many of these issues myself in various ways. For one, I am planning on writing a complete introduction to using Irmin for those that are new to both Ocaml and databases (like me). I am also open to updating the README and wiki myself, but if I am the one who does it it will take more time because (again) I'm still learning. As far as the API documentation goes, I don't know exactly how to improve it, but I think perhaps we can take [jbuilder's documentation](https://jbuilder.readthedocs.io/en/latest/index.html) as an example. I think it's the best documentation of an Ocaml library I've seen yet.

**Comment by samoht** [comment]
I am looking forward to read your improvements :-) Please keep us posted with your progress!

**Comment by dudelson** [comment]
Unfortunately I never got around to working on this 😞. I would like to return to it at some point in the future, but nothing is certain right now. Closing indefinitely.
