### ISSUE TITLE
Add Irmin.Type converter to concrete trees

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#478]
Concrete trees (http://mirage.github.io/irmin/irmin/Irmin/module-type-S/Tree/index.html#type-concrete) are a nice way to store tree-like structures in Irmin. It would be nice if we could add an API to read/write any OCaml value into a tree using automatic converters with lazy/read and writes. Maybe using lenses or something similar.

Not sure exactly how this will look but that's an interesting idea to investigate.

**Comment by maiste** [comment]
`Irmin.Store.Tree.Concrete` has a deriver.
