### ISSUE TITLE
Irmin.Type should be more careful when unmarshalling random data

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#483]
We should make sure the `decode_cstruct` doesn't try to allocate strings too big or other fancy operations which could make the runtime crash...

**Comment by samoht** [comment]
Related to #670 and #678

**Comment by CraigFe** [comment]
See [here](https://github.com/mirage/irmin/blob/2.2.0/src/irmin/type/type_binary.ml#L246) where we read a length header and immediately allocate that many bytes.

Related to discussion in https://github.com/mirage/irmin/pull/1030#discussion_r453359804 about failing more gracefully in that case.

**Comment by CraigFe** [comment]
Ported to https://github.com/mirage/repr/issues/7.
