### ISSUE TITLE
bad server version

### ISSUE THREAD

**Issue by joelburget** [mirage/irmin#499]
Following the getting started tutorial from the wiki, with a fresh install of `irmin`, I start my server (`irmin init -d -v -s mem`) and then try writing to it (`irmin write a/b foo`), but the write fails with `(Invalid_argument "bad server version: expecting 1.3.2, but got <none>")`. Would love advice how to fix.

**Comment by joelburget** [comment]
Similarly when following the tutorial in the README (note the readme specifies `set` when it should be `write`)

```
❯ irmin init

~/code/ocaml/irmin-mem
❯ irmin set food/bar "testing 123"
irmin: unknown command `set', did you mean `dot' ?
Usage: irmin COMMAND ...
Try `irmin --help' for more information.

~/code/ocaml/irmin-mem
❯ irmin write food/bar "testing 123"
(Invalid_argument "bad server version: expecting 1.3.2, but got <none>")
```

**Comment by joelburget** [comment]
Okay, this does work for me when I change my `.irminconfig` to be just `root=.`, following the instructions in the README. But not when I run a server, following the instructions from the getting started wiki.

**Comment by samoht** [comment]
@zshipko is just starting working on revamping the documentation which starts to be a bit outdated (as you might have discover). Sorry the current state and we hope to fix all of this very soon! Please keep sending us your feedback; newstarte's feedback is the most precious one :-)

**Comment by samoht** [comment]
You can see the new tutorial (which is still work in progress) here: https://zshipko.github.io/irmin-tutorial/

We are preparing a new release of irmin which should solve all your issues.
