### ISSUE TITLE
Read values from stdin

### ISSUE THREAD

**Issue by carlos-molina** [mirage/irmin#50]
I have notice that irmin can't store actual public keys unless you wrap them within " ".

1) You can see that irmin is ok with plain strings

cm770@pursuit2:~/local/irminsule/testing/irmin-mem$ irmin write person/pubKey 123abc
cm770@pursuit2:~/local/irminsule/testing/irmin-mem$ irmin tree
/person/name........................................................................................."carlos"
/person/nationality..............................................................................."universal"
/person/pubKey......................................................................................."123abc"
/person/surname......................................................................................"molina"

2) However, it can't handle actual public keys

cm770@pursuit2:~/local/irminsule/testing/irmin-mem$ irmin write person/pubKey ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvaRbn64jCX5Ne+FS4lmNNn+p+umx8/vcJ1+0oFF7oyXg55pFHJEBNhL0g8UXXzvuMdmFgHCBapAq9Efb4dUv45ffnoc5PQqYToO1Sy8eMSSxnVqI8oQeH81/yzgBelKiHVcLx5FNXyuBesIpvxd7VhrN4VZy2I1eWBE3EefmmfigQ9ISEeIHnIjyK6O922xPWkjiWmd83CAC6DGzCChC13Q6eFFArEgUmmNupm+A5Beu4qz6BkvP6xo0vJoOCI+WruWPsYhjxg13LE17LvSLmm1DQz2ghk25rRGPzNKVeJi7xy1LcM1i4vzIMJbTya9g86q5COvT5MqnIHvlbFi0GQ== carlos.molina@cl.cam.ac.uk
irmin: internal error, uncaught exception:
       (Failure "Too many arguments")

3) The prob goes away if yo wrap the key in between " ".

cm770@pursuit2:~/local/irminsule/testing/irmin-mem$ irmin write person/pubKey "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvaRbn64jCX5Ne+FS4lmNNn+p+umx8/vcJ1+0oFF7oyXg55pFHJEBNhL0g8UXXzvuMdmFgHCBapAq9Efb4dUv45ffnoc5PQqYToO1Sy8eMSSxnVqI8oQeH81/yzgBelKiHVcLx5FNXyuBesIpvxd7VhrN4VZy2I1eWBE3EefmmfigQ9ISEeIHnIjyK6O922xPWkjiWmd83CAC6DGzCChC13Q6eFFArEgUmmNupm+A5Beu4qz6BkvP6xo0vJoOCI+WruWPsYhjxg13LE17LvSLmm1DQz2ghk25rRGPzNKVeJi7xy1LcM1i4vzIMJbTya9g86q5COvT5MqnIHvlbFi0GQ== carlos.molina@cl.cam.ac.uk"

**Comment by samoht** [comment]
Closing as won't fix, as I stated above, this is the typical behaviour for CLI tools. The `irmin` CLI is also a toy, that I won't recommend using it for anything more than experimentations.
