### ISSUE TITLE
Use YAML for .irminconfig file

### ISSUE THREAD

**Issue by zshipko** [mirage/irmin#502]
Currently `.irminconfig` is using an encoding that is very similar to the INI format without headers. To avoid having a special format it seems like we should switch to something widely used, such as YAML.

The simplest way to do this would be to simply split on `:` instead of `=`, allow spaces between the key and colon and require a space between the colon and value.

For example, this:
```ini
root=.
```

becomes:
```yaml
root: .
```

This works because we are only using the configuration file as a mapping from string keys to string values, which would allow us to ignore YAML objects and arrays. This option would just require a few small changes to the `read_config_file` function in `ir_resolver.ml`.

An alternative to this idea would be to use [ocaml-yaml](https://github.com/avsm/ocaml-yaml), which seems like overkill at the moment, but may be worth it if we plan on expanding the configuration file.

Another alternative is to just leave it as-is.

What sounds like the best option here?

**Comment by rgrinberg** [comment]
Why not s-expressions? 😆

**Comment by samoht** [comment]
Using `ocaml-yaml` is probably best. We could imagine storing more complex things in there, like which merge strategies to use, etc.

> Why not s-expressions? 😆

Haha. No. :p

**Comment by samoht** [comment]
Also we should probably change the filename to something more sensible: `irmin.yml` would probably make more sense.

**Comment by avsm** [comment]
The only downside to ocaml-yaml is that it has C bindings, which mean that it cannot be a dependency of the core of Irmin (which must compile to Mirage or JavaScript).  However, the ini parsing sounds like something that would happen in Irmin_unix or some other platform-dependent place, so this shouldn't be a huge deal I hope.

**Comment by samoht** [comment]
Yes, we are indeed discussing on improving the CLI here, so it will leave in `irmin-unix`. I think that's fine to use as many Unix goodies as possible here :-)
