### ISSUE TITLE
Command line flags + irmin.yml

### ISSUE THREAD

**Issue by zshipko** [mirage/irmin#510]
How should we handle the case when there is an `irmin.yml` file present in addition to command-line flags passed that may overwrite those specified in the config file?

Currently we only use the configuration specified in `irmin.yml` and silently ignore the command-line flags, but that seems incorrect to me.

For some options it makes sense to allow them to be overwritten - for example, it is nice to be able to set the `branch` flag from the command-line even when using a config file.  This is also somewhat true for `uri` and `head` flags. 

It doesn't make much sense to allow some of the other flags to be overwritten if they're present in the config file - things like `store`, `contents`, `bare`, `root`. However, I can see cases where you would want to temporarily change those as well. 

I think it would be best to allow any flag specified in `irmin.yml` to be overwritten by passing it to `irmin` on the command-line. What do you think?

**Comment by samoht** [comment]
Yes, I think the priority should always be:

1. the default parameters
2. the config file parameters
3. the command-line arguments

where each layer can overwrite the previous one.

**Comment by samoht** [comment]
Note: this scheme could be later extended with support for global config files (something like `~/.irmin/config.yml`) that could be added between 1. and 2.

**Comment by zshipko** [comment]
Sounds good. 

I will spend some time cleaning up the way that command line flags are handled. I also noticed a scenario where the `--uri` flag is getting confused with the `--address` flag, so it seems like this area could use some attention.

**Comment by zshipko** [comment]
Actually, it looks like it was my mistake with the `--uri` and `--address` flags but I will still take a look at that stuff.
