### ISSUE TITLE
Parse error: result fied set in delta hunk

### ISSUE THREAD

**Issue by Ulrar** [mirage/irmin#528]
Hi,

I have no idea what I'm doing, and unfortunatly the documentation is light so I might be way off. But I feel like I've found a bug when trying to clone a remote git repo from mirage (compiled with the unix backend for now) : 

```ocaml
module Main
  (C: Mirage_types_lwt.CONSOLE)
  (RES: Resolver_lwt.S)
  (CON: Conduit_mirage.S) = struct

  let start console resolver (conduit:CON.t) =
    let (module Context) = Irmin_mirage.context (resolver, conduit) in
    let module GitMem = Irmin_mirage.Git.Mem.KV(Context)(Git.Inflate.None) in
    let module Store = GitMem(Irmin.Contents.String) in
    let module Sync = Irmin.Sync(Store) in
    let config = Irmin_mem.config () in
    let upstream = Irmin.remote_uri "https://github.com/Ulrar/test-irmin.git" in
    Store.Repo.v config >>= Store.master
    >>= fun t  -> Sync.pull_exn t upstream `Set
    >>= fun () -> Store.get t ["README.md"]
    >>= fun r  -> C.log console r
end
```

Running that I get : 
```
2018-07-08 17:49:43 +01:00: INF [tcpip-stack-socket] Manager: connect
2018-07-08 17:49:43 +01:00: INF [tcpip-stack-socket] Manager: configuring
2018-07-08 17:49:46 +01:00: INF [git.sync] remote: Counting objects: 3, done.
2018-07-08 17:49:46 +01:00: INF [git.sync] remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
2018-07-08 17:49:46 +01:00: INF [git.sync] Received a pack file of 226 bytes.
Parse error: result fied set in delta hunk
2018-07-08 17:49:46 +01:00: ERR [application] main: Mstruct.Parse_error("result fied set in delta hunk")
Raised at file "map.ml", line 122, characters 10-25
Called from file "src/core/lwt.ml", line 817, characters 20-60
```

Seems like there is at least a typo (I assume it's field and not fied), and maybe even a bug since the same code using Irmin-unix seems to work fine. Unless irmin-mirage is supposed to be used another way, I'm piecing it together by reading Canopy's sources and reading [the doc](https://mirage.github.io/irmin/), but a lot of it is magic to me so I might just be doing it wrong.
I most uncertain about Git.Inflate.None, maybe I'm supposed to use something else there, I saw a few issues mentionning it but everything got closed without any infos on what.

**Comment by Ulrar** [comment]
Well that's it, replacing Git.Inflate.None by Git.Inflate.M solves the issue. Although there is still a typo in the error, and at least another in the doc of ocaml-git ("Minimaal signature provided by Zlib.") but that's not the place for this.

**Comment by samoht** [comment]
The `sync` and `push` examples are now working fine on the master branch, thanks to the great work done by @dinosaure on ocaml-git. We are planning a new release pretty soon with the fixes.
