### ISSUE TITLE
Rename key (directory) in KV module

### ISSUE THREAD

**Issue by Ulrar** [mirage/irmin#533]
Hi,

I'm wondering how to rename a file or directory when using Irmin_mirage.Git.Mem.KV. I suppose there's always to option of reading every subfile and writing them to the new location manually, then removing the old ones, but is there a better way to do it ? I imagine that might be what with_tree is for, but I don't really understand how to use it.

```
with_tree t k ~info f replaces atomically the subtree v under k in the store t by the contents of the tree f v, using the commit info info ().
```

Any chance there's an example somewhere I missed ? I guess I must provide a function that would iterate on v, and just change the key associated with the directory I want to rename, somehow ?
Thanks

**Comment by Ulrar** [comment]
Okay I managed to get it to work by adapting the blog's example I found [https://mirage.io/blog/irmin-1.0](there). That code doesn't seem to be valid anymore, but after adding some match it works : 

```ocaml
let renameDir dir oldName newName =
  store () >>= fun t ->
    let info = makeInfo "renaming" in
    Store.with_tree ~info t dir
      (fun mt -> match mt with
        | None      -> Lwt.return_none
        | Some tree ->
          Store.Tree.find_tree tree [oldName]
          >>= fun v  -> match v with
            | None    -> Lwt.return_none
            | Some nt ->
              Store.Tree.remove tree [oldName]
              >>= fun tree -> Store.Tree.add_tree tree [newName] nt
              >>= Lwt.return_some
      )

```

**Comment by samoht** [comment]
Sorry about this, the blog example was fixed by @zshipko in https://github.com/mirage/mirage-www/pull/614
