### ISSUE TITLE
Sync.pull_exn fails on repeated invocation

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#594]
Invoking `Sync.pull_exn` repeatedly on the same remote throws the fairly unhelpful exception `Invalid_argument "Sync.pull_exn: XXX"`. This seems like unintended behaviour.

Minimal working example here:
```
open Lwt.Infix

module Store = Irmin_unix.Git.FS.KV(Irmin.Contents.String)
module Sync = Irmin.Sync(Store)

let () =
  let lwt =
    Store.remote "https://github.com/mirage/irmin"
    |> fun upstr -> Store.Repo.v (Irmin_git.config ~bare:false "/tmp/irminmwe")
    >>= fun repo -> Store.master repo

    >>= fun master -> begin
      Printf.printf "Beginning pull #1\n";
      Sync.pull_exn master upstr `Set
    end

    >>= fun _ -> begin
      Printf.printf "Beginning pull #2\n";

      (* Fatal error: exception (Invalid_argument "Sync.pull_exn: XXX") *)
      Sync.pull_exn master upstr `Set
    end
  in Lwt_main.run lwt
```

This gives the following output:
```
Beginning pull #1
Beginning pull #2
Fatal error: exception (Invalid_argument "Sync.pull_exn: XXX")
```

**Comment by zshipko** [comment]
This seems to be the source of the problem: https://github.com/mirage/irmin/blob/97ac4202ad113aa80e7bb13fd2d3a3619e38d044/src/irmin-git/irmin_git.ml#L715

@samoht, what hash are you talking about in the comment there?

**Comment by samoht** [comment]
This error is indeed very strange! Not totally sure why I meant, but I guess we just need to return the current commit hash for the reference.
