### ISSUE TITLE
Sync.pull_exn fails with Invalid_argument exception when called twice on two different brances

### ISSUE THREAD

**Issue by zshipko** [mirage/irmin#600]
I discovered this when writing tests for `irmin-graphql`, but the issue can be easily reproduced:

```ocaml
module Store = Irmin_unix.Git.FS.KV(Irmin.Contents.String)
module Sync = Irmin.Sync(Store)
let cfg = Irmin_git.config "./tmp-store"
let origin = "git://github.com/mirage/irmin"

open Lwt.Infix
let main =
  Store.Repo.v cfg >>= fun repo -> Store.of_branch repo "gh-pages" >>= fun gh_pages ->
  Store.master repo >>= fun t ->
  Sync.pull_exn t (Store.remote origin) `Set >>= fun () ->
  Lwt_io.printl "Pulled master" >>= fun () ->
  Sync.pull_exn gh_pages (Store.remote origin) `Set >>= fun () ->
  Lwt_io.printl "Pulled gh-pages"

let () = Lwt_main.run main
```

Which fails with the following error:
```
Fatal error: exception (Invalid_argument
  "Sync.pull_exn: {`Smart (`No_assert_predicate #predicate)}")
```

/cc @dinosaure, since this seems like it is probably an `ocaml-git` issue

**Comment by dinosaure** [comment]
Indeed, I will investigate why we have this.

**Comment by dinosaure** [comment]
Ok the bug definitely comes from `ocaml-git` on the negotiation engine which does not expect much more noticed commits when it sends the `done` status. I forked `irmin` to keep the current state of the git repository. However, this bug will take a long time to be fixed when we don't have any documentation about negotiation/smart protocol in Git. Thanks for your report.

**Comment by samoht** [comment]
I'm closing this as mirage/ocaml-git#338 has been merged.
