### ISSUE TITLE
irmin 2.0.0 and mirageos (freestanding)

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#632]
hi,

I wanted to re-deploy [Canopy](https://github.com/Engil/Canopy) with this shiny new irmin from master (f0cfeb8265d657f3f6aa70ae324225372839a253), turns out actually the kv-ng branch (I rebased #559 it at https://github.com/hannesm/irmin/tree/ro-ng-rebased).

I ran into multiple issues:

1. irmin-graphql requires the `Str` module, which is not available on MirageOS freestanding (I removed in https://github.com/hannesm/irmin/commit/ae59d9793544e653a9fa49372e82915421016429 the graphql from irmin-mirage). This module is used in graphql_parser (see https://github.com/andreas/ocaml-graphql-server/blob/master/graphql_parser/src/dune#L10, AFAICT there is only a small code segment (graphql_parser/src/ast.ml) which could instead use [re](https://github.com/ocaml/ocaml-re) or [astring](https://erratique.ch/software/astring/doc/Astring.String.html) (//cc @andreas)

2. I ran into a runtime (initialization time) issue because irmin-git calls out to `Sys.getcwd ()` which aborts in solo5. https://github.com/hannesm/irmin/commit/26ba030dc00f55169e18e528703337211ccb570f -- I've no idea what the proper solution is, but the call shouldn't be there ;)

3. When I then started Canopy, it pulled the remote repository, but couldn't find any data in there. Did the semantics of `Store.Repo.v store_config` change? I now added some mutable state in canopy_store, otherwise the `store ()` function would not return something where there is actual data -- please see https://github.com/hannesm/Canopy/commit/104546c97b85eb62bd90e98259679f5b6b9e8f74 what I did.

Thanks for your work on this, I'll hopefully tomorrow try CalDAV and will report success/failure.

**Comment by andreas** [comment]
@hannesm Thanks for pointing this out! I'm replacing `Str` with `Re` in `graphql_parser` here: https://github.com/andreas/ocaml-graphql-server/pull/144

**Comment by andreas** [comment]
I'll update `irmin-graphql` to depend on `graphql_parser.0.11.0` when it's ready (https://github.com/ocaml/opam-repository/pull/13577).

**Comment by hannesm** [comment]
this issue has been resolved. further discussion in #658

**Comment by hannesm** [comment]
the issue still left seems to be that the Canopy branch targeting irmin 2 works only on unix, but fails freestanding since it can't find `.config/uuid` (i.e. the `store` disappeared), see comments around https://github.com/mirage/irmin/issues/658#issuecomment-475448609
