### ISSUE TITLE
Irmin_unix.Git.Mem.KV backend's pull/fetch operation always returns an error

### ISSUE THREAD

**Issue by gowthamk** [mirage/irmin#634]
Hi,

As per my understanding, we can seamlessly switch between `FS` and `Mem` backends, and things should work just fine. However, that doesn't seem to be the case. I have a setup with two docker nodes that try to synchronize via `git+ssh` (the respective uri's I use are `git+ssh://opam@172.18.0.2/tmp/repos/foo.git` and `git+ssh://opam@172.18.0.3/tmp/repos/foo.git`). The setup works fine as long as I use `Irmin_unix.Git.FS.KV` backend, but I get the following error as soon as I switch to `Irmin_unix.Git.Mem.KV` backend:

```
Pulling from git+ssh://opam@172.18.0.3:/tmp/repos/canvas.git#master 
Fatal error: exception (Failure 
  "The connection has been closed by the server. This is usually due to an invalid client request.")
```

What am I missing here?

**Comment by kayceesrk** [comment]
I'd assumed `sync` would work out on any backend. Perhaps not so?

**Comment by samoht** [comment]
Which version of Irmin are you using?

**Comment by gowthamk** [comment]
@samoht This is with 1.4.

**Comment by samoht** [comment]
You should use Irmin 2.0 and ocaml-git 2.0.

**Comment by gowthamk** [comment]
Is Irmin 2.0 release avalable? I couldn't find it on github or opam. If you meant the dev version, I tried it a month back and ran into dependency issues. Here is an excerpt from my notes from back then:

> git-unix.2.0, git.2.0, and irmin-unix dev version are incompatible. Git_unix.Fs (from git-unix.2.0) doesn’t match Git.S signature (from git.2.0) required by the argument to Content_addressable functor (from irmin_unix dev version). 

Maybe these issues are resolved, or maybe I was using incorrect versions. It would be great If you could suggest the versions/commits of Irmin and Git packages to use. Thanks!

**Comment by samoht** [comment]
I'm closing this issue as it applies to irmin 1.4. Feel free to re-open if you have the same error with irmin 2.0.
