### ISSUE TITLE
Store.History.is_empty returns true with one value stored in the graph

### ISSUE THREAD

**Issue by aweis** [mirage/irmin#681]
The following gist:

https://gist.github.com/aweis/883322662f7c874b38e1b352314e7a5c

prints the following:

```
0. is the history empty? true
setting [a,b,c]
data at [a,b,c] is Message 1
1. is the history empty? true
setting [a,b,d]
data at [a,b,c] is Message 1
data at [a,b,d] is Message 2
2. is the history empty? false
```

I was surprised that a single item in the history still meant that the history was empty.  Is this intended behavior?

**Comment by aweis** [comment]
http://mathworld.wolfram.com/EmptyGraph.html

Is this because the singleton graph is considered empty?  This is unfortunate because I would expect a commit history of 1 commit to be not empty

**Comment by samoht** [comment]
It's indeed surprising. I'll try to dig a bit to understand what happens.

**Comment by avsm** [comment]
Linking in some context here to @aweis' irmin-web browser prototype https://github.com/mirage/irmin/issues/677#issuecomment-489877072

**Comment by samoht** [comment]
@zshipko did you manage to reproduce / fix?

**Comment by zshipko** [comment]
I was able to reproduce this, but wasn't able to fix it since it seems to come from `ocamlgraph`.

**Comment by pascutto** [comment]
The issue was in our implementation, it is now fixed.
