### ISSUE TITLE
split up irmin-mirage opam package into several opam packages

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#685]
as suggested in #658 somewhere, I'd be in favour of splitting up the irmin-mirage opam package. I'd envision three packages at the moment:
- irmin-mirage -- the core
- irmin-mirage-graphql -- graphql adapter (depending on cohttp etc.)
- irmin-mirage-git -- depending on the git implementation

a fourth one, irmin-mirage-wodan, would be welcome as well once the irmin-wodan integration is ready.

the reasoning behind this is not only binary size, but also to minimize the dependency cone. I like my unikernels where no http code is inside ;)

the split should be fairly straightforward to do since the code is independent. please consider this for a 2.0 release. thanks!

**Comment by avsm** [comment]
This sounds very reasonable to me, and definitely good to do for 2.0 so we don't have to do rearrangement down the line.  Putting it towards the 2.0 milestone.

**Comment by zshipko** [comment]
I've just opened a PR for this here: https://github.com/mirage/irmin/pull/686

Most of the stuff in `irmin-mirage` was git related, so this change means that `irmin-mirage` will only contain the `Info` functor. This makes `irmin-mirage` extremely lightweight if you're only interested in working with `irmin-mem` + mirage.
