### ISSUE TITLE
Irmin uses SHA-1 by default in many places

### ISSUE THREAD

**Issue by emillon** [mirage/irmin#727]
Hi,

Irmin provides shortcuts like `Irmin_mem.KV` where parameters like the hash function is already specified. In these cases, SHA1 is used by default.

[There are now collisions on SHA1](https://shattered.io/) - this is not only a theoretical consideration. I understand that this is the breaking change, but I believe that we should change that default for Irmin 2.0.

What do you think?

Thanks!

**Comment by samoht** [comment]
Yes, that's a good idea. The only backend where we should keep this the default is obviously `irmin-git` (otherwise we loose interoperability).

And we should pick `blake2b` as the new default.

**Comment by CraigFe** [comment]
`blake2b` seems like a sensible default to me, but I'm no crypto expert.

If we're still interested in getting this in for Irmin 2.0 (and can agree on a hash function), I'll try to get a PR together before the release is cut.

**Comment by samoht** [comment]
@CraigFe that sounds like a good idea!

**Comment by emillon** [comment]
Blake2b or SHA256 are fine defaults.

**Comment by samoht** [comment]
Fixed by #811
