### ISSUE TITLE
Bitv is LGPLv2

### ISSUE THREAD

**Issue by emillon** [mirage/irmin#729]
Hi,

`Bitv` in `src/irmin-pack/bitv.ml{,i}` is licensed under LGPLv2 + exception. LICENSE only mentions ISC. Also, `Bitv` is on opam, so it might be worth depending on it instead.

Thanks!

**Comment by samoht** [comment]
/cc @pascutto 

We can actually just depends on https://github.com/mirage/bloomf now that we are happy with the current implementation.

**Comment by pascutto** [comment]
Sure, I can make a release before the end of the week, I'd like to try resizability before that.

**Comment by samoht** [comment]
Yes sure, nothing urgent -- this could could be removed at one point but it's fine to keep it around here as long as it is convenient.
