### ISSUE TITLE
Documentation on JSON CRUD interface

### ISSUE THREAD

**Issue by sgrove** [mirage/irmin#80]
I'm interested in using Irmin other languages (Clojure and ClojureScript, specifically) via the JSON CRUD interface.

The only documentation I can find on the JSON CRUD interface is a single GET statement - it'd be great to see the other API endpoints have a bit of documentation with (or just) an example payload/CURL line, ideally linking to the source where the endpoint is implemented. I looked through the source a bit, but I've never worked with OCaml, so couldn't quite pin down the shape of the data I should use.

**Comment by samoht** [comment]
A very rough documentation is available here: https://github.com/mirage/irmin/wiki/REST-API

**Comment by samoht** [comment]
Irmin 1.0 does not expose a high-level REST API anymore (only a low-level API used by the backends) so I will close this.

Designing a nice and consistent REST/CRUD API is out-of-scope for 1.0 and is best done and specialised case-by-case by applications using Irmin. For instance, I plan to provide that a high-level CRUD API to [datakit](https://github.com/docker/datakit), using [webmachine](https://github.com/inhabitedtype/ocaml-webmachine)

Please let me know if the removal of the high-level API cause any issue.

**Comment by sgrove** [comment]
No, my original use-case was using Irmin from other languages, and I'm no longer concerned about that.

**Comment by Tails** [comment]
What is currently the status of the REST API? Are any of the methods mentioned here still available?

https://github.com/dudelson/irmin/blob/6b9794ecae7c3d4b0b834b2a3a5bc807babf0166/src/irmin-http/swagger.yml
