### ISSUE TITLE
improve debug messages (or remove them?) from irmin-git

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#816]
I see `fetch result: XXX` quite a lot of times when using irmin and git, it would be great to improve this fixme (maybe git now provides a decent pretty-printer?).

this issue has been copied from https://github.com/mirage/irmin/issues/755#issuecomment-508081538 for your convenience (to not conflate different things in a single issue).

`src/irmin-git/irmin_git.ml` contains some debug messages which are not very useful:
```OCaml
    let result refs =
      (* FIXME: need pp_result *)
      Log.debug (fun f ->
          f "fetch result: XXX" (* Git.Sync.Result.pp_fetch r *) );
      let key =
        try Some (G.Reference.Map.find reference refs) with Not_found -> None
      in
```

thanks for reading

**Comment by samoht** [comment]
Good catch :-) We should definitely fix these, and any PR to use the new API is welcome :-)

**Comment by hannesm** [comment]
I am not sure what "use the new API" means tbh.

**Comment by samoht** [comment]
hum yes sorry, I was confused with the new API exposed by #789. I'm not sure `pp_fetch` is exposed properly in Git 2.1. need to check with @dinosaure when he's back.

**Comment by pascutto** [comment]
@dinosaure do you have any insights about this?

**Comment by dinosaure** [comment]
Not yet, but I can provide something.
