### ISSUE TITLE
Allow backends to inline small objects

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#884]
It would be nice if we could propagate more information to the backends, so that they could decide to inline small objects if they deemed it necessary.

This would mean that some objects would not be addressable directly but in most use-cases that's fine.

**Comment by CraigFe** [comment]
This is now possible by using structured keys, as demonstrated in [this test case](https://github.com/mirage/irmin/blob/main/test/irmin/generic-key/test_inlined_contents.ml). Closing, and we can open a follow-up issue to leverage this in `irmin-pack` if necessary.
