### ISSUE TITLE
irmin-pack: add an option to force fsync on flush

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#886]
Similar to https://github.com/mirage/index/issues/126

**Comment by samoht** [comment]
Now that #1010 is merged, we should be using fsync too. /cc @CraigFe

**Comment by CraigFe** [comment]
Not strictly the same, but there was some discussion of `fsync`-ing as part of `irmin-pack` here: https://github.com/mirage/irmin/pull/1008#discussion_r446893653.

It still makes sense to provide `fsync` as an opt-in.

**Comment by samoht** [comment]
Do we still need this? /cc @icristescu and @CraigFe

**Comment by samoht** [comment]
Closing this as it doesn't seem necessary.
