### ISSUE TITLE
Not all file descriptors are getting closed

### ISSUE THREAD

**Issue by ssdubey** [mirage/irmin#891]
I am trying to integrate Cassandra as a backend to Irmin. Upon running the Irmin-tests I have noticed that each test case opens about 8 sessions (running `config` 8 times), but closing only 4 of them. As a result, I am able to run only 10 test cases at a time (any 10), and 11th one is unable to create a new session. 
I understand that all the sessions created by a test case should be closed upon exit. Can you please look into the issue, or let me know if I am missing something here.

**Comment by samoht** [comment]
Fixed by #892
