### ISSUE TITLE
CLI: add an option to check the consistency of a repository

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#902]
I think irmin-pack already exposes a `check` function, so this should probably be exposed in the main API first. Once this is done, the CLI could use this to perform statistics/integrity checking on the repository objects.

**Comment by CraigFe** [comment]
Do you have a feeling for what we might want the type of the `check` function to be?

- Should it be a `Store.t Fmt.t`?
- Should it return a value that can be introspected? If so, should each backend define its own type for 'integrity check statistics'?

**Comment by samoht** [comment]
No strong opinion, but should be able to distinguish the status (ok / error) and message/stats info (which can be printed in both cases).

**Comment by samoht** [comment]
I think this is done now? /cc @icristescu and @CraigFe

**Comment by CraigFe** [comment]
That depends on your interpretation: we haven't got anything hooked into the `irmin` CLI specifically, which is what I interpreted this issue being about. We do have easy hooks for building one's own binaries with consistency checks on an `irmin-pack` store, which seems good enough for now.

**Comment by samoht** [comment]
It's already in the Tezos branch (integrated in the `tezos-node storage` sub-command) so closing.
