### ISSUE TITLE
performance of last_modified

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#933]
hello,

in a scenario with ~2500 commits, where each commit *N* created two files (`foo/a`*N* and `foo/b`*N* -- i.e. all in the same directory), when I iterate over the directory and call `last_modified <store> "foo/a*N*"`, I see a massive amount of computation (99%) done in `last_modified` (pls find attached landmarks output), leading to an overall processing time of ~76 seconds (which is not acceptable for a HTTP request). Replacing the call to last_modified by a constant value (Ptime.epoch), the response time is reduced to sub-second.

I don't quite understand the implementation of `last_modified`, but is there a chance to use a different approach to speed it up by a factor of ~300? In the meantime, I can as well revert to not use irmin's last_modified, but store a last_modified timestamp as data.

![irmin-last-modified](https://user-images.githubusercontent.com/228456/73441965-3a246900-4354-11ea-9b70-1e186b3e6330.png)

**Comment by samoht** [comment]
I though @pascutto fixed this in #617 -- maybe we haven't pushed that through the Mirage implementations?

**Comment by hannesm** [comment]
@samoht #617 is active here -- I'm using https://github.com/mirage/irmin/blob/29b197f8ae4c77238965333a733277e097d00e7f/src/irmin-mirage/git/irmin_mirage_git.ml#L170-L174 which calls https://github.com/mirage/irmin/blob/29b197f8ae4c77238965333a733277e097d00e7f/src/irmin/store.ml#L992-L1032 (there's no updates to the code on master AFAICT).

according to landmarks, the expensive operation is `find` which is called multiple times in the `last_modified` implementation. Maybe for each commit, constructing a KV and checking whether the `key` is available is still rather expensive? As I said, I don't fully understand the current implementation of last_modified (as well I don't quite understand why it returns a commit list).

**Comment by pascutto** [comment]
> I don't quite understand why it returns a commit list

What return type would you expect instead?

I'm having a look at the performance issue, will report soon.

**Comment by hannesm** [comment]
`Ptime.t option` or `(Ptime.t, err) result` (i.e. a timestamp if the key exists, a failure/None if it does not exist).
