### ISSUE TITLE
Respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by CraigFe** [mirage/irmin#934]
The `irmin_unix` config currently sits in either `$HOME/.irmin/config.yml` or `$PWD/.irmin.yml`. 

It seems better to respect [`XDG_CONFIG_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as a location for this file.

The Dune source code contains an [internal XDG library](https://github.com/ocaml/dune/tree/master/src/xdg) that could be used as a starting point.

**Comment by wiml** [comment]
I haven't compared implementations, but https://opam.ocaml.org/packages/ocaml-xdg-basedir/ / https://github.com/gildor478/ocaml-xdg-basedir might also be a starting point.
