### ISSUE TITLE
Equivalent of `val Irmin.Hash.SHA1.t` in version 2.0?

### ISSUE THREAD

**Issue by njayinthehouse** [mirage/irmin#937]
I have some code that's dependent on Irmin1.4, which uses the `Irmin.Hash.SHA1` module. To my understanding, most of the functionality of that module moved to `Irmin_git.Mem.Hash` in Irmin2.0. However, there exists in version 1.4 the very convenient `val t` in `Irmin.Hash.SHA1`, that represents the 'Irmin type' of SHA1 hashes (defined via the types in `Irmin.Type`). I see that there exists no `val Irmin_git.Mem.Hash.t` in version 2.0. Is there any value in `Irmin_git.Mem.Hash` that can get me the 'Irmin type'? If not, is there a straightforward way to construct the 'Irmin type' from the type combinators in the `Irmin.Type` module?

**Comment by pascutto** [comment]
Hi!
Maybe I got it wrong, but `Irmin.Hash.SHA1` still exists in irmin.2.0.0, with a `val t : t Type.t` in it.
https://mirage.github.io/irmin/irmin/Irmin/Hash/SHA1/index.html

**Comment by njayinthehouse** [comment]
I see that you're right. Unfortunately, I still have some problems specific to my program; in Irmin1.4, in order to create an append-only store, I have `module S = Irmin_git.AO (Git_unix.Mem) (AO_value)`, where `AO_value` is defined in my code. In Irmin2.0, `Irmin_git.AO` becomes [`Irmin.Content_addressable`](https://mirage.github.io/irmin/irmin-git/Irmin_git/Content_addressable/index.html), if I'm not wrong; however, module `Git_unix.Mem` no longer exists in current versions, so I'm not sure what backend to use. I need a backend such that `Irmin.Hash.SHA1.t = S.key` if I use the `Irmin.Hash.SHA1` module.

**Comment by pascutto** [comment]
I think you can use `Irmin_git.Mem` instead.
See https://mirage.github.io/irmin/irmin-git/Irmin_git/Mem/index.html

**Comment by CraigFe** [comment]
Indeed, something like
```ocaml
module S = Irmin_git.Content_addressable (Irmin_git.Mem) (AO_value)
```
should work fine. `Irmin_git.Mem` exposes the hash type you need: https://github.com/mirage/irmin/blob/master/src/irmin-git/irmin_git.mli#L61.
