### ISSUE TITLE
Cannot install version 2.0

### ISSUE THREAD

**Issue by senorsmile** [mirage/irmin#949]
I would like to try out Irmin 2.0.  I installed opam last year for another tool, and I suspect that is somehow causing issues.  I have never actually written OCaml, so I don't really know what I'm doing. 

I installed via `opam install irmin-unix`.

I saw on the 2.0 release page: 
`opam update && opam info irmin -f version`

That gives me: 
```
=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org/1.2.2
1.4.0
```

That should be 2.0.0 right?  

I also tried `opam upgrade` to no avail.

**Comment by avsm** [comment]
Looks like you have opam 1.2 installed. Try upgrading to opam 2.0 or higher and retrying.

**Comment by senorsmile** [comment]
Thank you, that was definitely the problem.  I upgraded opam and 2.0 is now available.
