### ISSUE TITLE
Semantics for using Make functors twice

### ISSUE THREAD

**Issue by icristescu** [mirage/irmin#950]
Some backends guarantee that stores created on different calls to the "same" `Make` functor are distinct:
```ocaml  
module Store1 = Irmin_mem.KV (Irmin.Contents.String)
module Store2 = Irmin_mem.KV (Irmin.Contents.String)

let main () =
  Store1.Repo.v config >>= fun repo ->
  Store1.master repo >>= fun t ->
  Store1.set_exn t [ "a"; "b"; "c" ] "Hello" ~info:(info "commit")
  >>= fun () ->
  Store1.get t [ "a"; "b"; "c" ] >>= fun s ->
  assert (s = "Hello");
  Lwt.return_unit >>= fun () ->
  Store2.Repo.v config >>= fun repo ->
  Store2.master repo >>= fun t ->
  Store2.get t [ "a"; "b"; "c" ] >|= fun s ->
  assert (s = "Hello")
  (*Fatal error: exception (Invalid_argument "Irmin.Tree.get: /a/b/c not found")*)
  ```
while other backends identify stores if they are using the same root directory: 
```ocaml
module Store1 = Irmin_unix.Git.FS.KV (Irmin.Contents.String)
module Store2 = Irmin_unix.Git.FS.KV (Irmin.Contents.String)

let root = "/tmp/irmin/test"
let main () =
  let config = Irmin_git.config ~bare:true root in
  Store1.Repo.v config >>= fun repo ->
  ...
  Store2.Repo.v config >>= fun repo ->
  ...
```
where the `main` function above succeeds.

Irmin-pack is somewhere in between: it identifies two stores based on their root but only if constructed with the same Make. If the two stores are created on different calls to Make:
```Ocaml 
module Store1 = Irmin_pack.Make (Conf) (M) (Irmin.Contents.String) (P) (B) (H)
module Store2 = Irmin_pack.Make (Conf) (M) (Irmin.Contents.String) (P) (B) (H)
```
then the `main` function only succeeds if `Store2` is opened in readonly: 
```ocaml
Store2.Repo.v (config ~readonly:true ~fresh:false ()) >>= fun repo ->
``` 
or if we close `Store1` before opening `Store2`. 
This issue is related to [index](https://github.com/mirage/index) but I opened it here to compare with other backends. 
I think this behaviour is confusing and we should at least document it.

**Comment by pascutto** [comment]
I don't think the `irmin-mem` documentation guarantees anything about multiple calls to `Make`.
IMO we should stick to what we discussed last time, i.e. not provide any guarantees when it comes to double instantiation of `Make`, this can be undefined behaviour (for now at least).

**Comment by CraigFe** [comment]
I'm confused by the wording of

> Some backends guarantee that stores created on different calls to the "same" `Make` functor are distinct

The `Make` functor doesn't instantiate stores, it instantiates a set of functions to be used for manipulating stores. In the `Irmin_mem` and `Irmin_unix.Git` cases, one can interchange `Store1` and `Store2` freely and get the same result. I don't think this is a good comparison to the sort of behaviour exhibited by `Irmin_pack`.

I think the implicit sharing in `Irmin_pack` is unpleasant, but perhaps best left as (explicitly documented) undefined behaviour unless we are willing to refactor for a more explicit sharing scheme.

**Comment by icristescu** [comment]
closing this as we don’t make any guarantees about sharing for Make functors
