### ISSUE TITLE
link back to irmin.org

### ISSUE THREAD

**Issue by srenatus** [mirage/irmin#971]
Heya!

This is a bit of a silly issue, but I'd think the Github banner could use a link to https://irmin.org, since there's a nice page there nowadays. 😄 

(I mean this bit: 
![image](https://user-images.githubusercontent.com/870638/76991440-e0025600-6949-11ea-8b80-4b7adc401269.png)
)

**Comment by avsm** [comment]
That's an excellent thought, thank you! I've added that to the project banner now.
