### ISSUE TITLE
installed irmin-unix using opam but it says command not found

### ISSUE THREAD

**Issue by sahanakk** [mirage/irmin#980]
I have installed irmin but it says command not found .

    sahana@sahana-HP-ProBook-440-G4:~/work/irmin_ocaml$ irmin
    irmin: command not found   
 
    
    sahana@sahana-HP-ProBook-440-G4:~/work/irmin_ocaml$ opam install irmin-unix
    The following actions will be performed:
      - install irmin      0.12.0                           [required by irmin-unix]
      - install irmin-unix 0.12.0
    ===== 2 to install =====
    Do you want to continue ? [Y/n] y

    =-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    [irmin] Archive in cache

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    -> installed irmin.0.12.0
    -> installed irmin-unix.0.12.0
    Done.

    sahana@sahana-HP-ProBook-440-G4:~/work/irmin_ocaml$ irmin-unix help
    irmin-unix: command not found

    sahana@sahana-HP-ProBook-440-G4:~/work/irmin_ocaml$ which irmin

    sahana@sahana-HP-ProBook-440-G4:~/work/irmin_ocaml$ irmin help
    irmin: command not found

**Comment by CraigFe** [comment]
Are you sure that Opam-installed binaries are in your `PATH`? (with `eval $(opam env)`)

What is the result of `opam exec irmin help`?

**Comment by pascutto** [comment]
> ```
> -> installed irmin.0.12.0
> -> installed irmin-unix.0.12.0
> ```

You opam installed a _very_ old version of irmin. 
Can you try `opam update` then `opam install irmin-unix.2.1.0`, to install the latest version?

**Comment by CraigFe** [comment]
Good spot. You may also be using an Opam `1.x` version, in which case you probably want to upgrade to Opam `2.x` to access Irmin 2.0+.

**Comment by sahanakk** [comment]
yes the opam version is 1.2.2 .  I tried "opam update" but the version is still 1.2.2

**Comment by sahanakk** [comment]
For the "opam exec irmin help" and "opam env" it says exec and env command not found.

**Comment by CraigFe** [comment]
> yes the opam version is 1.2.2 . I tried "opam update" but the version is still 1.2.2

`opam update` updates the repository metadata, not opam itself. For that, you'll need to follow https://opam.ocaml.org/doc/Install.html#Upgrading-from-a-previous-version.

> For the "opam exec irmin help" and "opam env" it says exec and env command not found.

Yes, this will be because your Irmin version is from before the CLI was introduced. Try `opam upgrade irmin` (ideally after installing Opam 2.0, to get the latest Irmin version).

**Comment by sahanakk** [comment]
I have updated the opam version. But Now I am not able to update irmin.

    sahana@sahana-HP-ProBook-440-G4:~$ opam --version
    2.0.6 

    sahana@sahana-HP-ProBook-440-G4:~$ opam install irmin-unix
    [ERROR] irmin-unix unmet availability conditions, e.g. ocaml-version >=
            "4.01.0"

    sahana@sahana-HP-ProBook-440-G4:~$ ocaml -version
    The OCaml toplevel, version 4.02.3

    sahana@sahana-HP-ProBook-440-G4:~$ opam upgrade irmin
    [ERROR] irmin unmet availability conditions, e.g. ocaml-version >= "4.03.0"

    sahana@sahana-HP-ProBook-440-G4:~$ opam install irmin-unix.2.1.0
    [ERROR] Package irmin-unix has no version 2.1.0.

    sahana@sahana-HP-ProBook-440-G4:~$ opam install irmin-unix
    [ERROR] irmin-unix unmet availability conditions, e.g. ocaml-version >=
            "4.01.0"

**Comment by pascutto** [comment]
Apparently you also have a very old OCaml version, so that won't be compatible with irmin.
You can upgrade your OCaml version with `opam upgrade --unlock-base ocaml-base-compiler.4.09.1`, then you should be able to install it correctly.

**Comment by sahanakk** [comment]
Thanks @pascutto and @CraigFe
