### ISSUE TITLE
Could not install irmin-unix

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [mirage/irmin#981]
when I ran the command "opam install irmin-unix" to install irmin-unix
i was getting below error
**Error:**
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value
        (currently, it is set to 200.0 seconds).

I was tring to increase OPAMSOLVERTIMEOUT  time, but still i could not get any specific error.
Could you please help me ?
P.S: my system info 
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

and OPAM version - 2.0.4

**Comment by CraigFe** [comment]
My initial reaction is that this is probably an Opam issue and not an Irmin one; the solver shouldn't take > 200 seconds for a query as simple as that.

Can you post the output of `opam list` and `opam info irmin-unix`?

**Comment by samoht** [comment]
Can you also try with an explicit version number? E.g the solver will give you a more precise error message with `opam install irmin-unix.2.1.0`

**Comment by Keerthana-Jayakumaran** [comment]
> My initial reaction is that this is probably an Opam issue and not an Irmin one; the solver shouldn't take > 200 seconds for a query as simple as that.
> 
> Can you post the output of `opam list` and `opam info irmin-unix`?

opam list
# Packages matching: installed
# Name                   # Installed  # Synopsis
astring                  0.8.3        Alternative String module for OCaml
base-bigarray            base
base-bytes               base         Bytes library distributed with the OCaml c
base-ocamlbuild          base         OCamlbuild binary and libraries distribute
base-threads             base
base-unix                base
bin_prot                 113.33.03    A binary protocol generator
cmdliner                 1.0.2        Declarative definition of command line int
conf-m4                  1            Virtual package relying on m4
cppo                     1.6.5        Equivalent of the C preprocessor for OCaml
crunch                   1.4.1        Convert a filesystem into a static OCaml m
cstruct                  3.0.2        Access C-like structures directly from OCa
dune                     2.4.0        Fast, portable, and opinionated build syst
ezjsonm                  1.0.0        Simple interface on top of the Jsonm JSON 
fmt                      0.8.5        OCaml Format pretty-printer combinators
hex                      1.3.0        Library providing hexadecimal converters
jbuilder                 1.0+beta20.2 Fast, portable and opinionated build syste
js-build-tools           113.33.04    Collection of tools to help building Jane 
jsonm                    1.0.1        Non-blocking streaming JSON codec for OCam
logs                     0.6.2        Logging infrastructure for OCaml
lwt                      4.2.1        Promises and event-driven I/O
mirage-tc                0.3.0        MirageOS type-classes
mmap                     1.1.0        File mapping functionality
mstruct                  1.4.0        A mutable interface to Cstruct buffers
ocaml                    4.02.3       The OCaml compiler (virtual package)
ocaml-config             1            OCaml Switch Configuration
ocaml-secondary-compiler 4.08.1       OCaml 4.08.1 Secondary Switch Compiler
ocaml-system             4.02.3       The OCaml compiler (system version, from o
ocamlbuild               0            Build system distributed with the OCaml co
ocamlfind                1.8.1        A library manager for OCaml
ocamlfind-secondary      1.8.1        ocamlfind support for ocaml-secondary-comp
ocamlgraph               1.8.8        A generic graph library for OCaml
ocplib-endian            1.1          Optimised functions to read and write int1
re                       1.9.0        RE is a regular expression library for OCa
result                   1.4          Compatibility Result module
seq                      0.2.2        Compatibility package for OCaml's standard
sexplib                  113.33.03    Library for serializing OCaml values to an
topkg                    1.0.0        The transitory OCaml software packager
uchar                    0.0.2        Compatibility library for OCaml's Uchar mo
uri                      1.3.12       RFC3986 URI/URL parsing library
uutf                     1.0.2        Non-blocking streaming Unicode codec for O
keerthana@keerthi-HP-EliteBook-745-G2:~$ opam info irmin-unix

<><> irmin-unix: information on all versions ><><><><><><><><><><><><><><><><><>
name         irmin-unix
all-versions 0.9.4  0.9.9  0.12.0  1.0.0  1.0.1  1.0.2  1.1.0  1.2.0  1.3.0  1.3.3  2.0.0  2.1.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version      2.1.0
repository   default
pin          git+file:///home/keerthana/projects/coldChain/IrminWorks/IrminGithub/irmin#master
source-hash  7ee44a96
url.src:     "git+file:///home/keerthana/projects/coldChain/IrminWorks/IrminGithub/irmin#master"
homepage:    "https://github.com/mirage/irmin"
bug-reports: "https://github.com/mirage/irmin/issues"
dev-repo:    "git+https://github.com/mirage/irmin.git"
authors:     "Thomas Gazagnaire" "Thomas Leonard"
maintainer:  "thomas@gazagnaire.org"
license:     "ISC"
depends:     "ocaml" {>= "4.01.0"}
             "dune" {>= "1.8.0"}
             "irmin" {>= "2.1.0"}
             "irmin-mem" {>= "2.0.0"}
             "irmin-git" {>= "2.0.0"}
             "irmin-http" {>= "2.0.0"}
             "irmin-fs" {>= "2.0.0"}
             "irmin-pack" {>= "2.0.0"}
             "irmin-graphql"
             "git-unix" {>= "1.11.4"}
             "digestif" {>= "0.6.1"}
             "irmin-watcher" {>= "0.2.0"}
             "yaml" {>= "0.1.0"}
             "irmin-test" {with-test & >= "2.0.0"}
synopsis     Unix backends for Irmin
description  `Irmin_unix` defines Unix backends (including Git and HTTP) for Irmin, as well
             as a very simple CLI tool (called `irmin`) to manipulate and inspect Irmin
             stores.

**Comment by Keerthana-Jayakumaran** [comment]
> Can you also try with an explicit version number? E.g the solver will give you a more precise error message with `opam install irmin-unix.2.1.0`

When I ran, 
` opam install irmin-unix.2.1.0`

I got below error.
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[irmin-unix.2.1.0] no changes from git+file:///home/keerthana/projects/coldChain/IrminWorks/IrminGithub/irmin#master

The following dependencies couldn't be met:
  - irmin-unix -> irmin >= 2.1.0
      not available because the package is pinned to version 0.12.0
No solution found, exiting


So i tried below one,
`opam install irmin-unix.2.1.0 --unlock-base`

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[irmin-unix.2.1.0] no changes from git+file:///home/keerthana/projects/coldChain/IrminWorks/IrminGithub/irmin#master

The following dependencies couldn't be met:
  - irmin-unix -> irmin >= 2.1.0
      not available because the package is pinned to version 0.12.0

No solution found, exiting

**Comment by samoht** [comment]
You need to unpin the existing version of irmin:

```
$ opam pin -s | grep mirage | xargs opam unpin
```

**Comment by avsm** [comment]
Your OCaml compiler version is too old:

```
ocaml                    4.02.3       The OCaml compiler (virtual package)
```

Try

```
opam switch create 4.09.0
eval $(opam env)
opam install irmin-unix
```

I agree that this is a terrible error message when you have a fresh install of Ubuntu (where the base compiler is 4.02.3).  We may be able to fix that by tweaking the older Irmin packages.

**Comment by Keerthana-Jayakumaran** [comment]
Than you so much for your time @CraigFe @samoht @avsm 
I used switch and install commands which is being shared by  @avsm .

**Comment by avsm** [comment]
Let's please keep this open until we can fix the documentation issue in the README. We should specify a check for the minimum OCaml version before the `opam install` instruction. This would be a excellent contribution if you'd like to do that @Keerthana-Jayakumaran :)

**Comment by Keerthana-Jayakumaran** [comment]
Yeah sure @avsm

**Comment by CraigFe** [comment]
I think the real problem here is the `opam` solve step stalling when no specific version is given. Does anyone know why this is the case?

@avsm: With our current CI setup, we're not asserting the minimal OCaml version we require anywhere, so adding this information to the README seems like tracking a moving target. Perhaps that's something that needs to be handled on the OCaml-CI side. (perhaps with an `mdx` solution for keeping the docs up-to-date...)

**Comment by samoht** [comment]
That target is now moving very often and it should be an explicit decision when we drop support for ancient versions. In that case, it seems fine to me to edit to README to reflect that choice.

**Comment by Keerthana-Jayakumaran** [comment]
Hi, Updated the read me file. Please review the same.
