### ISSUE TITLE
Extract an Irmin_cli package

### ISSUE THREAD

**Issue by craigfe** [mirage/irmin#983]
Currently, our CLI is provided by `irmin-unix`. To achieve this, it depends on all of the other backends.
 
- I find this unintuitive and _suspect_ that it's a point of confusion for newcomers;
- the Unix backend must share constraints with all of the other backends, which is difficult to reason about if we're not releasing packages in lock-step.

It should be fairly easy to extract an `irmin-cli` package from `irmin-unix` that handles this logic and allows the Unix backend to go back to having its 'true' dependencies.

**Comment by samoht** [comment]
That sounds like a very good idea to simplify the `irmin-unix` package.

One other solution would do to make `irmin` install a minimal CLI, an each backend could register "plugins" (and/or install a custom CLI).

**Comment by CraigFe** [comment]
Good thought. I've been bitten a few too many times by optional dependencies, but it seems to make sense here :slightly_smiling_face:

**Comment by adatario** [comment]
@clecat: Maybe relevant for your recent work on tooling.

**Comment by metanivek** [comment]
This issue was closed by https://github.com/mirage/irmin/pull/1951

**Comment by clecat** [comment]
Thx for notification
