### ISSUE TITLE
"ERROR: No SSL or TLS support compiled into Conduit" for "irmin clone "

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [mirage/irmin#984]
Hi, 

When I try to run the command "irmin clone -s git $GIT_REPO_URL" , I am getting error as "ERROR: No SSL or TLS support compiled into Conduit" could anyone help me ?

P.S:I posted the question in gitter channel too.

**Comment by samoht** [comment]
Which gitter channel? :-) 

Can you try with `opam install tls`? It's an optional dependency to `conduit`, it should be made explicit to avoid this kind of errors.

**Comment by Keerthana-Jayakumaran** [comment]
**Hi,
The gitter channel link :  "https://gitter.im/mirage/ocaml-cohttp"

1) I ran the mentioned command, but i got an installation error for "conf-gmp ",**

The following actions will be performed:
  - install   conf-gmp          1      [required by conf-gmp-powm-sec, zarith]
  - install   zarith            1.9.1  [required by mirage-crypto-pk]
  - install   conf-gmp-powm-sec 1      [required by mirage-crypto-pk]
  - install   asn1-combinators  0.2.2  [required by x509]
  - install   mirage-crypto-pk  0.6.2  [required by tls]
  - install   x509              0.10.0 [required by tls]
  - install   tls               0.11.0
  - recompile conduit-lwt-unix  2.1.0  [uses tls]
  - recompile cohttp-lwt-unix   2.5.1  [uses conduit-lwt-unix]
  - recompile git-unix          2.1.2  [uses cohttp-lwt-unix]
  - recompile irmin-unix        2.1.0* [uses git-unix]
===== 7 to install | 4 to recompile =====
Do you want to continue? [Y/n] Y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[asn1-combinators.0.2.2] found in cache
[cohttp-lwt-unix.2.5.1] found in cache

[conduit-lwt-unix.2.1.0] found in cache
[git-unix.2.1.2] found in cache
[mirage-crypto-pk.0.6.2] found in cache
[tls.0.11.0] found in cache
[x509.0.10.0] found in cache
[zarith.1.9.1] found in cache
[irmin-unix.2.1.0] synchronised from git+file:///home/keerthana/projects/coldChain/IrminWorks/irminGitRepo/irmin#master

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-gmp failed at
        "/home/keerthana/.opam/opam-init/hooks/sandbox.sh build sh -exc cc -c
        $CFLAGS -I/usr/local/include test.c".

#=== ERROR while compiling conf-gmp.1 =========================================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.09.0 | https://opam.ocaml.org#95eb9ec5
# path        ~/.opam/4.09.0/.opam-switch/build/conf-gmp.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -exc cc -c $CFLAGS -I/usr/local/include test.c
# exit-code   1
# env-file    ~/.opam/log/conf-gmp-9961-126656.env
# output-file ~/.opam/log/conf-gmp-9961-126656.out
### output ###
# + cc -c -I/usr/local/include test.c
# test.c:1:17: fatal error: gmp.h: No such file or directory
# compilation terminated.
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build conf-gmp 1
+- 
- No changes have been performed

The packages you requested declare the following system dependencies. Please
make sure they are installed before retrying:
    libgmp-dev

**2) I tried to install "conf-gmp" , That also threw an error.**

opam install conf-gmp
The following actions will be performed:
  - install conf-gmp 1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-gmp failed at
        "/home/keerthana/.opam/opam-init/hooks/sandbox.sh build sh -exc cc -c
        $CFLAGS -I/usr/local/include test.c".

#=== ERROR while compiling conf-gmp.1 =========================================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.09.0 | https://opam.ocaml.org#95eb9ec5
# path        ~/.opam/4.09.0/.opam-switch/build/conf-gmp.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -exc cc -c $CFLAGS -I/usr/local/include test.c
# exit-code   1
# env-file    ~/.opam/log/conf-gmp-10155-5f1023.env
# output-file ~/.opam/log/conf-gmp-10155-5f1023.out
### output ###
# + cc -c -I/usr/local/include test.c
# test.c:1:17: fatal error: gmp.h: No such file or directory
# compilation terminated.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build conf-gmp 1
+- 
- No changes have been performed

The packages you requested declare the following system dependencies. Please
make sure they are installed before retrying:
    libgmp-dev

**Comment by samoht** [comment]
Did you try to install `libgmp-dev` on your system as advised (with `sudo apt install libgmp-dev`)? Or try `opam depext tls` to install all the external dependency automatically.

Also I completely forgot we had a gitter chat for ocaml-cohttp! Is the link still advertised somewhere? We should probably take it out as no cohttp maintainers are actually looking at that channel.

**Comment by Keerthana-Jayakumaran** [comment]
Thank you. @samoht . its working. When i was searching for the solution,  I got the gitter link.
I have another doubt that. Will irmin works only with http ?
Because when i tried with 'ssh' to avoid providing login details while push command. But I was getting error.
While pushing using "http" also I was getting error as ""irmin: [ERROR] The HTTP decoder returns an error: (`No_assert_predicate #predicate).
ERROR: (Invalid_argument "Sync.push_exn: (`Sync No anonymous write access.)")

**Comment by samoht** [comment]
Currently irmin+git just support the Git HTTP(s) and TCP protocols. There are work in progress to add SSH support too, see https://github.com/mirage/ocaml-git/pull/362

I would be happy to discuss the alternatives/workaround if you could tell me a bit more about the context of your projects!

**Comment by Keerthana-Jayakumaran** [comment]
Thanks @samoht 
We just want to store key-value pairs for different time instances and should be able to revert to any previous state. I could do clone, after I created the key-value pairs locally, I could not push the changes to the remote repo.

**Comment by CraigFe** [comment]
@samoht: we're currently linking to the Gitter chat [from the `ocaml-cohttp` README](https://github.com/mirage/ocaml-cohttp#ocaml-cohttp----an-ocaml-library-for-http-clients-and-servers).

**Comment by samoht** [comment]
@Keerthana-Jayakumaran How do you do the initial clone? Do you need ssh to communicate with the remote server hosting the repository? Initially, maybe you could try to run a Git server instead, and push/pull to it using TCP on port 9418 (see "The Git Protocol" on https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols) ?

**Comment by Keerthana-Jayakumaran** [comment]
sorry! for the late reply @samoht . I do not want ssh. I was trying to see the possible ways to push the changes using irmin.  I cloned using command "irmin clone -s git <gitrepoHTTPlink>". After that, I did some set operations and I tried to push the changes to the remote repo using "irmin push -s git <gitrepoHTTPlink>".  I was ended with an error  "(No_assert_predicate #predicate). ERROR: (Invalid_argument "Sync.push_exn: (Sync No anonymous write access.)")".

**Comment by mdaudali** [comment]
@Keerthana-Jayakumaran If you're serving the repository over HTTP, it's likely that the remote server does not have `http.receivepack = true` set for that particular repository. [Git's HTTP backend](https://git-scm.com/docs/git-http-backend) rejects anonymous writes without. Try editing the `.git/config` file in the remote repository and adding 
`[http]
    receivepack=true
` or running `git config http.receivepack true`

**Comment by ke389954** [comment]
Thanks @mdaudali

**Comment by samoht** [comment]
I am closing the issue but feel free to re-open a new one if you have further questions.
