### ISSUE TITLE
Error : Unbound module Infix while running the example given in the readme file

### ISSUE THREAD

**Issue by sahanakk** [mirage/irmin#985]
I am trying to run(build) the example program to set key values using irmin given in the readme file. But I am getting the below mentioned error.

    $ dune build main.exe
     Entering directory '/home/sahana/work/irmin_ocaml/ocaml_ex'
     File "bin/main.ml", line 1, characters 5-17:
     1 | open Infix.Option
      ^^^^^^^^^^^^
    Error: Unbound module Infix

**Comment by pascutto** [comment]
Can you please show the code that you are trying to compile (or just the beginning if it's too long)? The example in the readme does not contain `open Infix.Option` on its first line, but `open Lwt.Infix`.

**Comment by sahanakk** [comment]
I am sorry the error is 

    $dune build main.exe
    Entering directory '/home/sahana/work/irmin_ocaml/ocaml_ex'
    File "bin/main.ml", line 1, characters 5-14:
    1 | open Lwt.Infix
         ^^^^^^^^^
    Error: Unbound module Lwt

And the program is the one in the readme file.

**Comment by pascutto** [comment]
Can you check that:
- `lwt` is correctly installed (if you installed `irmin-unix` it also installed `lwt`).
- You mentioned `lwt` is in the `libraries` stanza of your `dune` file

**Comment by sahanakk** [comment]
Yes I had not mentioned lwt in the dune file . Now there is another error.

    23 |     Store.set t ~info:(info "Updating foo/bar") ["foo"; "bar"] "testing 123" >>= fun () ->
                                                                                          ^^
    Error: This variant pattern is expected to have type
             (unit, Store.write_error) result
           The constructor () does not belong to type result

Is there any tutorial or something that i can refer for Irmin other than the official document(because it does not contain the build steps) or any prerequisites to start working with irmin

**Comment by CraigFe** [comment]
See https://irmin.org/, which contains a similar example on the index (updated to use the current API), and also an extended tutorial.

**Comment by pascutto** [comment]
> Yes I had not mentioned lwt in the dune file . Now there is another error.
> 
> ```
> 23 |     Store.set t ~info:(info "Updating foo/bar") ["foo"; "bar"] "testing 123" >>= fun () ->
>                                                                                       ^^
> Error: This variant pattern is expected to have type
>          (unit, Store.write_error) result
>        The constructor () does not belong to type result
> ```

There was indeed an issue un the README example. `Store.set_exn` should be used instead of `Store.set`. You can find this examples under `examples/` (`readme.ml`) where all examples are checked and working. Thanks for noticing, we'll fix it!

**Comment by sahanakk** [comment]
Thanks it's working now.
